#!/bin/bash
set -x -e

CWD=$(pwd)

PRGNAM=$(basename $CWD)
ARCH=$(uname -m)
GITHUB_REPO=factor/factor
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/${GITHUB_REPO}/releases/latest | grep tag_name | grep -o "[0-9.]*")}
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
PREFIX=/usr

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}

mkdir -p $TMP

# cleaning
rm -fr $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY

[ -e $TMP/$PRGNAM ] && rm -fr $TMP/$PRGNAM
cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

./build.sh update

# installation
mkdir -p $PKG$PREFIX/libexec/$PRGNAM
cp -a * $PKG$PREFIX/libexec/$PRGNAM

mkdir -p $PKG$PREFIX/{bin,doc/$PRGNAM-$VERSION}
cat <<EOF > $PKG$PREFIX/bin/$PRGNAM
#!/bin/bash
cd $PREFIX/libexec/$PRGNAM
./$PRGNAM \$@
EOF
chmod +x $PKG$PREFIX/bin/$PRGNAM
( cd $PKG$PREFIX/doc/$PRGNAM-$VERSION
    ln -s ../libexec/$PRGNAM/readme.html
    ln -s ../libexec/$PRGNAM/license.txt
)

# packaging
cd $PKG
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (A practical stack language)
$PRGNAM:
$PRGNAM: Factor is expressive, fast, supports interactive development and has a
$PRGNAM: full-featured library. Factor runs on all common platforms and Factor
$PRGNAM: applications are portable between them. Factor can deploy stand-alone
$PRGNAM: applications on all platforms.
$PRGNAM:
$PRGNAM: see $PREFIX/doc/$PRGNAM-$VERSION
$PRGNAM:
$PRGNAM: http://factorcode.org/
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
