#!/bin/bash

# variables
VERSION=${VERSION:-"trunk"}
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/taiwins/taiwins --recursive $REPOSITORY
cd $REPOSITORY
git pull --all
git submodule update

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM/

[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

meson setup \
      --prefix /usr \
      --mandir /usr/man/ \
      -Dbuild-doc=true \
      build/
ninja -C build/
cd build/
meson install --destdir=$PKG
cd ../

cat <<EOF > $PKG$PREFIX/bin/start_taiwins.sh
#!/bin/bash

export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SAL_USE_VCLPLUGIN=gtk3

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export GDK_BACKEND=wayland
export CLUTTER_BACKEND=gdk

export SDL_VIDEODRIVER=wayland

export XDG_CURRENT_DESKTOP=taiwins

[ -e $HOME/.profile ] && . $HOME/.profile

exec /usr/bin/taiwins -s /usr/bin/taiwins-shell -c /usr/bin/taiwins-console
EOF
chmod +x $PKG$PREFIX/bin/start_taiwins.sh

mkdir -p $PKG/usr/share/wayland-sessions/
cat <<EOF > $PKG/usr/share/wayland-sessions/taiwins.desktop
[Desktop Entry]
Name=Taiwins
Comment=a modern wayland compositor
Exec=/usr/bin/start_taiwins.sh
Type=Application
EOF

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -a docs/ build/html/ LICENSE *.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (taiwins, a modern wayland compositor)
$PRGNAM:
$PRGNAM: Taiwins is a dynamic wayland window manager, supports both tiling
$PRGNAM: and floating layout. It is designed to be modern and modular. It is
$PRGNAM: extensible through lua script and it has built-in shell and widgets
$PRGNAM: implementation through nuklear GUI. It also supports popular tiling
$PRGNAM: window manager features like gapping.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/taiwins/taiwins
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
