#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=noarch

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories/
PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
if [ ! -e $REPOSITORIES/$PRGNAM ]; then
    mkdir -p $REPOSITORIES/$PRGNAM
    ( cd $REPOSITORIES/$PRGNAM
        httrack http://home.iae.nl/users/mhx/sf.html
    )
else
    ( cd $REPOSITORIES/$PRGNAM
        httrack --update
    )
fi

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORIES/$PRGNAM $PKG$PREFIX/doc/$PRGNAM

ebook-convert $PKG$PREFIX/doc/$PRGNAM/home.iae.nl/users/mhx/sf.html \
	$PKG$PREFIX/doc/$PRGNAM/$PRGNAM.epub \
	--authors="Leo Brodie" \
	--author-sort="Brodie, Leo" \
	--title="Starting FORTH" \
	--title-sort="Starting FORTH" \
	--cover=$PKG$PREFIX/doc/$PRGNAM/home.iae.nl/users/mhx/sf\ front.jpg \
	--language=English \
	--rating=5

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM («Starting Forth» book)
$PRGNAM: 
$PRGNAM: Starting Forth, First Edition is from 1981. These web pages were designed in
$PRGNAM: 2003, when it became apparent that SF would never be re-issued by the
$PRGNAM: copyright holder. A small supply of about 500 books was all that was left.
$PRGNAM: When you can get hold of the original, do so.
$PRGNAM: In this transcript Forth code has been ANSified. The samples should run on,
$PRGNAM: at least, iForth and SwiftForth. Where necessary, statements that were valid
$PRGNAM: in 1981 have been exchanged with statements more appropriate for 2003 (when
$PRGNAM: this tribute was written).
$PRGNAM: http://home.iae.nl/users/mhx/sf.html
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
