#!/bin/sh

# Copyright 2008, 2009  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Slackware build script for emacs-trunk

# Written by Dušan Stefanović (stefanovic.dusan@gmail.com)
# Modified by Robby Workman <rworkman@slackbuilds.org>
# Modified by Patrick Volkerding <volkerdi@slackware.com>
# Modified by Gwenhael Le Moine <gwenhael.le.moine@gmail.com>

CWD=$(pwd)

PRGNAM=emacs
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
ARCH=${ARCH:-$(uname -m)}
NUMJOBS=${NUMJOBS:-" -j3 "}
BUILD=${BUILD:-1}
BRANCH=${BRANCH:-"emacs-26"}

TAG=cyco
OUTPUT=/tmp
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

SLKCFLAGS="-O2 -fPIC"

X_TOOLKIT=${X_TOOLKIT:=lucid}

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM

[ ! -e $REPOSITORY ] && git clone git://git.savannah.gnu.org/emacs.git $REPOSITORY

( cd $REPOSITORY
  git checkout $BRANCH
  git pull
  [ -e Makefile ] && make distclean
)
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cd $TMP
mkdir -p $TMP/$PRGNAM
SRCDIR=$REPOSITORY

cd $PRGNAM || exit 1
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

( cd $SRCDIR
  ./autogen.sh
)

EMACS_VERSION=$(grep "AC_INIT(GNU Emacs," $SRCDIR/configure.ac | cut -d, -f 2 | tr -d \ )

CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      $SRCDIR/configure \
      --prefix=/usr \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --program-prefix="" \
      --program-suffix="" \
      --mandir=/usr/man \
      --infodir=/usr/info \
      --with-x \
      --with-x-toolkit=$X_TOOLKIT \
      --without-toolkit-scroll-bars \
      --enable-link-time-optimization \
      --with-compress-install \
      --without-gconf \
      --with-gameuser=":games" \
      --disable-libsystemd \
      --disable-build-details \
      --build=${ARCH}-slackware-linux

make bootstrap

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG || exit 1

( cd $PKG/usr/bin
  rm emacs
  mv emacs-${EMACS_VERSION} emacs-${EMACS_VERSION}-with-x11
  ln -s emacs-${EMACS_VERSION}-with-x11 emacs
#   cat <<EOF > $PKG/usr/bin/emacs
# #!/bin/sh

# XMODIFIERS= GTK_IM_MODULE= QT_IM_MODULE= /usr/bin/emacs-${EMACS_VERSION}-with-x11 "\$@"
# EOF
#   chmod +x $PKG/usr/bin/emacs
)

# I don't care for broken permissions.
chmod 755 $PKG/var/games/emacs
chown -R games:root $PKG/var/games/emacs

# This avoids a collision with Exuberant Ctags...
mv $PKG/usr/bin/ctags $PKG/usr/bin/ctags-emacs
mv $PKG/usr/man/man1/ctags.1 $PKG/usr/man/man1/ctags-emacs.1

find $PKG | xargs file | grep -e "executable" -e "shared object" \
    | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

rm $PKG/usr/info/dir*

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a  BUGS \
   CONTRIBUTE \
   COPYING \
   ChangeLog \
   INSTALL \
   INSTALL.REPO \
   README \
   $PKG/usr/doc/$PRGNAM

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
     |-----handy-ruler------------------------------------------------------|
emacs: emacs (GNU Emacs)
emacs:
emacs: Emacs is the extensible, customizable, self-documenting real-time
emacs: display editor. If this seems to be a bit of a mouthful, an
emacs: easier explanation is that Emacs is a text editor and more. At
emacs: its core is an interpreter for Emacs Lisp, a dialect of the Lisp
emacs: programming language with extensions to support text editing.
emacs: This version supports X.
emacs:
emacs: http://www.gnu.org/software/emacs/
emacs:
EOF

cat <<EOF > $PKG/install/doinst.sh
# Vim ships a better (IMHO) version of ctags, and we don't want
# to overwrite it with this one.  If you really want emacs' ctags
# either copy or link it into place yourself, or remove the vim
# packages and reinstall emacs.  Besides, does anyone know/use
# *both* emacs and vi?  I'd think that would bring the universe
# to an end.  ;-)
if [ ! -e usr/bin/ctags ]; then
  cp -a usr/bin/ctags-emacs usr/bin/ctags
  cp -a usr/man/man1/ctags-emacs.1.gz usr/man/man1/ctags.1.gz
fi
EOF

# Make the .desktop file
mkdir -p $PKG/usr/share/applications
cat << "EOF" > $PKG/usr/share/applications/$PRGNAM.desktop
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=emacs
Icon=emacs.png
Terminal=0
Name=Emacs
Comment=Text Editor
Categories=Application;Development;
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-${EMACS_VERSION}_$VERSION-$ARCH-$BUILD$TAG.txz
