#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-0.6.4}

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr $PRGNAM $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone https://github.com/adapta-project/adapta-gtk-theme.git $REPOSITORY
cd $REPOSITORY
git pull --all
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/$PRGNAM

# Preparation
cd $TMP/$PRGNAM
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Configuration
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o "64") \
    --sysconfdir=/etc \
    --disable-gnome \
    --disable-cinnamon \
    --disable-flashback \
    --disable-mate \
    --disable-openbox

# Building
make

# Installation
make install DESTDIR=$PKG

mkdir -p $PKG$PREFIX/share/$PRGNAM
cd $PKG$PREFIX/share/$PRGNAM
cp $TMP/$PRGNAM/ROMs/*rom*.bz2 .
find . -name "*.bz2" -exec bunzip2 {} \;

# Cleaning
cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (An adaptive Gtk+ theme based on Material Design Guidelines.)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/adapta-project/adapta-gtk-theme
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
