#!/bin/sh

# variables
TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

VERSION=1.4.3

DOCS="AUTHORS ChangeLog COPYING INSTALL NEWS README TODO"

ARCH=$(uname -m)
BUILD=1


PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && \
    wget -c http://ftp1.fr.freebsd.org/pub/frugalware/frugalware-current/source/lib-extra/libconfig/$PRGNAM-$VERSION.tar.gz \
    -O $CWD/$PRGNAM-$VERSION.tar.gz
tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

# configuration
CFLAGS=$SLCKFLAGS \
CPPFLAGS=$SLCKFLAGS \
./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o 64) \
    --infodir=$PREFIX/info

# compilation
make -j3 PREFIX=$PREFIX

# installation
make install DESTDIR=$PKG

# correction
cd $PKG
chown -R root:root *

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cd $TMP/$PRGNAM-$VERSION
cp -R $DOCS $PKG/usr/doc/$PRGNAM-$VERSION

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;
[ -d $PKG/usr/info ] && find $PKG/usr/info -type f -name "*.info*" -exec gzip -9f {} \;
[ -d $PKG/usr/info ] && rm $PKG/usr/info/dir{,.gz,.new}

# Strip binaries
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)


# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/doinst.sh
cd /usr/info
[ -e dir ] && rm dir
[ -e dir.gz ] && rm dir.gz
[ -e dir.new ] && rm dir.new
for file in \$(ls *.gz | grep -v ".*\-[0-9]\+\.gz")
do
    install-info \$file ./dir
done
EOF
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Configuration file library for C and C++.)
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM: http://hyperrealm.com/libconfig/libconfig.html
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
