#!/bin/bash
set -x -e

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-1.4.0}
ARCH=${ARCH:-java}
BUILD=${BUILD:-1}


TAG=gwh
TMP=${TMP:-/tmp/$TAG}
OUTPUT=${OUTPUT:-/tmp}
PKG=$TMP/pkg-$PRGNAM
PREFIX=${PREFIX:-/usr}

# cleaning
rm -fr $PKG

# do we have the sources?
if [ ! -e $CWD/$PRGNAM-$VERSION.zip ] ; then
   ( cd $CWD
      wget -c http://repo1.maven.org/maven2/org/clojure/clojure/$VERSION/clojure-$VERSION.zip
   )
fi

# unpacking
mkdir -p $PKG$PREFIX/libexec
( cd $PKG$PREFIX/libexec
    unzip $CWD/${PRGNAM}-$VERSION.zip
)

# compilation
( cd $PKG$PREFIX/libexec/$PRGNAM-$VERSION
    ant
)

# installation
mkdir -p $PKG$PREFIX/{bin,doc/$PRGNAM-$VERSION}
cat <<EOF > $PKG$PREFIX/bin/$PRGNAM
#!/bin/bash
java -jar $PREFIX/libexec/$PRGNAM-$VERSION/clojure.jar \$@
EOF
chmod +x $PKG$PREFIX/bin/$PRGNAM

cd $PKG$PREFIX/libexec/$PRGNAM-$VERSION
mv doc/ *.html *.txt test/ $PKG$PREFIX/doc/$PRGNAM-$VERSION

rm *.xml #.gitignore
rm -r src #classes

rm $PRGNAM.jar
ln -s $PRGNAM-$VERSION.jar $PRGNAM.jar
    # rm $PRGNAM-sources.jar
    # ln -s $PRGNAM-sources-$VERSION.jar $PRGNAM-sources.jar
    # rm $PRGNAM-slim.jar
    # ln -s $PRGNAM-slim-$VERSION.jar $PRGNAM-slim.jar

# packaging
cd $PKG
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (JVM targetting Lisp dialect)
$PRGNAM: 
$PRGNAM: Clojure is a dynamic programming language that targets the Java Virtual
$PRGNAM: Machine (and the CLR ). It is designed to be a general-purpose language,
$PRGNAM: combining the approachability and interactive development of a scripting
$PRGNAM: language with an efficient and robust infrastructure for multithreaded
$PRGNAM: programming.
$PRGNAM: 
$PRGNAM: see $PREFIX/doc/$PRGNAM-$VERSION
$PRGNAM: 
$PRGNAM: http://clojure.org
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d - )-$ARCH-$BUILD$TAG.txz
