#!/bin/bash

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=noarch

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/kuno/npm-zsh-completion.git $REPOSITORY
cd $REPOSITORY
git pull --all
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/share/zsh/site-functions/
cp $REPOSITORY/npm-zsh-completion.sh $PKG$PREFIX/share/zsh/site-functions/_npm

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp $REPOSITORY/README.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (npm completion for zsh)
$PRGNAM:
$PRGNAM: zsh completion shell script for npm
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/kuno/npm-zsh-completion
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
