#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/mwitmer/guile-xcb.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
./configure \
    --prefix=$PREFIX \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o 64) \
    --mandir=$PREFIX/man \
    --infodir=$PREFIX/info
make
make install DESTDIR=$PKG

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A guile implementation of the X protocol using xml/xcb)
$PRGNAM:
$PRGNAM: Guile XCB is an X11 client library written entirely in Guile. It make
$PRGNAM: use of the Guile compiler and virtual machine to turn XML descriptions
$PRGNAM: of the X protocol provided by the XCB project into Guile object code
$PRGNAM: files.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/mwitmer/guile-xcb
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
