#!/bin/bash

# variables
GITHUB_REPO=nwg-piotr/gopsuinfo
VERSION=${VERSION:-latest}

BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
[ ! -e "$REPOSITORY" ] && git clone https://github.com/${GITHUB_REPO} "$REPOSITORY"
cd "$REPOSITORY" || exit
git pull --all

cp -R "$REPOSITORY" $TMP/
cd "$TMP/$PRGNAM/" || exit

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-taggerdate | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
if [ "$VERSION" == "trunk" ]; then
    VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
else
    git checkout "$VERSION"
fi

make get
go get github.com/tklauser/go-sysconf

make build

mkdir -p "$PKG"/usr/bin
make install DESTDIR="$PKG"

mkdir -p "$PKG"/usr/doc/"$PRGNAM"
cp ./LICENSE ./*.md "$PKG/usr/doc/$PRGNAM/"

# correction
cd "$PKG" || exit
chown -R root:root ./*

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below kanshis it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# kanshi exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (display system usage info as text)
$PRGNAM:
$PRGNAM: A gopsutil-based command to display system usage info as text in
$PRGNAM: panels like Waybar or icon/text in tint2 and nwg-panel executors
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/${GITHUB_REPO}
EOF

# empaquetage
rm -f "$PKG"/{,usr/}lib"$(uname -m | grep -o 64)"/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/"$PRGNAM"-"$VERSION"-"$ARCH"-$BUILD$TAG.txz
