#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
GITHUB_REPO=jezhiggins/arabica
VERSION=${VERSION:-latest}
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
    *) ARCH=$( uname -m ) ;;
  esac
fi

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

if [ "$ARCH" = "i486" ]; then
    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
elif [ "$ARCH" = "arm" ]; then
    SLKCFLAGS="-O2"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM

[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO} $REPOSITORY
cd $REPOSITORY
git pull --all

cd $TMP
cp -R $REPOSITORY $PRGNAM

cd $PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION
chown -R root:root .
find -L . \
     \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      autoreconf -i

CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      ./configure \
      --prefix=/usr \
      --sysconfdir=/etc \
      --mandir=/usr/man \
      --libdir=/usr/lib$(uname -m | grep -o 64) \
      --localstatedir=/var \
      --build=$ARCH-slackware-linux \
      --host=$ARCH-slackware-linux

make
make install DESTDIR=$PKG

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

      |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (An XML and HTML processing toolkit)
$PRGNAM:
$PRGNAM: Arabica is an XML and HTML processing toolkit, providing SAX2, DOM,
$PRGNAM: XPath, and XSLT implementations, written in Standard C++
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/jezhiggins/arabica
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-${VERSION//-/_}-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
