#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)

BUILD=1
VERSION=1
ARCH="noarch"

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# Cleaning
rm -fr $PKG
mkdir -p $PKG$PREFIX/share/games/rtcw/main

# Installation
for i in mp_pak0.pk3 mp_pak1.pk3 mp_pak2.pk3 pak0.pk3 sp_pak1.pk3 sp_pak2.pk3; do
    cp $CWD/$i $PKG$PREFIX/share/games/rtcw/main/
done

# Cleaning
chown -R root:root $PKG
find $PKG -type f -exec chmod 644 {} \;
chmod +x $PKG$PREFIX/bin/*

# Packaging
cd $PKG
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Official data for iortcw)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/iortcw/iortcw
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
