#!/bin/bash
# Slackware build script for ledger
# Written by Lionel Young (redtricycle at gmail dot com)
# updated and adapted to my own taste by Gwenhael Le Moine <gwenhael.le.moine-AT-gmail.com>

set -e

CWD=$(pwd)

PRGNAM=$(basename $CWD)
UPSTREAM_REPO=https://github.com/ledger/ledger
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-3}
TAG=${TAG:-gwh}

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PYTHON=" --python "

if [ "$ARCH" = "i486" ]; then
    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
    SLKCFLAGS="-O2"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
fi

rm -rf $PKG
mkdir -p $TMP $PKG/usr
cd $TMP
rm -rf $PRGNAM

[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
( cd $REPOSITORY && git pull && git submodule update --init )
cp -R $REPOSITORY $PRGNAM

cd $PRGNAM || exit 1
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

cmake . \
      -DUSE_DOXYGEN=ON \
      -DBoost_NO_BOOST_CMAKE=ON \
      -DUSE_PYTHON=ON \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_MANDIR=/usr/man
make -j$(nproc) || exit 1
make install DESTDIR=$PKG || exit 1

[ -e $PKG/usr/share/man ] && mv $PKG/usr/share/man $PKG/usr/
[ -e $PKG/usr/share/doc ] && rm -fr $PKG/usr/share/doc
[ -e $PKG/usr/man ] && find $PKG/usr/man/ -type f -name \*.\? -exec gzip -9 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM/scripts
cp -a \
   *.md contrib/ doc/ python/ \
   $PKG/usr/doc/$PRGNAM
( cd $PKG/usr/bin
  for i in report; do
      ln -s ../doc/$PRGNAM/contrib/$i ledger-$i
  done
)


find $PKG | xargs file | grep -e "executable" -e "shared object" \
    | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

[ -e $PKG/usr/info/dir ] && rm -f $PKG/usr/info/dir
[ -e $PKG/usr/info ] && find $PKG/usr/info/ -type f -exec gzip -9 {} \;

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
|-----handy-ruler------------------------------------------------------|
ledger: ledger (a command-line accounting program)
ledger:
ledger: Ledger is an accounting program which is invoked from the command-line
ledger: using a textual ledger file. See the documentation ( use "info ledger"
                                                             ledger: or read ledger.pdf from the website) for full documentation on how to
ledger: create a ledger file and using Ledger to generate reports.
ledger:
ledger: Homepage: http://wiki.github.com/jwiegley/ledger
ledger:
ledger:
ledger:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
