#!/bin/sh
# Slackware build script for ledger
# Written by Lionel Young (redtricycle at gmail dot com)
# updated and adapted to my own taste by Gwenhael Le Moine <gwenhael.le.moine-AT-gmail.com>

CWD=$(pwd)

PRGNAM=$(basename $CWD)
BRANCH=${BRANCH:="CURRENT"}
VERSION=${VERSION:=${BRANCH}_$(date +%F | tr - .)}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-2}
TAG=${TAG:-cyco}

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PYTHON=""                       # " --python "

if [ "$ARCH" = "i486" ]; then
    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
    SLKCFLAGS="-O2"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
fi

rm -rf $PKG
mkdir -p $TMP $PKG/usr
cd $TMP
rm -rf $PRGNAM

[ ! -e $REPOSITORY ] && git clone https://github.com/ledger/ledger.git $REPOSITORY
( cd $REPOSITORY && git pull && git submodule update --init )
cp -R $REPOSITORY $PRGNAM

cd $PRGNAM || exit 1
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

case $BRANCH in
    "RELEASE")
        git checkout -b stable v$VERSION
        ;;
    "CURRENT")
        git checkout -b master origin/master
        ;;
    "BETA")
        git checkout -b $VERSION release/$VERSION
        ;;
    "ALPHA")
        git checkout -b next origin/next
        ;;
    *)
esac
[ $BRANCH != "RELEASE" ] && VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

./acprep pull

./acprep --prefix=/usr $PYTHON opt config -- -DUSE_DOXYGEN=ON -DBoost_NO_BOOST_CMAKE=ON #  -DUSE_PYTHON=ON

./acprep --prefix=/usr $PYTHON opt make || exit 1
./acprep --prefix=/usr $PYTHON opt -- make install DESTDIR=$PKG || exit 1

mv $PKG/usr/share/man $PKG/usr/
rm -fr $PKG/usr/share/doc
find $PKG/usr/man/ -type f -name \*.\? -exec gzip -9 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/scripts
cp -a \
   *.md contrib/ doc/ python/ \
   $PKG/usr/doc/$PRGNAM-$VERSION
( cd $PKG/usr/bin
  for i in report; do
      ln -s ../doc/$PRGNAM-$VERSION/contrib/$i ledger-$i
  done
)


find $PKG | xargs file | grep -e "executable" -e "shared object" \
    | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

rm -f $PKG/usr/info/dir
find $PKG/usr/info/ -type f -exec gzip -9 {} \;

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
|-----handy-ruler------------------------------------------------------|
ledger: ledger (a command-line accounting program)
ledger:
ledger: Ledger is an accounting program which is invoked from the command-line
ledger: using a textual ledger file. See the documentation ( use "info ledger"
                                                             ledger: or read ledger.pdf from the website) for full documentation on how to
ledger: create a ledger file and using Ledger to generate reports.
ledger:
ledger: Homepage: http://wiki.github.com/jwiegley/ledger
ledger:
ledger:
ledger:
EOF

cd $TMP/package-$PRGNAM
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
