#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/ledger/ledger"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

#configuration
cmake . \
      -DUSE_DOXYGEN=ON \
      -DBoost_NO_BOOST_CMAKE=ON \
      -DUSE_PYTHON=ON \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_MANDIR=/usr/man

#build
make -j$(nproc) || exit 1

#install
make install DESTDIR=$PKG || exit 1

[ -e "$PKG"/usr/share/man ] && mv "$PKG"/usr/share/man "$PKG"/usr/
[ -e "$PKG"/usr/share/doc ] && rm -fr "$PKG"/usr/share/doc
[ -e "$PKG"/usr/man ] && find "$PKG"/usr/man/ -type f -name \*.\? -exec gzip -9 {} \;

mkdir -p "$PKG"/usr/doc/"$PRGNAM"/scripts
cp -a \
   ./*.md contrib/ doc/ python/ \
   "$PKG"/usr/doc/"$PRGNAM"
( cd "$PKG"/usr/bin || exit 1
  ln -s ../doc/"$PRGNAM"/contrib/report ledger-report
)


find "$PKG" | xargs file | grep -e "executable" -e "shared object" \
    | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

[ -e "$PKG"/usr/info/dir ] && rm -f "$PKG"/usr/info/dir
[ -e "$PKG"/usr/info ] && find "$PKG"/usr/info/ -type f -exec gzip -9 {} \;

mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
|-----handy-ruler------------------------------------------------------|
ledger: ledger (a command-line accounting program)
ledger:
ledger: Ledger is an accounting program which is invoked from the command-line
ledger: using a textual ledger file. See the documentation ( use "info ledger"
                                                             ledger: or read ledger.pdf from the website) for full documentation on how to
ledger: create a ledger file and using Ledger to generate reports.
ledger:
ledger: Homepage: http://wiki.github.com/jwiegley/ledger
ledger:
ledger:
ledger:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
