#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +%Y.%m.%d_%H.%M)
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
cd $REPOSITORIES
if [ -e $REPOSITORIES/$PRGNAM ] ; then
    ( cd $REPOSITORIES/$PRGNAM
        git pull
    )
else
    git clone "http://github.com/tylerhall/simple-php-framework.git" $REPOSITORIES/$PRGNAM
fi


mkdir -p $PKG/srv/www/htdocs
cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
find $PKG/srv/www/htdocs -name \.git\* -exec rm -fr {} \;

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (The Simple PHP Framework)
$PRGNAM: 
$PRGNAM: The Simple PHP Framework is a pragmatic approach to building websites with PHP 5.
$PRGNAM: It’s geared towards web design shops and freelance programmers looking for a
$PRGNAM: common foundation to quickly bring web projects to life. Without getting too
$PRGNAM: technical, SPF follows the no-framework Framework method coined by Rasmus
$PRGNAM: Lerdorf — with a little Active Record thrown in for good measure.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://clickontyler.com/simple-php-framework/
$PRGNAM: 
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
