#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    mkdir -p $(dirname $REPOSITORY)
    git clone https://github.com/mwitmer/guile-wm.git $REPOSITORY
else
    ( cd $REPOSITORY
      git pull
    )
fi

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
./configure \
    --prefix=$PREFIX \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o 64) \
    --mandir=$PREFIX/man \
    --infodir=$PREFIX/info
make
make install DESTDIR=$PKG

mkdir -p $PKG$PREFIX/doc/$PRGNAM
mv $PKG$PREFIX/share/wm-init-sample.scm $PKG$PREFIX/doc/$PRGNAM/

mkdir -p $PKG/etc/X11/xinit/
cp $CWD/xinitrc.$PRGNAM $PKG/etc/X11/xinit/
chmod +x $PKG/etc/X11/xinit/xinitrc.$PRGNAM

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;
# Compress info pages if they exist (and remove the dir file)
if [ -d $PKG/usr/info ]; then
    gzip -9 $PKG/usr/info/*.info
    rm -f $PKG/usr/info/dir
fi

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A Window Manager Toolkit for Guile Scheme)
$PRGNAM:
$PRGNAM: Guile-WM is a framework for creating an X window manager (or any other
$PRGNAM: X application, really) and a set of useful modules designed for that
$PRGNAM: purpose. Users are encouraged to pick and choose from ones presently
$PRGNAM: available and contribute their own as well!
$PRGNAM: Guile-WM relies /heavily/ on its user init file. In fact, it won't do
$PRGNAM: anything on its own without one. The intention is to provide something
$PRGNAM: 100% configurable.
$PRGNAM:
$PRGNAM: https://github.com/mwitmer/guile-wm
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
