#!/bin/sh
#exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
for kernel in /boot/2.* ; do
    if [ -e $kernel/bzImage ] ; then
        echo "menuentry \"Slackware $(basename $kernel)\" {"
        echo "  set root=(hd0,2)"
        echo "  linux  /boot/$kernel/bzImage root=/dev/sda6 ro resume=/dev/sda5"
        echo "}"
    fi
done
