#!/bin/sh
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-0.6.4}

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

# Cleaning
rm -fr $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone https://github.com/WernerFP/Shades-of-gray-theme.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

# Preparation
mkdir -p $PKG$PREFIX/share/
cd $PKG$PREFIX/share/
cp -R $REPOSITORY themes
cd themes
mkdir -p $PKG$PREFIX/doc/$PRGNAM
mv LICENSE Readme $PKG$PREFIX/doc/$PRGNAM

# Cleaning
cd $PKG
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (A flat dark GTK-theme with ergonomic contrasts)
$PRGNAM:
$PRGNAM: It supports Gnome, Cinnamon, Xfce4, Mate and Openbox. Theme customizations
$PRGNAM: for Firefox, Thunderbird and Inkscape are additionally included.
$PRGNAM: Shades-of-gray is available in seven color variants:
$PRGNAM: Gray, Arch, Cerulean, Firebrick, Harvest, Orient, Patina
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://www.gnome-look.org/p/1244058/
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
