#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
UPSTREAM_REPO=https://github.com/FreshRSS/FreshRSS
VERSION=${VERSION:-latest}
ARCH=${ARCH:-noarch}
BUILD=${BUILD:-2}

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM

PREFIX=/usr

# nettoyage préalable
rm -fr $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY

mkdir -p $PKG/opt/

cp -R $REPOSITORY $PKG/opt/$PRGNAM
cd $PKG/opt/$PRGNAM
git checkout dist
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

# installation
chown -R apache:apache $PKG/opt/$PRGNAM/
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp $PKG/opt/$PRGNAM/*.txt $PKG/opt/$PRGNAM/*.md $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG

find $PKG -name \.git\* -exec rm -fr {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/doinst.sh
#!/bin/bash

grep -q "/opt/FreshRSS/app/actualize_script.php" /var/spool/cron/crontabs/apache || echo "*/15  *  *  *  * php -f /opt/FreshRSS/app/actualize_script.php" >> /var/spool/cron/crontabs/apache
EOF

cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A free, self-hostable news aggregator…)
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://freshrss.org
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
