#!/bin/bash

# Slackware build script for lua53

# Copyright 2018 Azure Zanculmarktum <zanculmarktum@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Some of the codes were taken from development/lua/lua.SlackBuild

CWD=${CWD:-$(pwd)}
PRGNAM=$(basename $CWD)
VERSION=${VERSION:-5.3.6}
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

if [ -z "$ARCH" ]; then
case "$( uname -m )" in
  i?86) ARCH=i586 ;;
  arm*) ARCH=arm ;;
  *) ARCH=$( uname -m ) ;;
esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/_repositories/$PRGNAM}

mkdir -p $REPOSITORY

if [ "$ARCH" = "i586" ]; then
    SLKCFLAGS="-O2 -march=i586 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
elif [ "$ARCH" = "aarch64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
else
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf lua-$VERSION

[ ! -e $REPOSITORY/lua-$VERSION.tar.gz ] && wget -c https://www.lua.org/ftp/lua-$VERSION.tar.gz -O  $REPOSITORY/lua-$VERSION.tar.gz

tar xvf $REPOSITORY/lua-$VERSION.tar.gz
cd lua-$VERSION
chown -R root:root .
find -L . \
     \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
     -o -perm 511 \) -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
     -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

eval $(sed -ne '/^\(V\|R\)= /s, ,,p' Makefile)

sed -i \
    -e '/^INSTALL_TOP= /s,\(/usr\).*,\$(DESTDIR)\1,' \
    -e '/^INSTALL_LIB= /s,lib,&'"${LIBDIRSUFFIX}"',' \
    -e '/^INSTALL_CMOD= /s,lib,&'"${LIBDIRSUFFIX}"',' \
    Makefile

sed -i \
    -e '/^CFLAGS= /s,-O2,'"$SLKCFLAGS"',' \
    -e '/-DLUA_USE_LINUX.*-Wl,-E -ldl -lreadline/s|-lreadline|& -lncurses|' \
    src/Makefile

sed -i \
    -e '/^#define LUA_ROOT/s,".*,"/usr/",' \
    -e '/^#define LUA_CDIR/s,"lib,&'"${LIBDIRSUFFIX}"',' \
    src/luaconf.h

make linux
make install DESTDIR=$PKG

# Now let's build the shared library
mkdir -p shared
cd shared
ar -x $PKG/usr/lib${LIBDIRSUFFIX}/liblua.a
gcc -ldl -lreadline -lncurses -lm -shared *.o -o liblua.so.$R
cp -a liblua.so.$R $PKG/usr/lib${LIBDIRSUFFIX}
( cd $PKG/usr/lib${LIBDIRSUFFIX}
  ln -s liblua.so.$R liblua.so.$V
  ln -s liblua.so.$R liblua.so.${V%??}
  ln -s liblua.so.$R liblua.so
  ln -s liblua.so.$R liblua$(echo $R | cut -d. -f1,2).so
  ln -s liblua.so.$R liblua$(echo $R | cut -d. -f1).so
  ln -s liblua.so.$R liblua$R.so
)
cd - >/dev/null

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
cd $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
sed \
  -e '/^V= /s, .*, '"$V"',' \
  -e '/^R= /s, .*, '"$R"',' \
  -e '/^prefix= /s,\(/usr\).*,\1,' \
  -e '/^INSTALL_LIB= /s,lib,&'"${LIBDIRSUFFIX}"',' \
  -e '/^INSTALL_CMOD= /s,lib,&'"${LIBDIRSUFFIX}"',' \
  -e '/^libdir=/s,/lib,&'"${LIBDIRSUFFIX}"',' \
  $REPOSITORY/lua.pc.in > lua.pc

ln -s lua.pc lua-$V.pc
ln -s lua.pc lua${V%.?}${V#?.}.pc
cd - >/dev/null

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a README doc/* $PKG/usr/doc/$PRGNAM
cat $REPOSITORY/SlackBuild > $PKG/usr/doc/$PRGNAM/SlackBuild

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

   |-----handy-ruler------------------------------------------------------|
lua: lua (a powerful, fast, light-weight, embeddable scripting language)
lua:
lua: Lua combines simple procedural syntax with powerful data description
lua: constructs based on associative arrays and extensible semantics.
lua: Lua is dynamically typed, runs by interpreting bytecode for a
lua: register-based virtual machine, and has automatic memory management
lua: with incremental garbage collection, making it ideal for
lua: configuration, scripting, and rapid prototyping.
lua:
lua:
lua:
EOF

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
