#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
#VERSION=${VERSION:-daily-master}
VERSION=${VERSION:-8.0.0}
ARCH="noarch"	# hardcode ARCH
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

VHOST=${VHOST:-vhosts/$PRGNAM/}
DOCROOT=${DOCROOT:-/var/www/${VHOST}htdocs}

PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -eu

rm -rf $PKG
mkdir -p $TMP $OUTPUT $PKG/$DOCROOT
cd $PKG/$DOCROOT/
rm -rf $PRGNAM-$VERSION

[ ! -e $CWD/$PRGNAM-$VERSION.tar.bz2 ] && wget -c http://download.owncloud.org/community/$PRGNAM-$VERSION.tar.bz2 -O $CWD/$PRGNAM-$VERSION.tar.bz2
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 -o -perm 755 \) \
 -exec chmod 750 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 -o -perm 644 \) \
 -exec chmod 640 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a AUTHORS COPYING-AGPL $PKG/usr/doc/$PRGNAM

# Change ownership and perms and create a link.
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/$PRGNAM
chmod 0750 $PKG/$DOCROOT/$PRGNAM
chmod 0770 $PKG/$DOCROOT/$PRGNAM/{config,apps}

mkdir -p $PKG/install
cat <<EOF > $PKG/install/doinst.sh
#!/bin/bash
chown -R $PHPUSER:$PHPGROUP $DOCROOT/$PRGNAM/apps

grep -q "/var/www/${VHOST}htdocs/owncloud/cron.php" /var/spool/cron/crontabs/apache || echo "*/15  *  *  *  * php -f /var/www/${VHOST}htdocs/owncloud/cron.php" >> /var/spool/cron/crontabs/apache

echo "Upgrading database and applications"
( cd /var/www/${VHOST}htdocs/owncloud/
sudo -u $PHPUSER php ./occ upgrade
)
echo "Post-installation process completed"
EOF

cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (self-hosted cloud platform)
$PRGNAM:
$PRGNAM: Access. Sync. Share.
$PRGNAM: ownCloud provides universal access to your files via the web, your computer
$PRGNAM: or your mobile devices — wherever you are.
$PRGNAM: It also provides a platform to easily view & sync your contacts, calendars
$PRGNAM: and bookmarks across all your devices and enables basic editing right on
$PRGNAM: the web.
$PRGNAM:
$PRGNAM: http://owncloud.org
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr - _)_$(date +%F | tr - .)-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
