#!/bin/bash

# variables
GITHUB_REPO=janeczku/calibre-web
VERSION=${VERSION:-latest}
BUILD=${BUILD:-2}

RUNNING_USER=${RUNNING_USER:-gwh}
RUNNING_GROUP=${RUNNING_GROUP:-users}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/_repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --all

mkdir -p $PKG/opt
cp -r $REPOSITORY $PKG/opt/
cd $PKG/opt/$PRGNAM

case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION=$(git tag --sort=-taggerdate | head -n1)
        git checkout $VERSION
        ;;
    *)
        git checkout $VERSION
        ;;
esac

rm -fr $PKG/opt/$PRGNAM/{.git*,.editorconfig,.eslintrc}
chown -R ${RUNNING_USER}:${RUNNING_GROUP} $PKG/opt/$PRGNAM

mkdir -p $PKG/etc/rc.d/
cp -r $CWD/rc $PKG/etc/rc.d/rc.$PRGNAM
sed -i "s|RUNNING_USER|$RUNNING_USER|" $PKG/etc/rc.d/rc.$PRGNAM

# change default password
NEW_DEFAULT_PASSWORD=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;)
sed -i "s|admin123|$NEW_DEFAULT_PASSWORD|g" cps/*
pip3 install --target vendor -r requirements.txt -r optional-requirements.txt

# correction
cd $PKG

# embaumement
mkdir -p $PKG/install

# cat <<EOF > $PKG/install/doinst
# chown -R ${RUNNING_USER}:${RUNNING_GROUP} /opt/$PRGNAM
# EOF

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Web app for browsing, reading and downloading eBooks stored in a Calibre database)
$PRGNAM:
$PRGNAM: Calibre-Web is a web app providing a clean interface for browsing,
$PRGNAM: reading and downloading eBooks using an existing Calibre database.
$PRGNAM:
$PRGNAM: default user: admin
$PRGNAM: default password: $NEW_DEFAULT_PASSWORD
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/${GITHUB_REPO}
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
