#!/bin/sh

# variables
RUNNING_USER=${RUNNING_USER:-gwh}
RUNNING_GROUP=${RUNNING_GROUP:-users}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/janeczku/calibre-web.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG/opt
cp -r $REPOSITORY $PKG/opt/
rm -fr $PKG/opt/$PRGNAM/{.git*,.editorconfig,.eslintrc}
chown -R ${RUNNING_USER}:${RUNNING_GROUP} $PKG/opt/$PRGNAM

mkdir -p $PKG/etc/rc.d/
cp -r $CWD/rc $PKG/etc/rc.d/rc.$PRGNAM
sed -i "s|RUNNING_USER|$RUNNING_USER|" $PKG/etc/rc.d/rc.$PRGNAM

cd $PKG/opt/$PRGNAM
# change default password
NEW_DEFAULT_PASSWORD=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;)
sed -i "s|admin123|$NEW_DEFAULT_PASSWORD|g" cps/*
pip3 install --target vendor -r requirements.txt

# correction
cd $PKG

# embaumement
mkdir -p $PKG/install

# cat <<EOF > $PKG/install/doinst
# chown -R ${RUNNING_USER}:${RUNNING_GROUP} /opt/$PRGNAM
# EOF

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Web app for browsing, reading and downloading eBooks stored in a Calibre database)
$PRGNAM:
$PRGNAM: Calibre-Web is a web app providing a clean interface for browsing,
$PRGNAM: reading and downloading eBooks using an existing Calibre database.
$PRGNAM:
$PRGNAM: default user: admin
$PRGNAM: default password: $NEW_DEFAULT_PASSWORD
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/janeczku/calibre-web
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
