#!/bin/sh

# Slackware build script for dbeaver

# Copyright 2014 Antonio Hernández Blas <hba.nihilismus@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# 2018: Modification by Gwenhael Le Moine

CWD=$(pwd)
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/${PRGNAM}/${PRGNAM}/releases/latest | grep tag_name | grep -o "[0-9.]*")}
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

ARCH=${ARCH:-$(uname -m)}
case "$ARCH" in
    i?86) ARCH=i586; SRCARCH=x86 ;;
  x86_64) SRCARCH=x86_64 ;;
       *) echo "$ARCH is not supported"; exit 1 ;;
esac

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

SRCNAM=${PRGNAM}-ce
SRCVER=$VERSION-linux.gtk.$SRCARCH
DESTDIR=$PKG/opt/

# mise en place
[ ! -e $CWD/${SRCNAM}-${VERSION}-linux.gtk.${SRCARCH}.tar.gz ] && wget -c -O $CWD/${SRCNAM}-${VERSION}-linux.gtk.${SRCARCH}.tar.gz https://github.com/${PRGNAM}/${PRGNAM}/releases/download/${VERSION}/${SRCNAM}-${VERSION}-linux.gtk.${SRCARCH}.tar.gz

mkdir -p $DESTDIR
cd $DESTDIR
tar xvf $CWD/$SRCNAM-$SRCVER.tar.gz
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
chmod ga+x $DESTDIR/$PRGNAM/$PRGNAM

mkdir -p $PKG/usr/bin
cat << EOF > $PKG/usr/bin/$PRGNAM
#!/bin/sh
cd \$HOME
/opt/$PRGNAM/$PRGNAM \$@
EOF
chmod 0755 $PKG/usr/bin/$PRGNAM

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  $DESTDIR/$PRGNAM/readme.txt $DESTDIR/$PRGNAM/licenses/* \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

       |-----handy-ruler------------------------------------------------------|
dbeaver: dbeaver (a universal database tool)
dbeaver:
dbeaver: DBeaver is free and open source (GPL) universal database tool for
dbeaver: developers and database administrators.
dbeaver:
dbeaver: Usability is the main goal of this project. It is multiplatform.
dbeaver: Based on opensource framework and allows writing of various
dbeaver: extensions (plugins).
dbeaver:
dbeaver: It supports any database having a JDBC driver.
dbeaver: Homepage: https://dbeaver.jkiss.org
EOF

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
