#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
ARCH=$(uname -m)
VERSION=${VERSION:-"$(curl -s https://ziglang.org/download/index.json | jq 'keys' | grep -v master | grep -v \\\[ | grep -v \\\] | tr -d , | tr -d \" | tr -d \  | sort -V | tail -n1)"}
BUILD=${BUILD:-1}

TAG="gwh"
OUTPUT=${OUTPUT:-"/tmp"}
TMP="/tmp/$TAG"
PKG="$TMP/pkg-$PRGNAM"
PREFIX=/usr

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM"}

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

mkdir -p "$REPOSITORY"

# cleaning
rm -fr "$PKG"

# unpacking
[ ! -e "$REPOSITORY/zig-${ARCH}-linux-${VERSION}.tar.xz" ] && wget -c "https://ziglang.org/download/${VERSION}/zig-${ARCH}-linux-${VERSION}.tar.xz" -O "$REPOSITORY/zig-${ARCH}-linux-${VERSION}.tar.xz"

mkdir -p "$TMP"
cd "$TMP" || exit 1
tar xvf "$REPOSITORY/zig-${ARCH}-linux-${VERSION}.tar.xz"
cd "zig-${ARCH}-linux-${VERSION}" || exit 1

# installation
mkdir -p "$PKG$PREFIX"/bin/
install -D zig "$PKG$PREFIX"/bin/zig

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
install -D LICENSE "$PKG$PREFIX"/doc/zig/LICENSE
cp -r lib "$PKG$PREFIX"
cp -r doc/ "$PKG$PREFIX"/doc/zig/

# packaging
cd "$PKG" || exit 1
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (robust, optimal, and clear programming language)
$PRGNAM:
$PRGNAM: Zig is a general-purpose programming language and toolchain for
$PRGNAM: maintaining robust, optimal, and reusable software.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://ziglang.org/
$PRGNAM:
EOF

/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
