#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
			  # remove old log files
REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
FONTDIR="/usr/share/fonts"

[ ! -e $REPOSITORY ] \
    && git clone https://github.com/chrissimpkins/Hack $REPOSITORY \
	|| (cd $REPOSITORY && git pull)

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/ $PKG/usr/doc/
cp -R $REPOSITORY $PKG/usr/doc/$PRGNAM
rm -fr $PKG/usr/doc/$PRGNAM/.git{ignore,}
mv $PKG/usr/doc/$PRGNAM/build/ttf $PKG$FONTDIR/TTF
#ln -s $PKG$FONTDIR/TTF $PKG/usr/doc/$PRGNAM/ttf
mv $PKG/usr/doc/$PRGNAM/build/otf $PKG$FONTDIR/OTF
#ln -s $PKG$FONTDIR/OTF $PKG/usr/doc/$PRGNAM/otf

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A typeface designed for source code)
$PRGNAM:
$PRGNAM: No frills. No gimmicks. Hack is hand groomed and optically balanced to be
$PRGNAM: a workhorse face for code.
$PRGNAM:
$PRGNAM: It has deep roots in the libre, open source typeface community and expands
$PRGNAM: upon the contributions of the Bitstream Vera & DejaVu projects.
$PRGNAM:
$PRGNAM:
$PRGNAM: http://sourcefoundry.org/hack/
$PRGNAM:
EOF

# Build the package:
cd $PKG
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
