#!/bin/bash

# variables
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone https://github.com/greshake/i3status-rust.git $REPOSITORY
cd $REPOSITORY
git pull --all
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM

cargo build --release

mkdir -p $PKG$PREFIX/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} $PKG$PREFIX/bin/ \;
chmod 755 $PKG$PREFIX/bin/*

mkdir -p $PKG$PREFIX/share/$PRGNAM
cp -R files/* $PKG$PREFIX/share/$PRGNAM

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R doc/ example/ LICENSE *.md $PKG$PREFIX/doc/$PRGNAM

mkdir -p $PKG$PREFIX/man
cp man/i3status-rs.1 $PKG$PREFIX/man
find $PKG$PREFIX/man -exec gzip -9 {} \;

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (resourcefriendly and feature-rich replacement for i3status)
$PRGNAM:
$PRGNAM: a feature-rich and resource-friendly replacement for i3status,
$PRGNAM: written in pure Rust. It provides a way to display "blocks" of system
$PRGNAM: information (time, battery status, volume, etc) on the i3 bar. It is
$PRGNAM: also compatible with sway.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/greshake/i3status-rust
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
