#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/greshake/i3status-rust"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

cargo build --release --features "pulseaudio"

mkdir -p "$PKG$PREFIX"/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} "$PKG$PREFIX"/bin/ \;
chmod 755 "$PKG$PREFIX"/bin/*

mkdir -p "$PKG$PREFIX/share/$PRGNAM"
cp -R files/* "$PKG$PREFIX/share/$PRGNAM"

# move doc/ to the appropriate location
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R doc/ examples/ LICENSE ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# mkdir -p "$PKG$PREFIX"/man/man1
# cp man/i3status-rs.1 "$PKG$PREFIX"/man/man1
# [ -d "$PKG$PREFIX"/man ] && find "$PKG$PREFIX"/man -exec gzip -9 {} \;

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX"/man ] && find "$PKG$PREFIX"/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG"/install

cat <<EOF > "$PKG"/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (resourcefriendly and feature-rich replacement for i3status)
$PRGNAM:
$PRGNAM: a feature-rich and resource-friendly replacement for i3status,
$PRGNAM: written in pure Rust. It provides a way to display "blocks" of system
$PRGNAM: information (time, battery status, volume, etc) on the i3 bar. It is
$PRGNAM: also compatible with sway.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
