#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://git.savannah.gnu.org/git/gforth"}
VERSION=${VERSION:-"latest"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all
git submodule update --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-taggerdate | head -n1)"
        git checkout "$VERSION"
        ;;
    *)
        git checkout "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# configuration
./BUILD-FROM-SCRATCH --prefix="${PREFIX}" \
                     --mandir="${PREFIX}/man" \
                     --infodir="${PREFIX}/info" \
                     --libdir="${PREFIX}/lib$(uname -m | grep -o 64)"

# compilation
make -j3

# installation
make install DESTDIR="$PKG"

rm "$PKG$PREFIX"/info/dir

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R AUTHORS Agenda BUGS BUILD-FROM-SCRATCH COPYING* ChangeLog* INSTALL* NEWS* README* ToDo* test/ doc/ ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

find "$PKG" -name \.git\* -exec rm -fr {} \;

[ -d "$PKG"/usr/man ] && find "$PKG"/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
cd "$PKG"
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
$PRGNAM: $PRGNAM (implementation of the Forth 2012 language.)
$PRGNAM:
$PRGNAM: A free, fast, featureful and portable implementation of the Forth 2012
$PRGNAM: language.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://gforth.org
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
