#!/bin/bash
# variables
VERSION=${VERSION:-latest}
BUILD=${BUILD:-3}

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
[ ! -e "$REPOSITORY" ] && git clone https://github.com/ErikReider/SwayNotificationCenter.git "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all

cp -R "$REPOSITORY" $TMP/
cd "$TMP/$PRGNAM/" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"

meson setup \
      --prefix /usr \
      --mandir /usr/man/ \
       build/
ninja -C build/
cd build/ || exit 1
meson install --destdir="$PKG"
cd ../

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R COPYING ./*.md "$PKG$PREFIX/doc/$PRGNAM/"
rm -fr "$PKG$PREFIX/share/doc"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*
[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below kanshis it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# kanshi exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.
     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Wayland background setter)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/ErikReider/SwayNotificationCenter
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
