#!/bin/bash -e

# variables
CWD=$(pwd)
VERSION=${VERSION:-1.4}
ITEMNB=${ITEMNB:-53678}
COMMITNB=${COMMITNB:-e7c3feb}

PRGNAM=$(basename "$CWD")
ARCH="AppImage"
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# nettoyage préalable
rm -fr "$PKG"

mkdir -p "$PKG"/opt/"$PRGNAM"

# mise en place
cd "$PKG"/opt/"$PRGNAM" || exit 1

wget -c https://inkscape.org/gallery/item/"${ITEMNB}"/Inkscape-"${COMMITNB}"-x86_64.AppImage -O "${PRGNAM}"-"${VERSION}".AppImage
chmod +x "${PRGNAM}"-"${VERSION}".AppImage

mkdir -p "$PKG$PREFIX"/bin/
cd "$PKG$PREFIX"/bin/ || exit 1
ln -s /opt/"$PRGNAM"/"${PRGNAM}"-"${VERSION}".AppImage inkscape

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
$PRGNAM: $PRGNAM (A powerful, free design tool)
$PRGNAM:
$PRGNAM: Whether you are an illustrator, designer, web designer
$PRGNAM: or just someone who needs to create some vector imagery,
$PRGNAM: Inkscape is for you!
$PRGNAM:
$PRGNAM:
$PRGNAM: https://www.inkscape.org
$PRGNAM:
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
