#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +%Y.%m.%d_%H.%M)
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
( cd $REPOSITORIES
    if [ -e $REPOSITORIES/$PRGNAM ] ; then
        ( cd $REPOSITORIES/$PRGNAM
            svn up
        )
    else
        svn checkout http://recaptcha.googlecode.com/svn/trunk/ $REPOSITORIES/$PRGNAM
    fi
)

mkdir -p $PKG/srv/www/htdocs
cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
find $PKG/srv/www/htdocs -name \.svn\* -exec rm -fr {} \;

( cd $PKG
    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Plugins and libraries for the reCAPTCHA API)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://recaptcha.net/
$PRGNAM: http://code.google.com/p/recaptcha/
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
