#!/bin/sh

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=1.0
ARCH=$(uname -m)
BUILD=1


TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr
DOCS="ABOUT-NLS AUTHORS ChangeLog COPYING* INSTALL NEWS README THANKS TODO"

SLCKFLAGS="-O2"
case $ARCH in
    "x86_64")
        SLCKFLAGS="$SLCKFLAGS -fPIC"
        ;;
    *)
esac

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
( cd $TMP
    [ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && \
        wget -c http://downloads.sourceforge.net/project/vimgadgets/$PRGNAM/$VERSION/$PRGNAM-$VERSION.tar.gz \
        -O $CWD/$PRGNAM-$VERSION.tar.gz
    tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
)

( cd $TMP/$PRGNAM-$VERSION
    # configuration
    CCPFLAGS=$SLCKFLAGS \
    CFLAGS=$SLCKFLAGS \
    LIBS="-lncursesw" \
    LDFLAGS="-L$PREFIX/lib$(echo $ARCH | grep -o 64)" \
    ./configure \
        --prefix=$PREFIX \
        --mandir=$PREFIX/man \
        --infodir=$PREFIX/info \
        --docdir=$PREFIX/doc/$PRGNAM-$VERSION \
        --includedir=$PREFIX/include \
        --libdir=$PREFIX/lib$(echo $ARCH | grep -o 64)

    # compilation
    make -j3 PREFIX=$PREFIX
    # installation
    make install DESTDIR=$PKG
    # WAT‽
    cp -R $PKG$PREFIX/lib$(echo $ARCH | grep -o 64)/$PRGNAM-$VERSION/include $PKG$PREFIX/
)

# correction
chown -R root:root $PKG/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
( cd $TMP/$PRGNAM-$VERSION
    cp -R $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
)

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
find $PKG | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find $PKG | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A Portable Foreign Function Interface Library )
$PRGNAM:
$PRGNAM: an implementation of the line breaking and word breaking algorithms as described
$PRGNAM: in Unicode Standard Annex 14 and Unicode Standard Annex 29, available at
$PRGNAM:     http://www.unicode.org/reports/tr14/tr14-26.html
$PRGNAM:     http://www.unicode.org/reports/tr29/tr29-17.html
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: Check this URL for up-to-date information:
$PRGNAM:     http://vimgadgets.sourceforge.net/libunibreak/
EOF

# empaquetage
( cd $PKG
    makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d -)-$ARCH-$BUILD$TAG.txz
)
