#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/simonmichael/hledger/releases/latest | grep tag_name | grep -o "[0-9.]*")}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-3}
TAG=${TAG:-gwh}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
PREFIX=/usr

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

mkdir -p "$REPOSITORY"

echo "$ARCH" | grep -q 64 && SRC_ARCH=x64
DOCS="CHANGES.md CONTRIBUTING.md CREDITS.md LICENSE README.md"
[ ! -e "$REPOSITORY/hledger-linux-${SRC_ARCH}-${VERSION}.tar.gz" ] && \
    wget -c "https://github.com/simonmichael/hledger/releases/download/${VERSION}/hledger-linux-${SRC_ARCH}.tar.gz" \
         -O "$REPOSITORY/hledger-linux-${SRC_ARCH}-${VERSION}.tar.gz"
# for d in $DOCS; do
#     [ ! -e "$REPOSITORY/${d}.${VERSION}" ] && \
#         wget -c "https://raw.githubusercontent.com/simonmichael/hledger/${VERSION}/${d}" \
#              -O "$REPOSITORY/${d}.${VERSION}"
# done
rm -fr "$PKG"

mkdir -p "$PKG$PREFIX/bin"
cd "$PKG$PREFIX/bin" || exit 1
tar xf "$REPOSITORY/hledger-linux-${SRC_ARCH}-${VERSION}.tar.gz"

mkdir -p "$PKG$PREFIX/man/man1"
mv ./*.1 "$PKG$PREFIX/man/man1"
find  "$PKG$PREFIX/man/man1" -exec gzip -9 {} \;

mkdir -p "$PKG$PREFIX/info"
mv ./*.info "$PKG$PREFIX/info"
find  "$PKG$PREFIX/info" -exec gzip -9 {} \;

mkdir -p "$PKG/usr/share/bash-completion/completions"
mv hledger-completion.bash "$PKG/usr/share/bash-completion/completions/hledger"
chmod 0644 "$PKG/usr/share/bash-completion/completions/hledger"

chmod +x "$PKG$PREFIX/bin"/*

# mkdir -p "$PKG$PREFIX/doc/hledger/"
# for d in $DOCS; do
#     [ -e "$REPOSITORY/${d}.${VERSION}" ] && \
#         cp "$REPOSITORY/${d}.${VERSION}" "$PKG$PREFIX/doc/hledger/${d}"
# done

mkdir -p "$PKG/etc/rc.d/"
cat <<EOF > "$PKG/etc/rc.d/rc.hledger-web.new"
#!/bin/sh
#
# Start/stop/restart hledger-web
#

DAEMON_USER=gwh
DAEMON_OPTIONS=" --server --empty --host=0.0.0.0 --port=7458 --file=/path/to/file.ledger --base-url=https://my-host.tld "

start() {
  if [ -x /usr/bin/hledger-web ]; then
    echo "Starting hledger-web daemon: /usr/bin/hledger-web "
    sudo -u \$DAEMON_USER /usr/bin/hledger-web \$DAEMON_OPTIONS 2> /dev/null &
  fi
}

stop() {
  killall hledger-web 2> /dev/null
}

restart() {
  stop
  sleep 1
  start
}

case "\$1" in
'start')
  start
  ;;
'stop')
  stop
  ;;
'restart')
  restart
  ;;
*)
  echo "usage \$0 start|stop|restart"
esac
EOF

mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/doinst.sh"
#!/bin/bash
[ ! -e /etc/rc.d/rc.hledger-web ] && mv /etc/rc.d/rc.hledger-web.new /etc/rc.d/rc.hledger-web
EOF

cat <<EOF > "$PKG/install/slack-desc"
       |-----handy-ruler--------------------------------------------------------|
$PRGNAM: $PRGNAM (ledger-cli-like plaintext accounting tool in Haskell)
$PRGNAM:
$PRGNAM: easy-to-use command-line/curses/web plaintext accounting tool; a modern
$PRGNAM: and largely compatible Haskell rewrite of Ledger
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://hledger.org/
$PRGNAM:
EOF

cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
