#!/bin/bash

# variables
GITHUB_REPO=qtile/qtile
VERSION=${VERSION:-latest}

BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO} $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM/

[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

# installation
python3 ./setup.py install --root=$PKG

cat <<EOF > $PKG$PREFIX/bin/start_qtile.sh
#!/bin/bash

export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SAL_USE_VCLPLUGIN=gtk3

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export GDK_BACKEND=wayland
export CLUTTER_BACKEND=gdk

export SDL_VIDEODRIVER=wayland

#export XDG_CURRENT_DESKTOP=qtile
export XDG_CURRENT_DESKTOP=Unity # for tray ?

[ -e $HOME/.profile ] && . $HOME/.profile

exec qtile start -b wayland
EOF
chmod +x $PKG$PREFIX/bin/start_qtile.sh

mkdir -p $PKG$PREFIX/share/wayland-sessions/
cp resources/qtile-wayland.desktop $PKG$PREFIX/share/wayland-sessions/

mkdir -p $PKG$PREFIX/share/xsessions/
cp resources/qtile.desktop $PKG$PREFIX/share/xsessions/

sed -i 's|Exec=qtile start -b wayland|Exec=/usr/bin/start_qtile.sh|' $PKG$PREFIX/share/wayland-sessions/qtile-wayland.desktop

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp LICENSE *.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A tiling window manager written and configured in Python)
$PRGNAM:
$PRGNAM: A full-featured, hackable tiling window manager written and
$PRGNAM: configured in Python
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://qtile.org
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
