#!/bin/bash

# variables

TAG=gwh
TMP=/tmp/$TAG
OUTPUT=/tmp
CWD=$(pwd)
PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

UPSTREAM_REPO=https://github.com/Fred78290/nct6687d
VERSION=${VERSION:-"trunk"}
KERNEL_VERSION=$(uname -r)

ARCH=$(uname -m)
BUILD=7

# mise en place
[ ! -e "$REPOSITORY" ] && git clone --quiet ${UPSTREAM_REPO} "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION=$(git tag --sort=-version:refname | head -n1)
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}_${KERNEL_VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# compilation
make

# installation
mkdir -p "$PKG/lib/modules/${KERNEL_VERSION}/kernel/drivers/hwmon/"
cp "${KERNEL_VERSION}/nct6687.ko" "$PKG/lib/modules/${KERNEL_VERSION}/kernel/drivers/hwmon/"

mkdir -p "$PKG/etc/modprobe.d/"
cat <<EOF > "$PKG"/etc/modprobe.d/blacklist_nct6683.conf
# Do not load the nct6683 module on boot.
blacklist nct6683
# uncomment the line below if blacklisting is not sufficient
# install nct6683 /bin/true
EOF

mkdir -p "$PKG/usr/doc/$PRGNAM/"
cp -R images/ LICENSE ./*.md "$PKG/usr/doc/$PRGNAM/"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/doinst.sh
#!/bin/bash

depmod

modprobe nct6687
EOF

cat <<EOF > "$PKG"/install/slack-desc
$PRGNAM: $PRGNAM (Linux kernel module for Nuvoton NCT6687-R)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
