#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH="noarch" 	# hardcode ARCH
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

DOCROOT=${DOCROOT:-/var/www/htdocs}

PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -eu

rm -rf $PKG
mkdir -p $TMP $OUTPUT $PKG/$DOCROOT
cd $PKG/$DOCROOT/
rm -rf $PRGNAM-$VERSION

REPOSITORY=/home/installs/SlackBuilds/repository/$PRGNAM

if [ -e $REPOSITORY ]; then
    (cd $REPOSITORY; git pull)
else
    git clone https://github.com/inthepoche/poche.git $REPOSITORY
fi

cp -R $REPOSITORY $PRGNAM

cd $PRGNAM
rm -fr .git .gitignore
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 -o -perm 755 \) \
 -exec chmod 750 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 -o -perm 644 \) \
 -exec chmod 640 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a *.md $PKG/usr/doc/$PRGNAM

# Change ownership and perms and create a link.
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/$PRGNAM
chmod 0750 $PKG/$DOCROOT/$PRGNAM

mkdir -p $PKG/install
cat <<EOF > $PKG/install/doinst.sh
#!/bin/sh
chown -R $PHPUSER:$PHPGROUP $DOCROOT/$PRGNAM/apps
EOF

cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (open source self hostable read-it-later web app)
$PRGNAM:
$PRGNAM: Abandon Pocket, Instapaper and other Readability service :
$PRGNAM: adopt poche. It is the same, but it is free (like in freedom)
$PRGNAM: and open source.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM: http://www.inthepoche.com/
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
