#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    git clone http://repo.or.cz/r/anything-config.git $REPOSITORY
else
	( cd $REPOSITORY
		git pull
	)
fi

mkdir -p $PKG$PREFIX/share/emacs/site-lisp $PKG$PREFIX/doc/$PRGNAM
cp -R $REPOSITORY $PKG$PREFIX/share/emacs/site-lisp
cd $PKG$PREFIX/share/emacs/site-lisp/$PRGNAM
find . \( -name ".git*" -o -name ".nosearch" \) -exec rm -fr {} \;

make

mv README doc/ $PKG$PREFIX/doc/$PRGNAM
rm Makefile

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (anything for Emacs)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.emacswiki.org/emacs/Anything
$PRGNAM: 
EOF

# empaquetage
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
