#!/bin/sh

# variables
CWD=$(pwd)

PRGNAM=$(basename $(pwd))
BRANCH=
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
ARCH=${ARCH:-$(uname -m)}
BUILD=1


TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories

DOCS="*.txt"

PREFIX=/usr

SLCKFLAGS=""

if [ ! -e $REPOSITORIES/$PRGNAM ]; then
    hg clone https://sigil.googlecode.com/hg/ $REPOSITORIES/$PRGNAM
else
    ( cd $REPOSITORIES/$PRGNAM
        hg pull -u
    )
fi

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
SRC_PATH=$REPOSITORIES/$PRGNAM
if [ -e $CWD/$PRGNAM-$VERSION.tar.?z* ] ; then
    tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
    SRC_PATH=.
    cd $TMP/$PRGNAM-$VERSION
else
    mkdir -p $TMP/$PRGNAM-$VERSION
    cd $TMP/$PRGNAM-$VERSION
fi

# configuration
cmake \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    $SRC_PATH


# compilation
make -j3

# installation
make install DESTDIR=$PKG


# correction
cd $PKG
chown -R root:root *

find $PKG -name \.hg\* -exec rm -fr {} \;

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)


# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A WYSIWYG ebook editor.)
$PRGNAM:
$PRGNAM: Sigil is a multi-platform WYSIWYG ebook editor. It is designed to
$PRGNAM: edit books in ePub format.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://code.google.com/p/sigil/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
