#!/bin/sh

# variables
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone https://github.com/symless/synergy-core.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
git submodule init
git submodule update

cmake \
  -D CMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
  -D CMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D LIB_SUFFIX=${LIBDIRSUFFIX}

make VERBOSE=1
make install DESTDIR=$PKG

strip $PKG/usr/bin/*

mkdir -p $PKG/usr/man/man1/
cp doc/synergys.man $PKG/usr/man/man1/synergys.1
cp doc/synergyc.man $PKG/usr/man/man1/synergyc.1

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R LICENSE README.md doc/ $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

          |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (core of Synergy, the keyboard and mouse sharing tool)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://symless.com/synergy
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
