#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
UPSTREAM_REPO="https://github.com/hyprwm/$PRGNAM"
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=2

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

# nettoyage préalable
rm -fr "$PKG" "$TMP"/"$PRGNAM"

mkdir -p "$PKG"

# mise en place
cd "$TMP" || exit 1
[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"

cd "$REPOSITORY" || exit1
git pull --all

cp -R "$REPOSITORY" "$TMP"/"$PRGNAM"
cd "$TMP"/"$PRGNAM" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" # || git checkout $VERSION
git submodule update --init --recursive

# configuration
cmake --no-warn-unused-cli \
      -DSYSCONFDIR=/etc \
      -DCMAKE_BUILD_TYPE:STRING=Release \
      -DCMAKE_INSTALL_PREFIX:STRING=${PREFIX} \
      -DNO_SYSTEMD:STRING=true \
      -DNO_UWSM:STRING=true \
      -S . \
      -B ./build

# compilation
cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`

# installation
cmake --install build --prefix "$PKG"$PREFIX --strip

mkdir -p "$PKG$PREFIX/doc/$PRGNAM/"
cp -R LICENSE VERSION ./*.md docs/ example/ assets/ "$PKG$PREFIX/doc/$PRGNAM/"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

mv "$PKG"/usr/share/man "$PKG"/usr/

[ -d "$PKG"/usr/man ] && find "$PKG"/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
$PRGNAM: $PRGNAM ( Wayland compositor )
$PRGNAM:
$PRGNAM: Hyprland is an independent, highly customizable, dynamic tiling Wayland
$PRGNAM:  compositor that doesn't sacrifice on its looks.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://hyprland.org
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM: REQUIRES: re2
EOF

# empaquetage
rm -f "$PKG"/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT"/"$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
