#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/aristocratos/btop"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        PKGVERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        PKGVERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$PKGVERSION"
        ;;
    *)
        PKGVERSION="$VERSION"
        git checkout --quiet "$PKGVERSION"
        ;;
esac

PKGNAM=${PRGNAM}

######################
# EMBED DEPENDENCIES #
######################
# rocm_smi_lib
EMBED_ROCM_SMI_LIB=${EMBED_ROCM_SMI_LIB:-"yes"}
if [ "$EMBED_ROCM_SMI_LIB" = "yes" ]; then
    ROCM_SMI_LIB_VERSION=${ROCM_SMI_LIB_VERSION:-$VERSION}
    ROCM_SMI_LIB_REPOSITORY=/var/cache/SlackBuilds.gwh/rocm_smi_lib
    [ ! -e "$ROCM_SMI_LIB_REPOSITORY" ] && git clone https://github.com/rocm/rocm_smi_lib.git "$ROCM_SMI_LIB_REPOSITORY"
    cd "$ROCM_SMI_LIB_REPOSITORY" || exit 1
    git reset --hard HEAD
    git pull --quiet --all

    mkdir -p "$TMP/$PRGNAM"/lib/
    cp -a "$ROCM_SMI_LIB_REPOSITORY" "$TMP/$PRGNAM"/lib/rocm_smi_lib
    cd "$TMP/$PRGNAM"/lib/rocm_smi_lib || exit 1
    case $ROCM_SMI_LIB_VERSION in
        trunk)
            # ROCM_SMI_LIB_VERSION="git_r$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)"
            ROCM_SMI_LIB_VERSION="r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
            ;;
        latest)
            ROCM_SMI_LIB_VERSION=$(git tag --sort=-version:refname | head -n1)
            git checkout --quiet "$ROCM_SMI_LIB_VERSION"
            ;;
        *)
            git checkout --quiet "$ROCM_SMI_LIB_VERSION"
            ;;
    esac
    PKGNAM="${PKGNAM}+rocm_smi_lib"
    PKGVERSION="${PKGVERSION}+${ROCM_SMI_LIB_VERSION}"
fi

PACKAGE_NAME="$PKGNAM-${PKGVERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

cd "$TMP/$PRGNAM/" || exit 1
make DESTDIR="$PKG" PREFIX=/usr RSMI_STATIC=true
make install DESTDIR="$PKG" PREFIX=/usr RSMI_STATIC=true
mv "$PKG$PREFIX"/share/man "$PKG$PREFIX/"

# move doc/ to the appropriate location
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp LICENSE ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM ( A monitor of resources )
$PRGNAM:
$PRGNAM: Resource monitor that shows usage and stats for processor, memory,
$PRGNAM: disks, network and processes.
$PRGNAM:
$PRGNAM: C++ version and continuation of bashtop and bpytop.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/aristocratos/btop
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
