#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/alacritty/alacritty"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

cargo build --release

mkdir -p "$PKG$PREFIX"/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} "$PKG$PREFIX"/bin/ \;
chmod 755 "$PKG$PREFIX"/bin/*

mkdir -p "$PKG$PREFIX"/man/man{1,5}
scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee "$PKG$PREFIX"/man/man1/alacritty.1.gz > /dev/null
scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee "$PKG$PREFIX"/man/man1/alacritty-msg.1.gz > /dev/null
scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee "$PKG$PREFIX"/man/man5/alacritty.5.gz > /dev/null
scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee "$PKG$PREFIX"/man/man5/alacritty-bindings.5.gz > /dev/null


mkdir -p "$PKG$PREFIX"/info
cp extra/alacritty.info "$PKG$PREFIX"/info/
gzip -9 "$PKG$PREFIX"/info/alacritty.info

mkdir -p "$PKG$PREFIX"/share/applications "$PKG$PREFIX"/share/pixmaps
cp extra/linux/Alacritty.desktop "$PKG$PREFIX"/share/applications/
cp extra/logo/alacritty-term.svg "$PKG$PREFIX"/share/pixmaps/Alacritty.svg

mkdir -p "$PKG$PREFIX"/share/appdata
cp extra/linux/org.alacritty.Alacritty.appdata.xml "$PKG$PREFIX"/share/appdata/

mkdir -p "$PKG$PREFIX"/share/bash-completion/completions
cp extra/completions/alacritty.bash "$PKG$PREFIX"/share/bash-completion/completions/alacritty

mkdir -p "$PKG$PREFIX"/share/zsh/site-functions
cp extra/completions/_alacritty "$PKG$PREFIX"/share/zsh/site-functions/

# move doc/ to the appropriate location
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -a docs/ extra/ scripts/ ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX"/man ] && find "$PKG$PREFIX"/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG"/install

cat <<EOF > "$PKG"/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A cross-platform, GPU-accelerated terminal emulator)
$PRGNAM:
$PRGNAM: Alacritty is a terminal emulator with a strong focus on simplicity
$PRGNAM: and performance. With such a strong focus on performance, included
$PRGNAM: features are carefully considered and you can always expect Alacritty
$PRGNAM: to be blazingly fast. By making sane choices for defaults, Alacritty
$PRGNAM: requires no additional setup. However, it does allow configuration of
$PRGNAM: many aspects of the terminal.
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
