#!/bin/sh

# variables
VERSION=${VERSION:-trunk_$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}


TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    git clone http://github.com/ginatrapani/todo.txt-cli.git $REPOSITORY
else
	( cd $REPOSITORY
		git pull
	)
fi

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
make
mkdir -p $PKG$PREFIX/{bin/,doc/$PRGNAM/}
mv todo.sh $PKG$PREFIX/bin/
mv * $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
chmod +x $PKG$PREFIX/bin/*

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (TODO.TXT Command Line Interface)
$PRGNAM:
$PRGNAM: A simple and extensible shell script for managing your todo.txt file.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://todotxt.com/
$PRGNAM: 
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
