#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)

BUILD=1
VERSION=${VERSION:-latest}

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

# Cleaning
rm -fr $TMP/$PRGNAM-$VERSION
rm -fr $PKG
mkdir -p $TMP

[ ! -e $REPOSITORY ] && git clone "http://repo.or.cz/r/cboard.git" $REPOSITORY
cd $REPOSITORY
git pull --all

# Preparation
cp -R $REPOSITORY $TMP/$PRGNAM-$VERSION
cd $TMP/$PRGNAM-$VERSION

[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

rm -fr debian
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man

make

# Installation
make install DESTDIR=$PKG

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp COPYING NEWS doc/config.example INSTALL README KnownBugs THANKS TODO $PKG$PREFIX/doc/$PRGNAM

# Cleaning
find $PKG | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find $PKG | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root $PKG
find $PKG -type f -exec chmod 644 {} \;
chmod +x $PKG$PREFIX/bin/*

# Packaging
cd $PKG
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (ncurses chess frontend)
$PRGNAM:
$PRGNAM: CBoard (Curses/Console Board) is an Ncurses frontend to chess engines
$PRGNAM: supporting the XBoard protocol. Supports reading and writing PGN
$PRGNAM: including roster tags, RAV, FEN, NAG and comments.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://benkibbey.wordpress.com/cboard/
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
