#!/bin/bash

PRGNAM=httrack
VERSION=3.45.1

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "64")

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

PREFIX=/usr

# Cleaning
rm -fr $TMP/$PRGNAM-* $PKG

# Fetching sources
cd $TMP
[ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && wget -c "http://download.httrack.com/cserv.php3?File=httrack.tar.gz" -O $CWD/$PRGNAM-$VERSION.tar.gz
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz

# Preparation
cd $TMP/$PRGNAM-$VERSION
chown -R root:root .
find . \
    \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
    -exec chmod 755 {} \; -o \
    \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
    -exec chmod 644 {} \;

# Building
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
	--prefix=$PREFIX \
	--mandir=$PREFIX/man \
	--libdir=$PREFIX/lib$LIBSUFFIX

LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
make

LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
make install DESTDIR=$PKG

# Cleaning
cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root .
find . \
    \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
    -exec chmod 755 {} \; -o \
    \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
    -exec chmod 644 {} \;
        
# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (offline browser utility)
$PRGNAM:
$PRGNAM: It allows you to download a World Wide Web site from the Internet to a local
$PRGNAM: directory, building recursively all directories, getting HTML, images, and
$PRGNAM: other files from the server to your computer. HTTrack arranges the original
$PRGNAM: site's relative link-structure.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://www.httrack.com/
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
