#!/bin/bash

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        git clone "https://github.com/m2ym/auto-complete.git" $REPOSITORY
fi

( cd $REPOSITORY
    git pull
)

mkdir -p $PKG$PREFIX/share/emacs/site-lisp
cp -R $REPOSITORY $PKG$PREFIX/share/emacs/site-lisp
( cd $PKG$PREFIX/share/emacs/site-lisp/$PRGNAM
    rm -fr .git*
    make
    mkdir -p $PKG$PREFIX/doc/$PRGNAM
    mv *.txt doc/ etc/ Makefile $PKG$PREFIX/doc/$PRGNAM
)

# correction
( cd $PKG
    chown -R root:root *
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (auto-completion for Emacs)
$PRGNAM: 
$PRGNAM: Auto Complete Mode is the most intelligent auto-completion extension
$PRGNAM: for GNU Emacs. Auto Complete Mode renews an old completion interface
$PRGNAM: and provides an environment that makes users could be more
$PRGNAM: concentrate on their own works.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://cx4a.org/software/auto-complete/
$PRGNAM: 
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
