#!/bin/bash

# variables
UPSTREAM_REPO=https://github.com/martinvonz/jj
VERSION=${VERSION:-latest}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone --quiet ${UPSTREAM_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --quiet --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout --quiet $VERSION

cargo build --release

mkdir -p $PKG$PREFIX/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} $PKG$PREFIX/bin/ \;
chmod 755 $PKG$PREFIX/bin/*

# Completions
mkdir -p $PKG/usr/share/bash-completion/completions/
$PKG$PREFIX/bin/jj util completion > $PKG/usr/share/bash-completion/completions/jj

mkdir -p $PKG/usr/share/fish/vendor_completions.d/
$PKG$PREFIX/bin/jj util completion --fish > $PKG/usr/share/fish/vendor_completions.d/jj.fish

mkdir -p $PKG/usr/share/zsh/site-functions/
$PKG$PREFIX/bin/jj util completion --zsh > $PKG/usr/share/zsh/site-functions/_jj

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -a AUTHORS LICENSE* ./*.md docs/ $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A Git-compatible DVCS that is both simple and powerful)
$PRGNAM:
$PRGNAM: Jujutsu is a Git-compatible DVCS. It combines features from Git (data
$PRGNAM: model, speed), Mercurial (anonymous branching, simple CLI free from
$PRGNAM: "the index", revsets, powerful history-rewriting), and Pijul/Darcs
$PRGNAM: (first-class conflicts), with features not found in most of them
$PRGNAM: (working-copy-as-a-commit, undo functionality, automatic rebase,
$PRGNAM: safe replication via rsync, Dropbox, or distributed file system).
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
