#!/bin/bash

# variables
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone http://github.com/aspiers/stow.git $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

autoconf
aclocal --force
automake --add-missing

./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man \
    --infodir=$PREFIX/info

make
make install DESTDIR=$PKG

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp AUTHORS COPYING INSTALL* MANIFEST* NEWS README* THANKS TODO $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -exec gzip -9 {} \;
find $PKG$PREFIX/info -type f -name dir -delete
find $PKG$PREFIX/info -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (a symlink farm manager program)
$PRGNAM:
$PRGNAM: GNU Stow is a symlink farm manager which takes distinct packages of
$PRGNAM: software and/or data located in separate directories on the
$PRGNAM: filesystem, and makes them appear to be installed in the same place.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/aspiers/stow
$PRGNAM: http://www.gnu.org/software/stow/
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
