#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=git$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORY ] && git clone http://github.com/rmurphey/jqfundamentals.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORY $PKG$PREFIX/doc/$PRGNAM
find $PKG$PREFIX/doc/$PRGNAM -name \.git\* -exec rm -fr {} \;

( cd $PKG
  mkdir -p install
  cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (JQuery book)
$PRGNAM:
$PRGNAM: jQuery is fast becoming a must-have skill for front-end developers. The
$PRGNAM: purpose of this book is to provide an overview of the jQuery JavaScript
$PRGNAM: library; when you're done with the book, you should be able to complete
$PRGNAM: basic tasks using jQuery, and have a solid basis from which to continue
$PRGNAM: your learning.
$PRGNAM:
$PRGNAM:
$PRGNAM: http://jqfundamentals.com/book/book.html
$PRGNAM:
EOF

  chown -R root:root *

  makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
