#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-6.2.20130902}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log
                          # remove old log files

FONTDIR="/usr/share/fonts"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/{misc,TTF} $PKG/usr/doc/$PRGNAM
cd $PKG$FONTDIR/
[ ! -e $CWD/${PRGNAM}_FontsOnly-$VERSION.zip ] && \
	wget -c --no-check-certificate "http://unifoundry.com/unifont-$VERSION.tar.gz" \
	-O $CWD/unifont-$VERSION.tar.gz
tar xf $CWD/unifont-$VERSION.tar.gz
cd unifont-$(echo $VERSION | grep -o "^.\..")
mv README unifont-intro.txt $PKG/usr/doc/$PRGNAM
mv font/precompiled/*.ttf ../TTF
mv font/precompiled/*.pcf.gz ../misc
cd ..
rm -fr unifont-$(echo $VERSION | grep -o "^.\..")

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM ( Font containing Unicode 6.2 MP )
$PRGNAM: 
$PRGNAM: The GNU unifont has a glyph for every printable code point in the
$PRGNAM: Unicode Basic Multilinguial Plane (BMP). The BMP is the first Unicode
$PRGNAM: "plane" of 65,536(16bit) code points, and includes character encoding
$PRGNAM: for most of the world's modern scripts.
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM: Website: http://unifoundry.com/unifont.html
$PRGNAM: 
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz

