#!/bin/bash
# variables
VERSION=${VERSION:-latest}
BUILD=2

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://codeberg.org/lukeflo/fuzzel-polkit-agent.git $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM/

[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

mkdir -p $PKG$PREFIX/bin
cp fuzzel-polkit-agent $PKG$PREFIX/bin/
chmod +x $PKG$PREFIX/bin/fuzzel-polkit-agent

mkdir -p $PKG$PREFIX/share/applications/
cp fuzzel-polkit-agent.desktop $PKG$PREFIX/share/applications/

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp ./*.md LICENSE $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below kanshis it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# kanshi exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.
     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Polkit agent for window managers, using fuzzel.)
$PRGNAM:
$PRGNAM: based on cmd-polkit
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://codeberg.org/lukeflo/fuzzel-polkit-agent
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
