#!/bin/sh

# variables
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=cyco
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    git clone http://github.com/phatina/simple-mtpfs.git $REPOSITORY
else
	( cd $REPOSITORY
		git pull
	)
fi

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
./autogen.sh
./configure \
	--prefix=$PREFIX \
	--mandir=$PREFIX/man

make
make install DESTDIR=$PKG

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc
cp AUTHORS COPYING ChangeLog INSTALL NEWS README $PKG$PREFIX/doc

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Simple MTP fuse filesystem driver.)
$PRGNAM:
$PRGNAM: SIMPLE-MTPFS (Simple Media Transfer Protocol FileSystem) is a file
$PRGNAM: system for Linux (and other operating systems with a FUSE
$PRGNAM: implementation, such as Mac OS X or FreeBSD) capable of operating on
$PRGNAM: files on MTP devices attached via USB to local machine. On the local
$PRGNAM: computer where the SIMPLE-MTPFS is mounted, the implementation makes
$PRGNAM: use of the FUSE (Filesystem in Userspace) kernel module. The practical
$PRGNAM: effect of this is that the end user can seamlessly interact with MTP
$PRGNAM: device files.
$PRGNAM: https://github.com/phatina/simple-mtpfs/
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
