#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=git$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORY ] && git clone http://github.com/sandal/rbp-book.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORY $PKG$PREFIX/doc/$PRGNAM
find $PKG$PREFIX/doc/$PRGNAM -name \.git\* -exec rm -fr {} \;

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Ruby Best Practices book)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://rubybestpractices.com/
$PRGNAM:
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
