#!/bin/bash

# variables
VERSION=${VERSION:-latest}

TAG=gwh
TMP=/tmp/$TAG
OUTPUT=/tmp
CWD=$(pwd)
REPOSITORIES=/var/cache/SlackBuilds.gwh

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)
BUILD=3

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
[ ! -e "$REPOSITORIES/$PRGNAM" ] && git clone https://github.com/keplerproject/luarocks.git "$REPOSITORIES/$PRGNAM"
( cd "$REPOSITORIES/$PRGNAM" || exit 1
  git pull
)

cp -R "$REPOSITORIES/$PRGNAM" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"

# configuration
CFLAGS=$SLCKFLAGS \
    CPPFLAGS=$SLCKFLAGS \
    ./configure \
    --prefix=$PREFIX \
    --lua-version="$(lua -v  | rg -o "[0-9]\.[0-9]" | head -n1)"

# compilation
make -j3 PREFIX=$PREFIX

# installation
make install DESTDIR="$PKG" ROCKS_TREE=$PREFIX/lib64/luarocks

mkdir -p "$PKG/etc/profile.d/"
cat <<EOF > "$PKG/etc/profile.d/luarocks.sh"
#!/bin/bash

eval \$(luarocks path)
EOF
# cat <<EOF > $PKG/etc/profile.d/luarocks.csh
# #!/bin/csh

# setenv PATH \$PATH:$PREFIX/lib64/luarocks/bin
# EOF
chmod +x "$PKG/etc/profile.d/*"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

mkdir -p "$PKG/usr/doc/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
cp -R ./*.md COPYING "$PKG/usr/doc/$PRGNAM"

[ -d "$PKG/usr/man" ] && find "$PKG/usr/man" -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
( cd "$PKG" || exit 1
  find . -print0 | xargs -0 file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -print0 | xargs -0 file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)


# embaumement
mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/slack-desc"
$PRGNAM: $PRGNAM (deployment and management system for Lua modules.)
$PRGNAM:
$PRGNAM: LuaRocks allows you to install Lua modules as self-contained packages
$PRGNAM: called [*rocks*]
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: LuaRocks is free software and uses the same license as Lua 5.1.
$PRGNAM:
$PRGNAM: http://luarocks.org
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
rm -f "$PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la"
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
