#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/keplerproject/luarocks"}
VERSION=${VERSION:-"latest"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# configuration
CFLAGS=$SLCKFLAGS \
    CPPFLAGS=$SLCKFLAGS \
    ./configure \
    --prefix="$PREFIX" \
    --lua-version="$(lua -v  | rg -o "[0-9]\.[0-9]" | head -n1)"

# compilation
make -j"$(nproc)" PREFIX="$PREFIX"

# installation
make install DESTDIR="$PKG" ROCKS_TREE="$PREFIX"/lib64/luarocks

mkdir -p "$PKG"/etc/profile.d/
cat <<EOF > "$PKG"/etc/profile.d/luarocks.sh
#!/bin/bash

eval \$(luarocks path)
EOF
chmod +x "$PKG"/etc/profile.d/*

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

mkdir -p "$PKG/usr/doc/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
cp -R ./*.md COPYING "$PKG/usr/doc/$PRGNAM"

[ -d "$PKG/usr/man" ] && find "$PKG/usr/man" -type f -name "*.?" -exec gzip -9f {} \;

# embaumement
mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/slack-desc"
$PRGNAM: $PRGNAM (deployment and management system for Lua modules.)
$PRGNAM:
$PRGNAM: LuaRocks allows you to install Lua modules as self-contained packages
$PRGNAM: called [*rocks*]
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: LuaRocks is free software and uses the same license as Lua 5.1.
$PRGNAM:
$PRGNAM: http://luarocks.org
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
rm -f "$PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la"
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
