#!/bin/sh

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/djpohly/dwl.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/

# configuration
[ -e $CWD/config.h ] && cat $CWD/config.h > config.h

sed -i 's|/usr/local|/usr|g' config.mk
cat <<EOF >> config.mk
CFLAGS += -DXWAYLAND
EOF

make

mkdir -p $PKG$PREFIX/bin/
install -D dwl $PKG$PREFIX/bin/dwl

cat <<EOF > $PKG$PREFIX/bin/start_dwl.sh
#!/bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SAL_USE_VCLPLUGIN=gtk3

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export GDK_BACKEND=wayland
export CLUTTER_BACKEND=gdk

export SDL_VIDEODRIVER=wayland

export XDG_CURRENT_DESKTOP=dwl

[ -e $HOME/.profile ] && . $HOME/.profile

exec dwl
EOF
chmod +x $PKG$PREFIX/bin/start_dwl.sh

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp LICENSE* README.md $PKG$PREFIX/doc/$PRGNAM/

mkdir -p $PKG/usr/share/wayland-sessions/
cat <<EOF > $PKG/usr/share/wayland-sessions/dwl.desktop
[Desktop Entry]
Name=dwl
Comment=dwm for Wayland
Exec=/usr/bin/start_dwl.sh
Type=Application
EOF

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below kanshis it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# kanshi exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (dwm for Wayland)
$PRGNAM:
$PRGNAM: dwl is a compact, hackable compositor for Wayland based on wlroots.
$PRGNAM: It is intended to fill the same space in the Wayland world that dwm
$PRGNAM: does in X11, primarily in terms of philosophy, and secondarily in
$PRGNAM: terms of functionality.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/djpohly/dwl
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
