#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)
BUILD=1
TAG=gwh
ARCH=noarch

OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr $PRGNAM $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone https://github.com/solarized/xresources.git $REPOSITORY
cd $REPOSITORY
git pull --all
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

# Installation
mkdir -p $PKG$PREFIX/{doc,share}/$PRGNAM
cp $REPOSITORY/X* $PKG$PREFIX/share/$PRGNAM
cp $REPOSITORY/{LICENSE,README.md} $PKG$PREFIX/doc/$PRGNAM

# Cleaning
cd $PKG
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Solarized for X Windows)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://github.com/solarized/xresources
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
