#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/fmtlib/fmt"}
VERSION=${VERSION:-"latest"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all
git submodule update --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout "$VERSION"
        ;;
    *)
        git checkout "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# configuration
cmake \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    .

# compilation
make -j"$(nproc)"

# installation
make install DESTDIR="$PKG"

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R ./*.rst ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

find "$PKG" -name \.git\* -exec rm -fr {} \;

[ -d "$PKG${PREFIX}/man" ] && find "$PKG${PREFIX}/man" -type f -name "*.?" -exec gzip -9f {} \;

# embaumement
mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/slack-desc"
$PRGNAM: $PRGNAM ( A modern formatting library )
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
