#!/bin/sh

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        cd $(dirname $REPOSITORY)
        git clone "git://git.sv.gnu.org/emms.git" $PRGNAM
fi

( cd $REPOSITORY
    git pull
)

cp -R $REPOSITORY $TMP
( cd $TMP/$PRGNAM
    make PREFIX=$PREFIX
    mkdir -p $PKG$PREFIX/info $PKG$PREFIX/man/man1 $PKG$PREFIX/share/emacs/site-lisp
    make install \
        PREFIX=$PKG$PREFIX \
        INFODIR=$PKG$PREFIX/info \
        MAN1DIR=$PKG$PREFIX/man/man1 \
        SITELISP=$PKG$PREFIX/share/emacs/site-lisp

    mkdir -p $PKG$PREFIX/doc/$PRGNAM
    cp -R AUTHORS COPYING FAQ NEWS README RELEASE doc/ $PKG$PREFIX/doc/$PRGNAM/
)

# correction
( cd $PKG
    chown -R root:root *
    find $PKG$PREFIX/info -type f -not -name "*.gz" -exec gzip -9 {} \;
)

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/doinst.sh
cd /usr/info
[ -e dir ] && rm dir
[ -e dir.gz ] && rm dir.gz
[ -e dir.new ] && rm dir.new
for file in \$(ls *.gz | grep -v ".*\-[0-9]\+\.gz")
do
    install-info \$file ./dir
done
EOF

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (The Emacs Multimedia System)
$PRGNAM: 
$PRGNAM: EMMS is the Emacs Multimedia System. It tries to be a clean and small
$PRGNAM: application to play multimedia files from Emacs using external players.
$PRGNAM: Many of it's ideas are derived from MpthreePlayer , but it tries to be
$PRGNAM: more general and cleaner.
$PRGNAM: The fact that EMMS is based on external players makes it powerful,
$PRGNAM: because it supports all formats that those players support, with no
$PRGNAM: effort from your side.
$PRGNAM: 
$PRGNAM: http://github.com/jwiegley/emacs-chess
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
