#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=trunk$(date +%Y.%m.%d_%H.%M)
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
( cd $REPOSITORIES
    if [ -e $REPOSITORIES/$PRGNAM ] ; then
        ( cd $REPOSITORIES/$PRGNAM
            git pull
        )
    else
        git clone git://gitorious.org/movicon//movicon.git $REPOSITORIES/$PRGNAM
    fi
)

mkdir -p $PKG/srv/www/htdocs
cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
find $PKG/srv/www/htdocs -name \.git\* -exec rm -fr {} \;

( cd $PKG
    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (MVC PHP Web framework)
$PRGNAM: 
$PRGNAM: Movicon is a very simple implementation of the MVC framework for web applications
$PRGNAM: written in PHP. Unlike other famous implementations, it aims to be simple,
$PRGNAM: straightforward and particularly easy to tweak and deploy.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://movicon.dyndns.org/
$PRGNAM: 
$PRGNAM: http://gitorious.org/movicon/
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
