#!/bin/bash

CWD=$(pwd)

GITHUB_REPO=pavouk/lgi
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/${GITHUB_REPO}/releases/latest | jq -r .tag_name | sed 's|^null$|trunk|')} # or VERSION=trunk

# default settings
PRGNAM=$(basename $CWD)
ARCH=$(uname -m)
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

DOCS="ABOUT-NLS AUTHORS BUGS COPYING ChangeLog INSTALL NEWS README TODO"

rm -rf $PKG $TMP/$PRGNAM
mkdir -p $PKG
cd $TMP

if [ -e $CWD/$PRGNAM-$VERSION.tar.xz ] ; then
    tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
else
    [ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY
    cd $REPOSITORY
git pull --all
    VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

    cp -R $REPOSITORY $PRGNAM
fi
cd $PRGNAM

LUA_VERSION=$(lua -v 2>&1 | grep -o "5\..")

sed -i \
    -e "s|/usr/local|/usr|" \
    -e "s|/lib/lua/|/share/lua/|" \
    -e "s|LUA_VERSION=5.1|LUA_VERSION=$LUA_VERSION|" \
    lgi/Makefile

LIBDIRSUFFIX=$( uname -m | grep -o 64 )

make LUA_LIBDIR=/usr/lib$LIBDIRSUFFIX/lua/$LUA_VERSION \
     LUA_SHAREDIR=/usr/share/lua/$LUA_VERSION \
     PREFIX=/usr CFLAGS="$SLKCFLAGS"
make LUA_LIBDIR=/usr/lib$LIBDIRSUFFIX/lua/$LUA_VERSION \
     LUA_SHAREDIR=/usr/share/lua/$LUA_VERSION \
     DESTDIR=$PKG install

cd $PKG

find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

mkdir -p install
cat << EOF > install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler-----------------------------------------------------|
$PRGNAM: $PRGNAM (Dynamic Lua binding to GObject libraries)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/${GITHUB_REPO}
$PRGNAM:
EOF

chown -R root:root $PKG

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
