#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=102
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log
                          # remove old log files

FONTDIR="/usr/share/fonts/TTF"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR $PKG/usr/doc/$PRGNAM-$VERSION
( cd $PKG$FONTDIR/
    [ ! -e $CWD/MgOpen.tar.gz ] && wget -c http://www.ellak.gr/pub/fonts/mgopen/files/MgOpen.tar.gz -O $CWD/MgOpen.tar.gz
    tar xf $CWD/MgOpen.tar.gz

    find . -type f -name "*.?TF" -o -name "*.?tf" -exec mv {} . \;
    find . -type f -not \( -name "*.?TF" -o -name "*.?tf" \) -exec mv {} $PKG/usr/doc/$PRGNAM-$VERSION \;
    find . -type d -exec rm -r {} \;
)

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (font)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.ellak.gr/pub/fonts/mgopen/index.en.html
$PRGNAM: 
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz 2>&1 | tee $OUTPUT//sbin/makepkg-${PRGNAM}.log
cd $OUTPUT
md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz.md5
cd -
cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt

