#!/bin/bash

# variables
GITHUB_REPO=werererer/japokwm
VERSION=${VERSION:-"latest"}
BUILD=2

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO} $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION=$(git describe --tags --abbrev=0)
        git checkout $VERSION
        ;;
    *)
        git checkout $VERSION
        ;;
esac

meson setup \
      --prefix /usr \
      --mandir /usr/man/ \
      -Dxwayland=true \
      -Dbash-completions=true \
      -Dzsh-completions=true \
      -Dfish-completions=true \
      build/

ninja -C build/
cd build/
meson install --destdir=$PKG
cd ../

cat <<EOF > $PKG$PREFIX/bin/start_japokwm.sh
#!/bin/bash

set -e

# export QT_QPA_PLATFORMTHEME=qt5ct
# export QT_QPA_PLATFORM=wayland-egl
# export QT_WAYLAND_FORCE_DPI=physical
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# export SAL_USE_VCLPLUGIN=gtk3

# export MOZ_ENABLE_WAYLAND=1
# export MOZ_DBUS_REMOTE=1

# export _JAVA_AWT_WM_NONREPARENTING=1

# # export GDK_BACKEND=wayland
# export CLUTTER_BACKEND=gdk

# export SDL_VIDEODRIVER=wayland

#export XDG_CURRENT_DESKTOP=japokwm
export XDG_CURRENT_DESKTOP=Unity # for waybar's tray?

# Décommenter s'il n'y a pas de curseur souris visible
# export WLR_NO_HARDWARE_CURSORS=1

[ -e $HOME/.profile ] && . $HOME/.profile

unset DISPLAY

export XDG_RUNTIME_DIR=/tmp/xdg-runtime-\$(id -u)
mkdir -p \$XDG_RUNTIME_DIR

export LIBSEAT_BACKEND=logind

exec dbus-run-session japokwm
EOF
chmod +x $PKG$PREFIX/bin/start_japokwm.sh

sed -i 's|Exec=japokwm|Exec=/usr/bin/start_japokwm.sh|' $PKG$PREFIX/share/wayland-sessions/japokwm.desktop

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R config LICENSE ./*.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A tiling wayland compositor based around creating layouts)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/${GITHUB_REPO}
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr - _)-$ARCH-$BUILD$TAG.txz
