#!/bin/sh

# variables
VERSION=${VERSION:-cvs_$(date +"%Y.%m.%d_%H.%M")}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-1}


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "[0-9\.]*")

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        cd $(dirname $REPOSITORY)
        echo "Press [Enter]"
        cvs -d :pserver:anonymous@cvs.namazu.org:/storage/cvsroot login
        cvs -d :pserver:anonymous@cvs.namazu.org:/storage/cvsroot co $PRGNAM
fi

( cd $REPOSITORY
    cvs update
)

if [ ! -e $REPOSITORY ] ; then
    [ -e $CWD/$PRGNAM-$VERSION.tar.gz ] && rm $CWD/$PRGNAM-$VERSION.tar.gz
    wget -c "http://cvs.namazu.org/emacs-w3m.tar.gz?view=tar" -O $CWD/$PRGNAM-$VERSION.tar.gz
    ( cd $TMP
        tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
        mv $PRGNAM $PRGNAM-$VERSION
    )
else
    cp -R $REPOSITORY $TMP/$PRGNAM-$VERSION
fi
( cd $TMP/$PRGNAM-$VERSION
    zcat $CWD/widget-mouse-face.patch.gz | patch -p1
    autoreconf
    ./configure \
        --prefix=$PREFIX \
        --infodir=$PREFIX/info \
        --mandir=$PREFIX/man
    make
    make install prefix=$PKG$PREFIX
)

# correction
( cd $PKG
    chown -R root:root *
)

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

        |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (a simple Emacs interface to w3m.)
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://emacs-w3m.namazu.org/
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
