#!/bin/sh

# variables

TAG=gwh
TMP=/tmp/$TAG
OUTPUT=/tmp
CWD=$(pwd)
PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

VERSION=$(date +%Y.%m%d_%H.%M)

ARCH='noarch'
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/postmodern/gem_home $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM

# installation
make install PREFIX=$PKG$PREFIX DOC_DIR=$PKG$PREFIX/doc/$PRGNAM
mv $PKG$PREFIX/share/man $PKG$PREFIX/man

# correction
mkdir -p $PKG$PREFIX/bin/
( cd $PKG$PREFIX/bin/
  ln -s ../share/gem_home/gem_home.sh gem_home
  chmod +x gem_home
)

cd $PKG
chown -R root:root *

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A tool for changing your $GEM_HOME)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/postmodern/gem_home
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
