#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO="https://github.com/FreeTubeApp/FreeTube"
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

yarn install

sed -i "s|deb', 'zip', '7z', 'apk', 'rpm', 'AppImage', 'pacman|zip|" _scripts/build.mjs

npm run build

mkdir -p "$PKG/opt/$PKGNAM"
cd "$PKG/opt/$PKGNAM" || exit 1
unzip "$TMP/$PKGNAM/build/freetube*.zip"

[ -x ./FreeTube ] && mv ./FreeTube ./freetube

mkdir -p "$PKG$PREFIX/bin"
cd "$PKG$PREFIX/bin" || exit 1
ln -s "/opt/$PKGNAM/freetube" freetube

cd "$TMP/$PKGNAM/" || exit 1

mkdir -p "$PKG$PREFIX/share/icons/hicolor/scalable/apps/"
cp _icons/icon.svg "$PKG$PREFIX/share/icons/hicolor/scalable/apps/freetube.svg"

mkdir -p "$PKG$PREFIX/share/applications/"
cat <<EOF > "$PKG$PREFIX/share/applications/freetube.desktop"
[Desktop Entry]
Name=FreeTube
Exec=/opt/$PKGNAM/FreeTube %U
Terminal=false
Type=Application
Icon=freetube
StartupWMClass=FreeTube
Comment=A private YouTube client
MimeType=x-scheme-handler/freetube;
Categories=Network;
EOF

mkdir -p "$PKG$PREFIX/doc/$PKGNAM"
cp ./LICENSE ./*.md "$PKG$PREFIX/doc/$PKGNAM/"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

# Packaging
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
freetube: freetube (The Private YouTube Client)
freetube:
freetube: FreeTube is a YouTube client for Windows, Mac, and Linux built around
freetube: using YouTube more privately. You can enjoy your favorite content and
freetube: creators without your habits being tracked.
freetube:
freetube:
freetube:
freetube:
freetube: Homepage: https://freetubeapp.io/
freetube:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
