#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
UPSTREAM_REPO=https://github.com/fossar/selfoss
VERSION=${VERSION:-latest}
ARCH=${ARCH:-noarch}
BUILD=${BUILD:-2}

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM

PREFIX=/usr

# nettoyage préalable
rm -fr $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
( cd $REPOSITORY
  git pull --all
)

mkdir -p $PKG/opt/

cp -R $REPOSITORY $PKG/opt/$PRGNAM
cd $PKG/opt/$PRGNAM
#git checkout dist
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

# installation
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp $PKG/opt/$PRGNAM/COPYING $PKG/opt/$PRGNAM/*.md $PKG$PREFIX/doc/$PRGNAM

COMPOSER_ALLOW_SUPERUSER=1 npm run install-dependencies:server
npm run install-dependencies:client
npm run build

chown -R apache:apache $PKG/opt/$PRGNAM/

# correction
cd $PKG

#find $PKG -name \.git\* -exec rm -fr {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/doinst.sh
#!/bin/bash

grep -q "/opt/selfoss/cliupdate.php" /var/spool/cron/crontabs/apache || echo "*/15  *  *  *  * php -f /opt/selfoss/cliupdate.php" >> /var/spool/cron/crontabs/apache
EOF

cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (multipurpose rss reader, live stream, mashup, aggregation...)
$PRGNAM:
$PRGNAM: selfoss is a multipurpose RSS reader and feed aggregation web application.
$PRGNAM: It allows you to easily follow updates from different web sites, social
$PRGNAM: networks and other platforms, all in single place. It is written in PHP,
$PRGNAM: allowing you to run it basically anywhere.
$PRGNAM:
$PRGNAM:
$PRGNAM: https://selfoss.aditu.de
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
