#!/bin/sh

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG

PRGNAM=$(basename $CWD)
VERSION=2.1.6
ARCH=${ARCH:-$(uname -m)}
BUILD=1

PKG=$TMP/pkg-$PRGNAM

rm -rf $PKG $TMP/$PRGNAM-$VERSION

cd $TMP

[ ! -e $CWD/$PRGNAM-$VERSION.tar.gz ] && wget -c http://www.stolk.org/stormbaancoureur/download/$PRGNAM-$VERSION.tar.gz -O $CWD/$PRGNAM-$VERSION.tar.gz
tar xf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION

chown -R root.root *
find . -perm 777 -exec chmod 755 {} \;

cd src-stormbaancoureur
sed -i 's|$(ODEPREFIX)/$(LIBDIRNAME)/libode.a|-lode|g' Makefile
make LIBDIRNAME=lib$(echo $ARCH | grep -o 64)
make install DESTDIR=$PKG

# Compress the man page(s)
[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

chmod -R o-w $PKG
chown -R root:root $PKG/*

mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

         |-----handy-ruler------------------------------------------------------|
${PRGNAM}: ${PRGNAM} (Simulated Obstacle Course For Automobiles)
${PRGNAM}:
${PRGNAM}: Stormbaan Coureur is the Linux game that was formerly known as
${PRGNAM}: Sturmbahnfahrer. It is back with a larger track, more challenges, many
${PRGNAM}: improvements in a PC (Politically Correct) edition. In this game, it
${PRGNAM}: is all about the car Physics. If you want to master it, try to have
${PRGNAM}: the laws of physics work with you, not against you.
${PRGNAM}: 
${PRGNAM}: 
${PRGNAM}: http://www.stolk.org/stormbaancoureur/
${PRGNAM}: 
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-$(echo ${VERSION} | tr - _)-${ARCH}-${BUILD}$TAG.txz
