#!/bin/bash -e

# variables
VERSION=${VERSION:-latest}

BUILD=3
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

NPROC=$(nproc)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://git.code.sf.net/p/newrpl/sources $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/
[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="$(git rev-list --count master)_git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

# https://www.hpmuseum.org/forum/thread-17667-post-154012.html#pid154012
# elf2rom is only needed to build actual calculator firmware
# bmp2font is only needed to edit or create fonts

# mkdir build-elf2rom
# cd build-elf2rom/
# qmake ../tools/elf2rom//elf2rom.pro
# make -j$NPROC
# cp elf2rom ../tools-bin/

# cd $TMP/$PRGNAM/
# mkdir build-bmp2font
# cd build-bmp2font/
# qmake ../tools/fonts/bmp2font//bmp2font.pro
# make -j$NPROC
# cp bmp2font ../tools-bin/

cd $TMP/$PRGNAM/
mkdir build-comp
cd build-comp/
qmake ../newrpl-comp.pro
make -j$NPROC
cp newrpl-comp ../tools-bin/

cd $TMP/$PRGNAM/
mkdir build-ui
cd build-ui/
qmake ../newrpl-ui.pro
make -j$NPROC

cd $TMP/$PRGNAM/
mkdir build-ui-prime
cd build-ui-prime/
qmake ../newrpl-ui-prime.pro
make -j$NPROC

cd $TMP/$PRGNAM/
mkdir -p $PKG$PREFIX/bin/
cp build-ui/newrpl-ui build-comp/newrpl-comp $PKG$PREFIX/bin/
cp build-ui-prime/newrpl-ui $PKG$PREFIX/bin/newrpl-ui-prime
# cp build-elf2rom/elf2rom $PKG$PREFIX/bin/newrpl-elf2rom
# cp build-bmp2font/bmp2font $PKG$PREFIX/bin/newrpl-bmp2font

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp LICENSE* $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
# find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Programming environment)
$PRGNAM:
$PRGNAM: newRPL is a re-implementation of the HP48/49/50 series calculators
$PRGNAM: programming environment. The RPL scripting language is being
$PRGNAM: redesigned and recreated with even more powerful features.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://hpgcc3.org/projects/newrpl
$PRGNAM: https://newrpl.wiki.hpgcc3.org/doku.php?id=start
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
