#!/bin/sh

# variables
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone https://github.com/buggins/coolreader.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM

# Fix upstream typo
sed -i 's,documetn,document,g' cr3qt/src/*.ui cr3qt/src/i18n/*.ts || exit 1

mkdir -p build
cd build
cmake \
  -D CMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
  -D CMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D LIB_SUFFIX=${LIBDIRSUFFIX} \
  -D CMAKE_BUILD_TYPE=Release \
  -D MAX_IMAGE_SCALE_MUL=2 \
  -D DOC_DATA_COMPRESSION_LEVEL=3 \
  -D DOC_BUFFER_SIZE=0x1400000 \
  -D GUI=QT5 ..
make VERBOSE=1
make install DESTDIR=$PKG
cd ..

strip $PKG/usr/bin/$ORIG_PRGNAM

mkdir -p $PKG/usr/man
mv $PKG/usr/share/man/* $PKG/usr/man
rm -rf $PKG/usr/share/man

sed -i '/Icon/s|\.png||' $PKG/usr/share/applications/$ORIG_PRGNAM.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/usr/share/doc/$ORIG_PRGNAM/* $PKG/usr/doc/$PRGNAM-$VERSION
rm -rf $PKG/usr/share/doc

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

          |-----handy-ruler------------------------------------------------------|
coolreader: coolreader (e-book reader)
coolreader:
coolreader: CoolReader is an e-book reader for various platforms.
coolreader:
coolreader: Supported file formats include plain text, HTML, RTF, Microsoft Word
coolreader: (.doc), Palm Pilot (.prc, .pdb, .pml, .mobi), FB2, and EPUB.
coolreader:
coolreader:
coolreader:
coolreader: https://github.com/buggins/coolreader
coolreader:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
