#!/bin/bash

# variables
VERSION=0.14.1
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=emacs-sokoban
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP

[ ! -e $CWD/$PRGNAM-$VERSION.tar.gz ] && \
	wget -c -O $CWD/$PRGNAM-$VERSION.tar.gz http://www.sha-bang.de/content/15_emacs/emacs-sokoban-$VERSION.tar.gz

mkdir -p $PKG$PREFIX/share/emacs/site-lisp

( cd $PKG$PREFIX/share/emacs/site-lisp/
    tar xf $CWD/$PRGNAM-$VERSION.tar.gz
    cd $PRGNAM-$VERSION
    find . -name "*.el" -exec $EMACS -batch -f batch-byte-compile {} \;
)

# correction
( cd $PKG
    chown -R root:root *
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Sokoban for Emacs)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.emacswiki.org/emacs/SokobanMode
$PRGNAM: 
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
