#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://git.code.sf.net/p/newrpl/sources"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# https://www.hpmuseum.org/forum/thread-17667-post-154012.html#pid154012
# elf2rom is only needed to build actual calculator firmware
# bmp2font is only needed to edit or create fonts

# mkdir build-elf2rom
# cd build-elf2rom/
# qmake ../tools/elf2rom//elf2rom.pro
# make -j"$NPROC"
# cp elf2rom ../tools-bin/

# cd "$TMP/$PRGNAM/" || exit 1
# mkdir build-bmp2font
# cd build-bmp2font/
# qmake ../tools/fonts/bmp2font//bmp2font.pro
# make -j"$NPROC"
# cp bmp2font ../tools-bin/

cd "$TMP/$PRGNAM/" || exit 1
mkdir build-comp
cd build-comp/ || exit 1
qmake ../newrpl-comp.pro
make -j"$NPROC"
cp newrpl-comp ../tools-bin/

cd "$TMP/$PRGNAM/" || exit 1
mkdir build-base
cd build-base/ || exit 1
qmake ../newrpl/newRPL-base.pro
make -j"$NPROC"

cd "$TMP/$PRGNAM/" || exit 1
mkdir build-ui
cd build-ui/ || exit 1
qmake ../newrpl-ui.pro
make -j"$NPROC"

cd "$TMP/$PRGNAM/" || exit 1
mkdir build-ui-prime
cd build-ui-prime/ || exit 1
qmake ../newrpl-ui-prime.pro
make -j"$NPROC"

cd "$TMP/$PRGNAM/" || exit 1
mkdir -p "$PKG$PREFIX"/bin/
cp build-comp/newrpl-comp "$PKG$PREFIX"/bin/

cp build-base/newrpl-base "$PKG$PREFIX"/bin/newrpl-tui
cp build-ui/newrpl-ui "$PKG$PREFIX"/bin/
cp build-ui-prime/newrpl-ui "$PKG$PREFIX"/bin/newrpl-ui-prime

# cp build-elf2rom/elf2rom "$PKG$PREFIX"/bin/newrpl-elf2rom
# cp build-bmp2font/bmp2font "$PKG$PREFIX"/bin/newrpl-bmp2font

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp LICENSE* "$PKG$PREFIX/doc/$PRGNAM"/

# correction
cd "$PKG" || exit 1
chown -R root:root ./*
# find "$PKG$PREFIX"/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG"/install

cat <<EOF > "$PKG"/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Programming environment)
$PRGNAM:
$PRGNAM: newRPL is a re-implementation of the HP48/49/50 series calculators
$PRGNAM: programming environment. The RPL scripting language is being
$PRGNAM: redesigned and recreated with even more powerful features.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://hpgcc3.org/projects/newrpl
$PRGNAM: https://newrpl.wiki.hpgcc3.org/doku.php?id=start
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
