#!/bin/bash

CWD=$(pwd)

# default settings
PRGNAM=$(basename $CWD)
ARCH=$(uname -m)
VERSION=svn$(date +%F | sed 's/-//g')
BUILD=1


TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories
GZBZ2="bz2"

DOCS="ABOUT-NLS AUTHORS BUGS COPYING ChangeLog INSTALL NEWS README TODO"

rm -rf $PKG $TMP/$PRGNAM-$VERSION
mkdir -p $PKG
cd $TMP

if [ -e $CWD/PRGNAM-$VERSION.tar.$GZBZ2 ] ; then
      tar xvf $CWD/PRGNAM-$VERSION.tar.$GZBZ2
else
    if [ ! -e $REPOSITORIES/$PRGNAM ] ; then
        git clone http://git.naquadah.org/git/oopango.git $REPOSITORIES/$PRGNAM
    else
        ( cd $REPOSITORIES/$PRGNAM
            git pull
        )
    fi
    cp -R $REPOSITORIES/$PRGNAM $PRGNAM-$VERSION
fi
cd $PRGNAM-$VERSION

./autogen.sh
LIBS=-lX11 ./configure \
  --libdir=/usr/lib$( [ $ARCH = "x86_64" ] && echo 64 ) \
	--mandir=/usr/man \
    --prefix=/usr

make
make install DESTDIR=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM/
cp $DOCS $PKG/usr/doc/$PRGNAM/

cd $PKG

find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

mkdir -p install
cat << EOF > install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

        |-----handy-ruler-----------------------------------------------------|
$PRGNAM: $PRGNAM (Lua - pango binding)
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://git.naquadah.org/?p=oopango.git;a=summary
$PRGNAM:
EOF

chown -R root:root $PKG

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
