#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep tag_name | grep -o "[0-9.]*")}
ARCH=$(uname -m)
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

mkdir -p "$REPOSITORY"

[ ! -e "$REPOSITORY/${PRGNAM}-${VERSION}-${ARCH}.txz" ] && wget -c -O "$REPOSITORY/${PRGNAM}-${VERSION}-${ARCH}.txz" "https://github.com/jgm/pandoc/releases/download/$VERSION/pandoc-$VERSION-linux-amd64.tar.gz"

rm -fr "$PKG"
mkdir -p "$PKG"

cd "$PKG" || exit 1
tar xvf "$REPOSITORY/${PRGNAM}-${VERSION}-${ARCH}.txz"

mv "pandoc-${VERSION}" usr
mv usr/share/man usr/
rm -r usr/share

mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

         |-----handy-ruler------------------------------------------------------|
${PRGNAM}: ${PRGNAM} ( Universal markup converter )
${PRGNAM}:
${PRGNAM}: Pandoc is a Haskell library for converting from one markup format to
${PRGNAM}: another, and a command-line tool that uses this library.
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}: https://pandoc.org
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
