#!/bin/bash

# variables
TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone --quiet https://git.weboob.org/weboob/weboob.git $REPOSITORY
cd $REPOSITORY
git pull --quiet --all

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
VERSION="$(git rev-list --count HEAD)_$(git log -1 --format=%h)"

# installation
./tools/local_install.sh $PKG$PREFIX/bin

# avoid overwriting existing binaries
( cd $PKG$PREFIX/bin
  for b in *; do
      [ -e $PREFIX/bin/$b ] && mv $b ${PRGNAM}_$b
  done
)

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R AUTHORS CONTRIBUTING.md COPYING COPYING.LESSER ChangeLog INSTALL README.md $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Web Outside Of Browsers)
$PRGNAM:
$PRGNAM: Weboob is a collection of applications able to interact with websites,
$PRGNAM: without requiring the user to open them in a browser. It also provides
$PRGNAM: well-defined APIs to talk to websites lacking one.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://weboob.org/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
