#!/bin/sh

# variables
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=cyco
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=noarch

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/dgud/wings.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG/opt/

cp -R $REPOSITORY $PKG/opt/
cd $PKG/opt/$PRGNAM

ERL_LIBS=$PKG/opt/ make

mkdir -p $PKG$PREFIX/bin
cat<<EOF > $PKG$PREFIX/bin/$PRGNAM
#!/bin/sh
erl -pa /opt/$PRGNAM/ebin -run wings_start start_halt
EOF
chmod 0755 $PKG$PREFIX/bin/$PRGNAM

mkdir -p $PKG$PREFIX/doc/$PRGNAM
mv AUTHORS BUILD.unix BUILD.win32 CodingGuidelines OLD-NOTES README README-22.txt README.jp $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A polygon modeler)
$PRGNAM:
$PRGNAM: Wings 3D is an advanced subdivision modeler that is both powerful and
$PRGNAM: easy to use.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://www.wings3d.com/
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
