#!/bin/bash

CWD=$(pwd)
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PRGNAM=$(basename $CWD)
ARCH=${ARCH:-$(uname -m | grep -q 64 && echo "x86_64" || echo "i386")}
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/elm/compiler/releases/latest | grep tag_name | grep -o "[0-9.]*")}
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

rm -rf $PKG
mkdir -p $PKG/usr/bin $OUTPUT
cd $PKG/usr/bin/

[ ! -e $CWD/$PRGNAM.tar.gz ] && wget -c https://github.com/elm/compiler/releases/download/${VERSION}/binaries-for-linux.tar.gz -O $CWD/$PRGNAM.tar.gz
tar xvf $CWD/$PRGNAM.tar.gz

# Make sure top-level perms are correct:
chmod 0755 $PKG/usr/bin/$PRGNAM

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler----------------------------------------------------|
$PRGNAM: $PRGNAM (A delightful language for reliable webapps.)
$PRGNAM:
$PRGNAM: Generate JavaScript with great performance and no runtime
$PRGNAM: exceptions.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: Homepage: https://elm-lang.org/
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
