#!/bin/sh

# variables
VERSION=2.2.1
BUILD=1


TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP

[ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && wget -c ftp://ftp.tuxpaint.org/unix/www/cgi-util/$PRGNAM-$VERSION.tar.gz -O $CWD/$PRGNAM-$VERSION.tar.gz
tar xf $CWD/$PRGNAM-$VERSION.tar.gz

( cd $TMP/$PRGNAM-$VERSION
    make LIBDIR=$PREFIX/lib$(echo "${ARCH}" | grep -o 64) INCDIR=$PREFIX/include

    mkdir -p $PKG$PREFIX/lib$(echo "${ARCH}" | grep -o 64) $PKG$PREFIX/include
    make install LIBDIR=$PKG$PREFIX/lib$(echo "${ARCH}" | grep -o 64) INCDIR=$PKG$PREFIX/include
)

# correction
( cd $PKG
    chown -R root:root *
    find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (CGI C library)
$PRGNAM:
$PRGNAM: cgi-util is a powerful, small C library that allows you to create
$PRGNAM: CGI ("Common Gateway Interface") programs for websites.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.newbreedsoftware.com/cgi-util/
$PRGNAM: 
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
