#!/bin/bash

# variables
UPSTREAM_REPO=https://codeberg.org/river/river
VERSION=${VERSION:-latest}

BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
[ ! -e "$REPOSITORY" ] && git clone --quiet ${UPSTREAM_REPO}.git --recursive "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet

cp -R "$REPOSITORY" $TMP/
cd "${TMP:?}/$PRGNAM" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"

zig build \
    -Dxwayland \
    -Doptimize=ReleaseSafe \
    --prefix "$PKG$PREFIX" \
    install

mv "$PKG$PREFIX/share/man" "$PKG$PREFIX/"

cat <<EOF > "$PKG$PREFIX/bin/start_river.sh"
#!/bin/bash

#set -e

# LOGFILE=~/.wsession-errors
# true > \$LOGFILE
# exec &> \$LOGFILE

set -x
echo "river Starting: \$( date )"

# Uncomment if mouse pointer is invisible
#export WLR_NO_HARDWARE_CURSORS=1

unset QT_QPA_PLATFORM


# vulklan seems buggy with Intel IGP
if \$(lsmod | grep -q "^i915.*$"); then
   export WLR_RENDERER=gles2
else
   export WLR_RENDERER=vulkan
fi

export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export XDG_SESSION_DESKTOP=river
export XDG_SESSION_TYPE=wayland
export QT_PLATFORMTHEME=qt5ct
export QT_PLATFORM_PLUGIN=qt5ct

export QT_QPA_PLATFORMTHEME=qt5ct
export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=river
export XDG_PICTURES_DIR=~/.wallpapers

export XDG_RUNTIME_DIR=/tmp/xdg-runtime-\$(id -u)

mkdir -p \$XDG_RUNTIME_DIR
chmod 0700 \$XDG_RUNTIME_DIR

# avoid wlr error
unset DISPLAY

killall daemon

exec dbus-run-session $PREFIX/bin/river
EOF
chmod +x "$PKG$PREFIX/bin/start_river.sh"

mkdir -p "$PKG/usr/share/wayland-sessions/"
cat <<EOF > "$PKG/usr/share/wayland-sessions/river.desktop"
[Desktop Entry]
Name=River
Comment=a modern wayland compositor
Exec=/usr/bin/start_river.sh
Type=Application
EOF

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -a docs/ example/ contrib/ AUTHORS LICENSE ./*.md "$PKG$PREFIX/doc/$PRGNAM/"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*
[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A dynamic tiling wayland compositor)
$PRGNAM:
$PRGNAM: River is a dynamic tiling wayland compositor with flexible runtime
$PRGNAM: configuration.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
