#!/bin/sh -x

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=2


TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        cd $(dirname $REPOSITORY)
        hg clone http://bitbucket.org/zck/minesweeper.el $PRGNAM
fi

( cd $REPOSITORY
    hg pull -u
)

mkdir -p $PKG$PREFIX/share/emacs/site-lisp
cp -R $REPOSITORY $PKG$PREFIX/share/emacs/site-lisp
( cd $PKG$PREFIX/share/emacs/site-lisp/$PRGNAM
    rm -fr .hg
    $EMACS -batch -f batch-byte-compile *.el
)

# correction
( cd $PKG
    chown -R root:root *
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Mineswipper game for Emacs)
$PRGNAM: 
$PRGNAM: A minesweeper implementation for Emacs.
$PRGNAM: To start a game, run M-x minesweeper . Reveal a square by pressing
$PRGNAM: the spacebar, enter, or the x key.
$PRGNAM: 
$PRGNAM:
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://bitbucket.org/zck/minesweeper.el
$PRGNAM: 
EOF

# empaquetage
cd $PKG
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
