#!/bin/sh

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://git.sr.ht/~kennylevinsen/seatd $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/
meson build/
meson configure --prefix /usr --mandir /usr/man/ build/
ninja -C build/
cd build/
meson install --destdir=$PKG
cd ../

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp LICENSE README.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Seat management daemon and library)
$PRGNAM:
$PRGNAM: seatd and libseat
$PRGNAM: A minimal seat management daemon, and a universal seat management
$PRGNAM: library.
$PRGNAM: - What is seat management?
$PRGNAM:   Seat management takes care of mediating access to shared devices
$PRGNAM:   (graphics, input), without requiring the applications needing
$PRGNAM:   access to be root.
$PRGNAM:
$PRGNAM: https://git.sr.ht/~kennylevinsen/seatd
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
