#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH="noarch" 	# hardcode ARCH
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

DOCROOT=${DOCROOT:-/var/www/htdocs}

PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -eu

rm -rf $PKG
mkdir -p $TMP $OUTPUT $PKG/$DOCROOT
cd $PKG/$DOCROOT/
rm -rf $PRGNAM-$VERSION

REPOSITORY=/home/installs/SlackBuilds/repository/$PRGNAM

if [ -e $REPOSITORY ]; then
    (cd $REPOSITORY; git pull)
else
    git clone https://github.com/sebsauvage/Shaarli.git $REPOSITORY
fi

cp -R $REPOSITORY $PRGNAM

cd $PRGNAM
rm -fr .git .gitignore
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 -o -perm 755 \) \
 -exec chmod 750 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 -o -perm 644 \) \
 -exec chmod 640 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a README.md COPYING $PKG/usr/doc/$PRGNAM

# Change ownership and perms and create a link.
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/$PRGNAM
chmod 0750 $PKG/$DOCROOT/$PRGNAM

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (The personal, minimalist, super-fast, no-database delicious clone.)
$PRGNAM:
$PRGNAM: You want to share the links you discover ? Shaarli is a minimalist delicious
$PRGNAM: clone you can install on your own website. It is designed to be personal
$PRGNAM: (single-user), fast and handy.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM:
$PRGNAM: http://blog.slucas.fr/en/oss/calibre-opds-php-server
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
