#!/bin/sh

# variables
CWD=$(pwd)

VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
BUILD=${BUILD:-1}

TAG=gwh
TMP=${TMP:-/tmp/$TAG}
OUTPUT=${OUTPUT:-/tmp}

PRGNAM=${PRGNAM:-$(basename $CWD)}
PKG=${PKG:-$TMP/pkg-$PRGNAM}

ARCH=${ARCH:-noarch}

PREFIX=${PREFIX:-/usr}

REPOSITORY=${REPOSITORY:=/home/installs/SlackBuilds/repositories/$PRGNAM}

# nettoyage préalable
rm -fr $PKG

mkdir -p $PKG$PREFIX/doc/

# mise en place
[ ! -e $REPOSITORY ] && git clone http://github.com/twcamper/sicp-kindle $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORY $PKG$PREFIX/doc/$PRGNAM
rm -fr $PKG$PREFIX/doc/$PRGNAM/.git*

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

        |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (computer-science text)
$PRGNAM:
$PRGNAM: Wizard Book n. Hal Abelson's, Jerry Sussman's and Julie Sussman's
$PRGNAM: Structure and Interpretation of Computer Programs (MIT Press, 1984;
$PRGNAM: ISBN 0-262-01077-1), an excellent computer science text used in
$PRGNAM: introductory courses at MIT. So called because of the wizard on the
$PRGNAM: jacket. One of the bibles of the LISP/Scheme world. Also,
$PRGNAM: less commonly, known as the Purple Book.
$PRGNAM: http://mitpress.mit.edu/sicp/
$PRGNAM: http://groups.csail.mit.edu/mac/classes/6.001/abelson-sussman-lectures/
$PRGNAM: http://github.com/twcamper/sicp-kindle
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
