#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
                          # remove old log files

FONTDIR="/usr/share/fonts/TTF"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR $PKG/usr/doc/$PRGNAM
( cd $PKG$FONTDIR/
    [ ! -e $CWD/$PRGNAM-$VERSION.zip ] && \
        wget -c "http://input.fontbureau.com/build/?fontSelection=whole&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=straight&preset=default&line-height=1.2&accept=I+do" -O $CWD/$PRGNAM-$VERSION.zip
    unzip $CWD/$PRGNAM-$VERSION.zip
    find . -type f -name \*.ttf -exec mv {} . \;
    find . -type f -not -name \*.ttf -exec mv {} $PKG/usr/doc/$PRGNAM \;
    find . -type d -exec rm -fr {} \;
)

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Coding font)
$PRGNAM: 
$PRGNAM: For private use
$PRGNAM: Input is available free of charge for private/unpublished usage.
$PRGNAM: This includes things like your personal coding app or for composing
$PRGNAM: plain text documents.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://input.fontbureau.com/
$PRGNAM: 
EOF

# Build the package:
cd $PKG
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.tgz 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
cd $OUTPUT
md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.tgz > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.tgz.md5
cd -
cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt

