#!/bin/bash

# variables
TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

VERSION=${VERSION:-"trunk"}

DOCS="LICENSE README.rst AUTHORS.rst"

ARCH=$(uname -m)
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
GIT_URL="https://github.com/jkbr/httpie.git"
[ ! -e $REPOSITORY ] && git clone "$GIT_URL" $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

# installation
python3 ./setup.py install --root=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R $DOCS $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (a CLI, cURL-like tool for humans.)
$PRGNAM:
$PRGNAM: HTTPie is a command line HTTP client. Its goal is to make CLI interaction
$PRGNAM: with web services as human-friendly as possible. It provides a simple http
$PRGNAM: command that allows for sending arbitrary HTTP requests using a simple and
$PRGNAM: natural syntax, and displays colorized responses. HTTPie can be used for
$PRGNAM: testing, debugging, and generally interacting with HTTP servers.
$PRGNAM:
$PRGNAM:
$PRGNAM: http://httpie.org/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
