#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H.%M")}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

SLCKFLAGS=" -O "

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ]; then
    svn checkout http://pwauth.googlecode.com/svn/trunk/pwauth $REPOSITORY
else
    ( cd $REPOSITORY
      svn update
    )
fi
cp -R $REPOSITORY $TMP/$PRGNAM

cd $TMP/$PRGNAM

# installation
make
mkdir -p $PKG$PREFIX/sbin/
mv pwauth unixgroup $PKG$PREFIX/sbin/

# correction
cd $PKG
chown -R root:root *

find $PKG -name \.git\* -exec rm -fr {} \;

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)


# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A Unix Authentication Tool)
$PRGNAM:
$PRGNAM: Pwauth is an authenticator designed to be used with mod_auth_external
$PRGNAM: or mod_authnz_external and the Apache HTTP daemon to support reasonably
$PRGNAM: secure web authentication out of the system password database on most
$PRGNAM: versions of Unix.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://code.google.com/p/pwauth/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
