#!/bin/bash
set -x

PRGNAM=x48

BUILD=1
GITHUB_REPO=gwenhael-le-moine/x48
VERSION=${VERSION:-latest}

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr $PRGNAM $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/$PRGNAM

# Preparation
cd $TMP/$PRGNAM

[ "x$VERSION" == "xlatest" ] && VERSION=$(git for-each-ref --sort=taggerdate --format '%(tag)' | tail -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Configuration
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o "64") \
    --sysconfdir=/etc

# Building
make

# Installation
make install DESTDIR=$PKG

mkdir -p $PKG$PREFIX/share/$PRGNAM
cd $PKG$PREFIX/share/$PRGNAM
cp $TMP/$PRGNAM/ROMs/*rom*.bz2 .
find . -name "*.bz2" -exec bunzip2 {} \;

# # Cleaning
# cd $PKG
# find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
# find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

cd $PKG

[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (HP48 emulator)
$PRGNAM:
$PRGNAM: The x48 is an emulator of the Saturn Processor and the I/O of an
$PRGNAM: HP48 calculator. There is a debugger for the Saturn Processor.
$PRGNAM:
$PRGNAM: initialization:
$PRGNAM: $ mkdir ~/.hp48 && cp $PREFIX/share/$PRGNAM/gxrom-r ~/.hp48/rom.dump
$PRGNAM: $ cd ~/.hp48 && x48 -initialize
$PRGNAM:
$PRGNAM: http://x48.berlios.de/
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
