#!/bin/bash
set -x

PRGNAM=$(basename $(pwd))
UPSTREAM_REPO=https://github.com/sagb/alttab
VERSION=${VERSION:-latest}

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr $PRGNAM $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --quiet --all

cp -R $REPOSITORY $TMP/$PRGNAM

# Preparation
cd $TMP/$PRGNAM
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout --quiet $VERSION

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Configuration
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --mandir=$PREFIX/man \
    --docdir=$PREFIX/doc/$PRGNAM \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o "64") \
    --sysconfdir=/etc

# Building
make

# Installation
make install DESTDIR=$PKG

# Cleaning
cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Task switcher for minimalistic window managers or standalone X11 session)
$PRGNAM:
$PRGNAM: Unlike task switchers integrated in most simple window managers (WM) or dmenu-like
$PRGNAM: switchers, alttab features visual interface and convenient tactile behaviour:
$PRGNAM: press modifier (Alt) - multiple switch with a key (Tab) - release modifier. Also,
$PRGNAM: it's lightweight and depends only on basic X11 libs, conforming to the usage of
$PRGNAM: lightweight WM.alttab is X11 window switcher designed for minimalistic window
$PRGNAM: managers or standalone X11 session.
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
