#!/bin/sh

# variables
VERSION=trunk_$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    mkdir -p $(dirname $REPOSITORY)
    svn checkout http://pyglet.googlecode.com/svn/trunk/ $REPOSITORY
fi

( cd $REPOSITORY
    svn update
)

cp -R $REPOSITORY $TMP/
( cd $TMP/$PRGNAM
    python ./setup.py install --root $PKG
)

# correction
( cd $PKG
    chown -R root:root *
    find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (a cross-platform windowing and multimedia library for Python.)
$PRGNAM:
$PRGNAM: pyglet provides an object-oriented programming interface for developing
$PRGNAM: games and other visually-rich applications for Windows, Mac OS X and
$PRGNAM: Linux.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.pyglet.org
$PRGNAM: 
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
