#!/bin/sh

# Slackware build script for google-musicmanager

# Modified by Gwenhael Le Moine <gwenhael.le.moine@gmail.com>
# Written by Steven Pledger <spledger91@yahoo.com>
# Based on google-chrome.SlackBuild from Slackware

# Copyright 2009-2010  Erik Hanson, Minneapolis, MN, USA
# Copyright 2011  Patrick J. Volkerding, Sebeka, MN, USA
# Copyright 2011 Steven Pledger, Vacaville, CA, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=google-musicmanager
RELEASE=${RELEASE:-beta}    # stable, beta, or unstable

CWD=$(pwd)
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

case "$(uname -m)" in
  i?86) DEBARCH="i386" ; LIBDIRSUFFIX="" ; ARCH=i386 ;;
  x86_64) DEBARCH="amd64" ; LIBDIRSUFFIX="64" ; ARCH=x86_64 ;;
  *) echo "Package for $(uname -m) architecture is not available." ; exit 1 ;;
esac

[ ! -e $CWD/$PRGNAM-${RELEASE}_current_${DEBARCH}.deb ] && wget -c http://dl.google.com/linux/direct/$PRGNAM-${RELEASE}_current_${DEBARCH}.deb -O $CWD/$PRGNAM-${RELEASE}_current_${DEBARCH}.deb

VERSION=$(ar p $CWD/$PRGNAM-${RELEASE}_current_${DEBARCH}.deb control.tar.gz 2> /dev/null | tar zxO ./control 2> /dev/null | grep Version | awk '{print $2}' | cut -d- -f1)

BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $PKG
ar p $CWD/$PRGNAM-${RELEASE}_current_${DEBARCH}.deb data.tar.lzma | lzma -d | tar xv
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Make sure top-level perms are correct:
chmod 0755 .

# The cron job is for Debian/Ubuntu only:
rm -rf etc

# Nothing in here
rm -rf usr/share/man

# Install a .desktop launcher:
sed -i -e "s#Icon=google-musicmanager#Icon=/opt/google/musicmanager/product_logo_128.png#" \
  $PKG/opt/google/musicmanager/google-musicmanager.desktop
mkdir -p $PKG/usr/share/applications
ln -s /opt/google/musicmanager/google-musicmanager.desktop \
  $PKG/usr/share/applications/google-musicmanager.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/SlackBuild

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

                   |-----handy-ruler------------------------------------------------------|
google-musicmanager: google-musicmanager (Music uploader for Google Music)
google-musicmanager:
google-musicmanager: Google MusicManager is a simple application for adding music files
google-musicmanager: to your Google Music library.
google-musicmanager:
google-musicmanager: Homepage: http://music.google.com/
google-musicmanager:
google-musicmanager:
google-musicmanager:
google-musicmanager:
google-musicmanager:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD${TAG}.${PKGTYPE:-txz}
