#!/bin/bash

# variables
CWD=$(pwd)
UPSTREAM_REPO=https://github.com/winterheart/broadcom-bt-firmware
VERSION=${VERSION:-trunk}
BUILD=${BUILD:-1}

TAG=gwh
TMP=${TMP:-/tmp/$TAG}
OUTPUT=${OUTPUT:-/tmp}

PRGNAM=${PRGNAM:-$(basename $CWD)}
PKG=${PKG:-$TMP/pkg-$PRGNAM}

ARCH=${ARCH:-noarch}

PREFIX=${PREFIX:-/usr}

REPOSITORY=${REPOSITORY:=/var/cache/SlackBuilds.gwh/$PRGNAM}

# nettoyage préalable
rm -fr $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
( cd $REPOSITORY; git pull )
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

mkdir -p $PKG/lib/firmware/
cp -R $REPOSITORY/brcm/ $PKG/lib/firmware/

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R $REPOSITORY/{DEVICES.md,LICENSE.*,README.md} $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

        |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (various Broadcom Bluetooth firmware)
$PRGNAM:
$PRGNAM: This package intentended to provide firmware of Broadcom WIDCOMM®
$PRGNAM: Bluetooth devices (including BCM20702, BCM20703, BCM43142 chipsets
$PRGNAM: and other) for Linux kernel.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
