#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)
GITHUB_REPO=gwenhael-le-moine/x49gp
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/${GITHUB_REPO}/releases/latest | jq -r .tag_name | sed 's|^null$|trunk|')} # or VERSION=trunk

BUILD=2

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr $TMP/$PRGNAM $PKG

# Fetching sources
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

# Preparation
chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Building
make INSTALL_PREFIX=/usr INSTALL_MAN_DIR=/usr/man/man1
make sdcard INSTALL_PREFIX=/usr INSTALL_MAN_DIR=/usr/man/man1

# Installing
mkdir -p $PKG
make install DESTDIR=$PKG INSTALL_PREFIX=/usr INSTALL_MAN_DIR=/usr/man/man1

mkdir -p $PKG$PREFIX/share/$PRGNAM
[ ! -e $CWD/hp4950v215.zip ] && wget -c -O $CWD/hp4950v215.zip https://www.hpcalc.org/hp49/pc/rom/hp4950v215.zip
unzip -d $PKG$PREFIX/share/$PRGNAM/ $CWD/hp4950v215.zip

mkdir -p $PKG$PREFIX/share/$PRGNAM/newrpl/
wget -c -O $PKG$PREFIX/share/$PRGNAM/newrpl/newrplfw.bin https://hpgcc3.org/downloads/newrplfw.bin
echo "newrplfw.bin" > $PKG$PREFIX/share/$PRGNAM/newrpl/update.scp

mkdir -p $PKG$PREFIX/doc/$PRGNAM/
cp README* sdcard $PKG$PREFIX/doc/$PRGNAM/

mkdir -p $PKG$PREFIX/doc/$PRGNAM/HP_50g_Advanced_User-s_Reference_Manual_Edition_2
[ ! -e $CWD/hp50gaur.zip ] && wget -c -O $CWD/hp50gaur.zip https://www.hpcalc.org/hp49/docs/misc/hp50gaur.zip
unzip -d $PKG$PREFIX/doc/$PRGNAM/HP_50g_Advanced_User-s_Reference_Manual_Edition_2/ $CWD/hp50gaur.zip

mkdir -p $PKG$PREFIX/doc/$PRGNAM/HP_50g_User-s_Guide
[ ! -e $CWD/hp50gug.zip ] && wget -c -O $CWD/hp50gug.zip https://www.hpcalc.org/hp49/docs/misc/hp50gug.zip
unzip -d $PKG$PREFIX/doc/$PRGNAM/HP_50g_User-s_Guide/ $CWD/hp50gug.zip

# Cleaning
cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/doinst.sh
#!/bin/bash

cat /usr/doc/x49gp/README.md | grep "First launch setup" --before-context=2 --after-context=28

echo "Prepared folders are installed in $PREFIX/share/$PRGNAM/hp4950v215"
EOF
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (HP49/50 emulator)
$PRGNAM:
$PRGNAM: Emulator of the newer Hewlett Packard Handheld Calculator Models with ARM CPU
$PRGNAM: (HP49g+ HP50).
$PRGNAM:
$PRGNAM:
$PRGNAM: Post-installation setup:
$PRGNAM: $ x49gp-bootstrap-config
$PRGNAM:
$PRGNAM: https://sourceforge.net/projects/x49gp/
$PRGNAM: https://github.com/${GITHUB_REPO}
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
