#!/bin/bash

# variables
VERSION=${VERSION:-latest}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr "$PKG $TMP/$PRGNAM"

mkdir -p "$PKG"

# mise en place
cd "$TMP" || exit 1
[ ! -e "$REPOSITORY" ] && git clone https://github.com/haampie/libtree.git "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all

cp -R "$REPOSITORY" "$TMP"/
cd "$TMP/$PRGNAM" || exit 1
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" #|| git checkout $VERSION

make
make install DESTDIR="$PKG" PREFIX=/usr
mv "$PKG$PREFIX"/share/man "$PKG$PREFIX/"
rm -fr "$PKG$PREFIX/share/"

# move doc/ to the appropriate location
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp LICENSE ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (ldd in a tree)
$PRGNAM:
$PRGNAM: A tool that:
$PRGNAM:     🌳 turns ldd into a tree
$PRGNAM:     ☝️ explains how shared libraries are found or why they cannot
$PRGNAM:        be located
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/haampie/libtree
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
