#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=trunk$(date +%Y.%m.%d_%H.%M)
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
( cd $REPOSITORIES
    if [ -e $REPOSITORIES/$PRGNAM ] ; then
        ( cd $REPOSITORIES/$PRGNAM
            svn up
        )
    else
        svn co http://core.svn.wordpress.org/trunk/ $REPOSITORIES/$PRGNAM
    fi
)

mkdir -p $PKG/srv/www/htdocs
cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
find $PKG/srv/www/htdocs -name \.svn\* -exec rm -fr {} \;

( cd $PKG
    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Blog/CMs engine)
$PRGNAM: 
$PRGNAM: WordPress is web software you can use to create a beautiful website or blog.
$PRGNAM: We like to say that WordPress is both free and priceless at the same time.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://wordpress.org/
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
