#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=noarch

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories/
PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
if [ ! -e $REPOSITORIES/$PRGNAM ]; then
    mkdir -p $REPOSITORIES/$PRGNAM
    ( cd $REPOSITORIES/$PRGNAM
        httrack http://www.pitt.edu/~jdnorton/teaching/HPS_0410/chapters/index.html
    )
else
    ( cd $REPOSITORIES/$PRGNAM
        httrack --update
    )
fi

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORIES/$PRGNAM $PKG$PREFIX/doc/$PRGNAM

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM («Einstein for everyone» book)
$PRGNAM: 
$PRGNAM: Einstein for Everyone
$PRGNAM:    JOHN D.  NORTON
$PRGNAM:    Nullarbor Press
$PRGNAM:         2007
$PRGNAM: revisions  2008, 2010
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.pitt.edu/~jdnorton/teaching/HPS_0410/chapters/index.html
$PRGNAM: 
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
