#!/bin/sh
set -x

CWD=$(pwd)

PKGNAM=$(basename $CWD)
VERSION=${VERSION:-b}

BUILD=${BUILD:-1}

ARCH=noarch

TAG=gwh
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PKGNAM
OUTPUT=${OUTPUT:-/tmp}

# Cleaning
rm -fr $TMP/$PKGNAM-$VERSION
rm -fr $PKG

mkdir -p $PKG/

# $CWD/config is pre-configured alread (permissions and all)
cp -a $CWD/config/etc $PKG/

# Activate some non-default fonts adjustements
(cd $PKG/etc/fonts/conf.d
	ln -s ../conf.avail/35-gwh.conf
	ln -s ../conf.avail/10-sub-pixel-rgb.conf
	ln -s ../conf.avail/10-autohint.conf
)

cd $PKG
# Cleaning
chown -R root:root .

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PKGNAM: $PKGNAM (Cycojesus' post-install configuration)
$PKGNAM:
$PKGNAM: 
$PKGNAM: 
$PKGNAM: 
$PKGNAM: 
$PKGNAM:
$PKGNAM: 
$PKGNAM: 
$PKGNAM: 
$PKGNAM: 
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PKGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
