#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
UPSTREAM_REPO=https://github.com/janet-lang/janet
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

SLCKFLAGS=" -O "

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --quiet --all

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "develop" ] && git checkout --quiet develop && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout --quiet $VERSION

# sed -i 's|git@github.com:|https://github.com/|g' $(grep -l git@ .*)

# installation
make install DESTDIR=$PKG PREFIX=$PREFIX LIBDIR=$PREFIX/lib$(uname -m | grep -o 64) JANET_MANPATH=$PREFIX/man/man1

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R test/ doc/ *.md LICENSE $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root ./*

find $PKG -name \.git\* -exec rm -fr {} \;

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# # Strip binaries
# cd $PKG
# find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
# find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM ( A dynamic language and bytecode vm )
$PRGNAM:
$PRGNAM: Janet is a programming language for system scripting,
$PRGNAM: expressive automation, and extending programs written
$PRGNAM: in C or C++ with user scripting capabilities.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
