#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-20111129}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
rm -rf $PKG
mkdir -p $OUTPUT
mkdir -p $PKG

FONTDIR=/usr/share/fonts/TTF

# Move the fonts into place:
mkdir -p $PKG$FONTDIR $PKG/usr/doc/
cd $PKG$FONTDIR/
[ ! -e $CWD/Roboto_Hinted_$VERSION.zip ] && wget -c https://dl-ssl.google.com/android/design/Roboto_Hinted_$VERSION.zip -O $CWD/Roboto_Hinted_$VERSION.zip
unzip $CWD/Roboto_Hinted_$VERSION.zip
mv Roboto_Hinted_$VERSION/*.ttf .
mv Roboto_Hinted_$VERSION $PKG/usr/doc/$PRGNAM

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Roboto font, from Android)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: https://developer.android.com/design/style/typography.html
$PRGNAM: 
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
