#!/bin/bash

set -e

# variables
VERSION=${VERSION:-"trunk"}
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM
PREFIX=/usr

DARCS=/root/.local/bin/darcs

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && $DARCS clone --lazy https://hub.darcs.net/raichoo/hikari $REPOSITORY
cd $REPOSITORY
$DARCS pull

VERSION="darcs_$($DARCS log --last=1 | head -n1 | cut -d\  -f2)"

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/
bmake WITH_ALL=YES PREFIX=/usr ETC_PREFIX=
bmake install DESTDIR=$PKG PREFIX=/usr ETC_PREFIX=

mv $PKG/usr/share/man/ $PKG/usr

cat <<EOF > $PKG$PREFIX/bin/start_hikari.sh
#!/bin/bash

export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SAL_USE_VCLPLUGIN=gtk3

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export GDK_BACKEND=wayland
export CLUTTER_BACKEND=gdk

export SDL_VIDEODRIVER=wayland

export XDG_CURRENT_DESKTOP=hikari

[ -e $HOME/.profile ] && . $HOME/.profile

exec hikari
EOF
chmod +x $PKG$PREFIX/bin/start_hikari.sh

sed -i 's|Exec=hikari|Exec=/usr/bin/start_hikari.sh|' $PKG$PREFIX/share/wayland-sessions/hikari.desktop

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp LICENSE *.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Wayland compositor)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://hikari.acmelabs.space/
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
