#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=2

TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=emacs-chess
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        cd $(dirname $REPOSITORY)
        git clone "https://github.com/jwiegley/emacs-chess.git" $PRGNAM
else
	( cd $REPOSITORY
		git pull
	)
fi

cp -R $REPOSITORY $TMP
cd $TMP/$PRGNAM
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --infodir=$PREFIX/info
make
make install DESTDIR=$PKG
rm $PKG$PREFIX/info/dir
find $PKG$PREFIX/info/ -type f -name \*.info -exec gzip -9 {} \;

VERSION=$(grep version $PKG$PREFIX/share/emacs/site-lisp/_pkg.el | grep -o '[0-9.]*')_$VERSION

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/doinst.sh
cd /usr/info
for file in \$(ls *.gz | grep -v ".*\-[0-9]\+\.gz")
do
    install-info \$file ./dir
done
EOF

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A complete chess client written in Emacs Lisp.)
$PRGNAM: 
$PRGNAM: a client and library for playing Chess from Emacs.
$PRGNAM: chess.el is an Emacs Lisp library and several clients on top of the
$PRGNAM: underlying library functionality for performing various activities
$PRGNAM: related to the game of chess.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://github.com/jwiegley/emacs-chess
$PRGNAM: 
EOF

# empaquetage
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
