#!/bin/sh

CWD=$(pwd)

PRGNAM=jquery
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
( cd $REPOSITORIES
    if [ -e $REPOSITORIES/$PRGNAM ] ; then
        ( cd $REPOSITORIES/$PRGNAM
            git pull
        )
    else
        git clone http://github.com/$PRGNAM/$PRGNAM.git $REPOSITORIES/$PRGNAM
    fi
)

# mkdir -p $PKG/srv/www/htdocs
# cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
# find $PKG/srv/www/htdocs -name \.git\* -exec rm -fr {} \;
mkdir -p $TMP
cp -R $REPOSITORIES/$PRGNAM $TMP
( cd $TMP/$PRGNAM
    make PREFIX=$PKG/srv/www/htdocs
    mkdir -p $PKG$PREFIX/doc/$PRGNAM
    cp -R *-LICENSE.txt README.md version.txt test speed $PKG$PREFIX/doc/$PRGNAM
)

VERSION=$(cat $PKG$PREFIX/doc/$PRGNAM/version.txt)_$VERSION

( cd $PKG
    # Amis, nettoyons un tantinet la zone
    find $PKG -name \.git\* -exec rm -fr {} \;

    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (New Wave Javascript)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://jquery.com/
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
