#!/bin/bash

# variables
TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

VERSION=${VERSION:-latest}

DOCS="LICENSE *.rst"

ARCH=$(uname -m)
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
GIT_URL="https://github.com/Kozea/cairocffi.git"
[ ! -e $REPOSITORY ] && git clone "$GIT_URL" $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

# installation
python3 ./setup.py install --root=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R $DOCS $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (CFFI-based cairo bindings for Python)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/Kozea/cairocffi
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
