#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
UPSTREAM_REPO=https://github.com/libsdl-org/sdl12-compat
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
cd "$TMP" || exit
[ ! -e "$REPOSITORY" ] && git clone ${UPSTREAM_REPO}.git "$REPOSITORY"

cp -R "$REPOSITORY" "${TMP:?}/$PRGNAM"
cd "$TMP/$PRGNAM" || exit

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
if [ "$VERSION" == "trunk" ]; then
    VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
else
    git checkout "$VERSION"
fi

# configuration
mkdir -p build
cd build || exit

cmake \
    -DSDL12TESTS=0 \
    -DSDL12DEVEL=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    ..

# compilation
make "-j$(nproc)"

# installation
make install DESTDIR="$PKG"

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R ../*.txt ../*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit
chown -R root:root ./*

find . -name \.git\* -exec rm -fr {} \;

[ -d .${PREFIX}/man ] && find .${PREFIX}/man -type f -name "*.?" -exec gzip -9f {} \;

# # Strip binaries
# cd $PKG
# find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
# find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/slack-desc"
$PRGNAM: $PRGNAM (An SDL-1.2 compatibility layer that uses SDL 2.0 behind the scenes.)
$PRGNAM:
$PRGNAM: WARNING: this overwrites many files of the sdl package.
$PRGNAM:  - If you remove this package make sure to reinstall sdl after.
$PRGNAM:  - If sdl is upgraded, make sure to reinstall sdl12-compat afterward
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
EOF

# empaquetage
rm -f "${PKG:?}"/{,usr/}lib"$(uname -m | grep -o 64)"/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-${VERSION//-/_/}-$ARCH-$BUILD$TAG.txz"
