#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%Y.%m.%d_%H.%M)}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
rm -fr $PKG
mkdir -p $PKG             # place for the package to be built
                          # remove old log files

FONTDIR="/usr/share/fonts/OTF"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR
cd $PKG$FONTDIR/
if [ -e $CWD/Inconsolata.otf ] ; then
    cp $CWD/Inconsolata.otf .
else
    wget -c http://www.levien.com/type/myfonts/Inconsolata.otf
fi
if [ -e $CWD/Inconsolata-dz.otf.zip ] ; then
    unzip $CWD/Inconsolata-dz.otf.zip
else
    wget -c http://media.nodnod.net/Inconsolata-dz.otf.zip ;
    unzip Inconsolata-dz.otf.zip
    rm Inconsolata-dz.otf.zip
fi

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Monospace font)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.levien.com/type/myfonts/inconsolata.html
$PRGNAM: http://nodnod.net/2009/feb/12/adding-straight-single-and-double-quotes-inconsola/
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz

