#!/bin/bash

# variables
UPSTREAM_REPO=https://github.com/nemuTUI/nemu
VERSION=${VERSION:-latest}

BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO} $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM/

[ "$VERSION" == "latest" ] && VERSION=$(git describe --tags --abbrev=0)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION


mkdir -p build/
cd build/ || exit 1

cmake -G Ninja .. -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON -DNM_WITH_USB=ON -DCMAKE_INSTALL_PREFIX=$PREFIX
cmake --build .
DESTDIR=$PKG cmake --install .
mv $PKG$PREFIX/share/man $PKG$PREFIX/

cd ../ || exit 1

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp CHANGES LICENSE ./*.md ./*.sample $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Ncurses UI for QEMU)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
