#!/bin/sh

PRGNAM=Bodoni-SvtyTwo-OS-ITC-TT
VERSION=${VERSION:-$(date +"%Y.%m.%d_%H:%M")}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log
                          # remove old log files

FONTDIR="/usr/share/fonts"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/TTF

( cd $PKG$FONTDIR/TTF
    for fnt in bold.ttf bolditalic.ttf italic.ttf book.ttf ; do
        [ ! -e $CWD/$fnt ] && ( cd $CWD ; wget -c http://foohack.com/tpl/fonts/$PRGNAM/$fnt )
        cp $CWD/$fnt ./$PRGNAM-$fnt
    done
)

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (font)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz

