#!/bin/sh

# Copyright 2008, 2009  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


VERSION=git$(date +%Y.%m.%d_%H.%M)
ARCH=${ARCH:-x86_64}
BUILD=${BUILD:-1gwh}

NUMJOBS=${NUMJOBS:-" -j3 "}

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=${TMP:-/tmp}
PKG=$TMP/pkg-gimp
REPOSITORIES=/home/installs/SlackBuilds/repositories

rm -rf $PKG
mkdir -p $TMP $PKG

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

cd $TMP
rm -rf gimp-$VERSION
( cd $REPOSITORIES/gimp
    git pull
)
cp -R $REPOSITORIES/gimp gimp-$VERSION
cd gimp-$VERSION || exit 1
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
./autogen.sh \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --docdir=/usr/doc/gimp-$VERSION \
  --disable-static \
  --enable-gimp-remote \
  --without-gvfs \
  --with-libcurl \
  --build=$ARCH-slackware-linux

make $NUMJOBS || make || exit 1
mkdir -p $PKG/usr/share/applications $PKG/usr/share/application-registry
make install DESTDIR=$PKG || exit 1

( cd $PKG/usr/bin
    ln -s gimp-remote-2.? gimp-remote
    ln -s gimp-console-2.? gimp-console
    ln -s gimp-2.? gimp
    ln -s gimptool-2.? gimptool
)

# Add a manpage symlink for POLA-compliance
( cd $PKG/usr/man/man1 ; ln -sf gimptool-2.?.1 gimptool.1 )

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
)

mkdir -p $PKG/usr/doc/gimp-$VERSION
cp -a \
  AUTHORS COPYING HACKING INSTALL LICENSE NEWS README* docs/Wilber* \
  $PKG/usr/doc/gimp-$VERSION
( cd $PKG/usr/doc/gimp-$VERSION
  for i in \
    libgimp libgimpbase libgimpcolor libgimpconfig libgimpmath \
    libgimpmodule libgimpthumb libgimpwidgets ; do \
   ln -s /usr/share/gtk-doc/html/$i $i-html ; 
  done
)

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/gimp-$VERSION-$ARCH-$BUILD.txz

