#!/bin/sh

# variables
TAG=cyco
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

VERSION=$(date +%Y.%m.%d_%H.%M)

DOCS="AUTHORS LICENSE README.rst dev-requirements.txt"

ARCH=$(uname -m)
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

REPOSITORIES=/home/installs/SlackBuilds/repositories
# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORIES/$PRGNAM ] ; then
    git clone https://github.com/mopidy/mopidy.git $REPOSITORIES/${PRGNAM}
else
    ( cd $REPOSITORIES/${PRGNAM}
      git pull
    )
fi
cp -R $REPOSITORIES/${PRGNAM} $TMP/$PRGNAM-$VERSION
cd $TMP/$PRGNAM-$VERSION

# installation
python ./setup.py install --root=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -R $DOCS $PKG/usr/doc/$PRGNAM-$VERSION

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (extensible music server written in Python.)
$PRGNAM:
$PRGNAM: Mopidy is an extensible music server that plays music from local disk, Spotify,
$PRGNAM: SoundCloud, Google Play Music, and more. You edit the playlist from any phone,
$PRGNAM: tablet, or computer using a range of MPD and web clients.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://www.mopidy.com/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
