#!/bin/sh
set -x

PRGNAM=webrowse
VERSION=1.7.0

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "64")

CWD=$(pwd)
TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

PREFIX=/usr

# Cleaning
( cd $TMP
    rm -fr $PRGNAM-$VERSION
    rm -fr $PKG
)

# Fetching sources
[ ! -e $CWD/$PRGNAM-$VERSION.tgz ] \
    && wget -c http://www.cs.indiana.edu/~kinzler/$PRGNAM/$PRGNAM-$VERSION.tgz
( cd $TMP
    tar xvf $CWD/$PRGNAM-$VERSION.tgz
)

# Preparation
( cd $TMP/$PRGNAM-$VERSION
    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Building
( cd $TMP/$PRGNAM-$VERSION
    make PERL=$(which perl)
)

# Installation
mkdir -p $PKG$PREFIX/{bin,man/man1}
( cd $TMP/$PRGNAM-$VERSION
    make install install.man BINDIR=$PKG$PREFIX/bin MANDIR=$PKG$PREFIX/man/man1
)

# Cleaning
( cd $PKG
    find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
    find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

    find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Packaging
( cd $PKG
    mkdir install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (web browsing tools )
$PRGNAM:
$PRGNAM: $PRGNAM is a tool for interfacing between a Netscape or Mozilla (or Mosaic)
$PRGNAM: web browser and the rest of a Unix/X11 environment, via the `-remote` option.
$PRGNAM: It can be used for convenient file or URL loading remote control, and for
$PRGNAM: textual reference HTML markup.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://www.cs.indiana.edu/~kinzler/webrowse/
$PRGNAM:
EOF

    makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
)

