#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
UPSTREAM_REPO=https://github.com/Kron4ek/Conty
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/Kron4ek/Conty/releases/latest | grep tag_name | grep -o "[0-9.]*")}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-6}
TAG=${TAG:-gwh}

EDITION=${EDITION:-"_lite_dwarfs"} # "", "_lite", "_dwarfs", "_lite_dwarfs"

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
PREFIX=/usr

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

mkdir -p "$REPOSITORY"

[ ! -e "$REPOSITORY/conty${EDITION}-${VERSION}.sh" ] && wget -c "${UPSTREAM_REPO}/releases/download/${VERSION}/conty${EDITION}.sh" -O "$REPOSITORY/conty${EDITION}-${VERSION}.sh"

rm -fr "$PKG"

mkdir -p "$PKG$PREFIX/bin"
cp "$REPOSITORY/conty${EDITION}-${VERSION}.sh" "$PKG$PREFIX/bin/conty"

cd "$PKG$PREFIX/bin/" || exit 1
cat <<EOF > steam
#!/bin/bash

# https://github.com/ValveSoftware/steam-for-linux/issues/11358
unset SDL_VIDEODRIVER

$PREFIX/bin/conty steam "\$@"
EOF

mkdir -p "$PKG$PREFIX/share/applications/"
cat <<EOF > "$PKG$PREFIX/share/applications/steam.desktop"
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=$PREFIX/bin/steam
Name=Steam
EOF

for prg in lutris playonlinux4; do
    ln -s conty $prg
cat <<EOF > "$PKG$PREFIX/share/applications/$prg.desktop"
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=$PREFIX/bin/$prg
Name=$prg
EOF
done

chmod +x "$PKG$PREFIX/bin"/*

mkdir -p "$PKG/install"
cat <<EOF > "$PKG/install/slack-desc"
       |-----handy-ruler--------------------------------------------------------|
$PRGNAM: $PRGNAM (Easy to use non-root container packed into a single executable)
$PRGNAM:
$PRGNAM: a portable Arch Linux distro packed into a single executable that can
$PRGNAM: be used to run any applications
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
