#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

mkdir -p $OUTPUT
mkdir -p $PKG
rm -rf $PKG/*
rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log

FONTDIR="/usr/share/fonts"

[ ! -e $CWD/Noto-hinted.zip ] && wget -c https://noto-website.storage.googleapis.com/pkgs/Noto-hinted.zip -O $CWD/Noto-hinted.zip

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/{TTF,OTF} $PKG/usr/doc/$PRGNAM/
cd $PKG/usr/doc/$PRGNAM/
unzip $CWD/Noto-hinted.zip
mv *.ttf $PKG$FONTDIR/TTF
mv *.otf $PKG$FONTDIR/OTF

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Beautiful and free fonts for all languages)
$PRGNAM:
$PRGNAM: Noto is Google’s font family that aims to support all the world’s languages.
$PRGNAM: Its design goal is to achieve visual harmonization across languages.
$PRGNAM: Noto fonts are under Apache License 2.0.
$PRGNAM:
$PRGNAM: The comprehensive set of fonts and some of the tools used in our development
$PRGNAM: are available at http://noto.googlecode.com.
$PRGNAM:
$PRGNAM:
$PRGNAM:
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
