#!/bin/bash

# Slackware build script for dwl

# Copyright 2022 Damian Perticone,  Berisso, Argentina
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=$(basename $CWD)
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}
PKGTYPE=${PKGTYPE:-txz}

GITHUB_REPO=djpohly/dwl
REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM
VERSION=${VERSION:-"latest"}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO} $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/

cd $TMP/$PRGNAM/
case $VERSION in
    trunk)
        git checkout wlroots-next
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION=$(git tag --sort=-taggerdate | head -n1)
        git checkout $VERSION
        ;;
    *)
        git checkout $VERSION
        ;;
esac

# fix to correct man pages directory path
sed -i 's/share/man/g' config.mk

# # compile with XWayland support
# XWAYLAND=${XWAYLAND:-yes}
# [ "$XWAYLAND" = "yes" ] && patch -p1 <$CWD/sbo-patches/use-XWayland.patch

# autostart patch for stuff like swaybg
#patch -p1 < $CWD/sbo-patches/autostart.patch

mkdir -p $PKG/usr/share/wayland-sessions

# use bar
SOMEBAR=${SOMEBAR:-no}
[ "$SOMEBAR" = "yes" ] && cat $CWD/sbo-patches/dwl.desktop > $PKG/usr/share/wayland-sessions/dwl.desktop
[ "$SOMEBAR" = "no" ] && cat $CWD/dwl.desktop > $PKG/usr/share/wayland-sessions/dwl.desktop

# use win key instead of alt key
MODWINKEY=${MODWINKEY:-no}
[ "$MODWINKEY" = "yes" ] && patch -p1 <$CWD/sbo-patches/use-winkey.patch

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

### for those that wish to include custom patches.
### A sample patch is included in the patches/ directory
### that will change the default terminal from 'alacritty'
### to 'foot'.

#find $CWD/patches/ -name \*.patch -exec patch --verbose -p1 -i {} \;

make \
  OPTS="$SLKCFLAGS" \
  PREFIX=/usr \
  MANPREFIX=/usr/man \
  XWAYLAND=-DXWAYLAND \
  XLIBS=xcb xcb-icccm

make PREFIX=$PKG/usr install

mkdir -p $PKG/usr/man/man1
cp -a $PKG/usr/man/man/man1/dwl.1 $PKG/usr/man/man1/dwl.1
rm -r $PKG/usr/man/man

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a LICENSE LICENSE.dwm LICENSE.tinywl README.md  $PKG/usr/doc/$PRGNAM
cat $CWD/SlackBuild > $PKG/usr/doc/$PRGNAM/SlackBuild

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.
# Line up the first '|' above the ':' following the base package name, and
# the '|' on the right side marks the last column you can put a character in.
# You must make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':' except on otherwise blank lines.

   |-----handy-ruler------------------------------------------------------|
dwl: dwl (wayland compositor based on wlroots)
dwl:
dwl: Dwl dwl is a compact, hackable compositor for Wayland based on
dwl: wlroots. It is intended to fill the same space in the Wayland world
dwl: that dwm does in X11
dwl:
dwl:
dwl:
dwl: Home: https://github.com/djpohly/dwl
dwl:
dwl:
EOF

cat <<EOF > $PKG/install/doinst.sh
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi
EOF

cd $PKG
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
