#!/bin/sh

CWD=$(pwd)
PRGNAM=$(basename $CWD)
VERSION=git_$(date +%Y.%m.%d_%H.%M)
ARCH=$(uname -m)
BUILD=1


PREFIX=/usr
LIBSUFFIX=$(echo $ARCH | grep -o 64)

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories

if [ -e $REPOSITORIES/$PRGNAM ] ; then
    ( cd $REPOSITORIES/$PRGNAM
        git pull
    )
else
    git clone http://repo.or.cz/r/conkeror.git $REPOSITORIES/$PRGNAM
fi

rm -fr $PKG

mkdir -p $PKG$PREFIX/libexec/
cp -R $REPOSITORIES/$PRGNAM $PKG$PREFIX/libexec/
cd $PKG$PREFIX/libexec/$PRGNAM
make conkeror-spawn-helper
rm -fr .git .gitignore

mkdir -p $PKG$PREFIX/bin
cd $PKG$PREFIX/bin
ln -s ../libexec/$PRGNAM/conkeror-spawn-helper conkeror-spawn-helper

# "Firefox 3 and later ships with a private XULRunner package, which can run any compatible XULRunner application using the -app switch." -- https://developer.mozilla.org/en-US/docs/XULRunner
cat <<EOF > $PKG$PREFIX/bin/conkeror
#!/bin/sh
exec /usr/bin/firefox -app $PREFIX/libexec/$PRGNAM/application.ini "\$@"
EOF
chmod 755 $PKG$PREFIX/bin/conkeror

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cd $PKG$PREFIX/doc/$PRGNAM
for d in COPYING CREDITS INSTALL help ; do
    ln -s ../../libexec/$PRGNAM/$d $d
done

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Web browser)
$PRGNAM: 
$PRGNAM: Conkeror is a keyboard-oriented, highly-customizable, highly-extensible
$PRGNAM: web browser based on Mozilla XULRunner, written mainly in JavaScript, and
$PRGNAM: inspired by exceptional software such as Emacs and vi. Conkeror features
$PRGNAM: a sophisticated keyboard system, allowing users to run commands and interact
$PRGNAM: with content in powerful and novel ways. It is self-documenting, featuring a
$PRGNAM: powerful interactive help system. 
$PRGNAM: 
$PRGNAM: http://conkeror.org/
$PRGNAM: 
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
