#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=beta_0.5
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
# [ ! -e $REPOSITORIES ] && mkdir -p $REPOSITORIES
# ( cd $REPOSITORIES
#     if [ -e $REPOSITORIES/$PRGNAM ] ; then
#         ( cd $REPOSITORIES/$PRGNAM
#             git pull
#         )
#     else
#         git clone http://github.com/bauhouse/fluid960gs.git $REPOSITORIES/$PRGNAM
#     fi
# )

mkdir -p $PKG/srv/www/htdocs/$PRGNAM
#cp -R $REPOSITORIES/$PRGNAM $PKG/srv/www/htdocs/
[ ! -e $CWD/${PRGNAM}_$VERSION.zip ] && ( cd $CWD ; wget -c http://52framework.com/download/${PRGNAM}_$VERSION.zip )
( cd $PKG/srv/www/htdocs/$PRGNAM
    unzip $CWD/${PRGNAM}_$VERSION.zip
)
#find $PKG/srv/www/htdocs -name \.git\* -exec rm -fr {} \;

( cd $PKG
    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (HTML5 & CSS3 framework)
$PRGNAM: 
$PRGNAM: The 52framework was started by the enavu network as a way to expedite the process
$PRGNAM: of the usage of the latest standards in web development, and the love of the
$PRGNAM: number 52. The 52framework provides an easy way to get started using html5 and
$PRGNAM: css3 while still supporting all modern browsers (including ie6).
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://52framework.com/
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
