#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/original-tinozza/amdgpu-fancontrol"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

#configuration

#build

#install
mkdir -p "$PKG$PREFIX/bin"
cp "$REPOSITORY"/amdgpu-fanc* "$PKG$PREFIX/bin/"
chmod 755 "$PKG$PREFIX/bin"/*

#install docs
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp "$REPOSITORY"/LICENSE "$REPOSITORY"/README.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -type f -not -name \*.gz -exec gzip -9 {} \;

# packaging
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (script to manually control cooling fans of modern AMD GPUs)
$PRGNAM:
$PRGNAM: This is a simple bash script that can be used to control the cooling
$PRGNAM: fans of recent AMD GPUs supported by the amdgpu kernel driver. The
$PRGNAM: script is able to let the user control manually the fans rotational
$PRGNAM: speed by changing directly the fans PWM set-point or by defining a
$PRGNAM: custom fans control curve (with a separate curve definition file or
$PRGNAM: using directly the script user interface).
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}/
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
