#!/bin/bash

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1


TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    git clone git://anongit.freedesktop.org/git/geoclue $REPOSITORY
else
	( cd $REPOSITORY
		git pull
	)
fi

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
./autogen.sh
./configure \
    --prefix=$PREFIX \
    --libdir=$PREFIX/lib$(echo "$ARCH" | grep -o 64) \
	--mandir=$PREFIX/man

make
make install DESTDIR=$PKG

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (The Geoinformation Service)
$PRGNAM:
$PRGNAM: Geoclue is a modular geoinformation service built on top of the D-Bus
$PRGNAM: messaging system. The goal of the Geoclue project is to make creating
$PRGNAM: location-aware applications as simple as possible.
$PRGNAM: Geoclue defines a set of geoinformation APIs, but it also includes
$PRGNAM: some providers that implement those APIs.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.freedesktop.org/wiki/Software/GeoClue
$PRGNAM: 
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
