#!/bin/sh

CWD=$(pwd)
TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PRGNAM=$(basename $CWD)
ARCH=${ARCH:-$(uname -m | grep -q 64 && echo "x86_64" || echo "i386")}
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/commercialhaskell/stack/releases/latest | grep tag_name | grep -o "v[0-9.]*" | tr -d v)}
BUILD=${BUILD:-1}
TAG=${TAG:-cyco}

rm -rf $PKG
mkdir -p $PKG/usr/{bin,doc} $OUTPUT
cd $PKG/usr/doc/

wget -c https://github.com/commercialhaskell/stack/releases/download/v${VERSION}/stack-${VERSION}-linux-${ARCH}.tar.gz -O stack.tar.gz
tar xvf stack.tar.gz
rm stack.tar.gz
mv stack-${VERSION}-linux-${ARCH} stack
mv stack/stack $PKG/usr/bin/

# Make sure top-level perms are correct:
chmod 0755 $PKG/usr/bin/stack

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler----------------------------------------------------|
$PRGNAM: $PRGNAM (The Haskell Tool Stack)
$PRGNAM:
$PRGNAM: $PRGNAM is a cross-platform program for developing Haskell projects.
$PRGNAM: It is aimed at Haskellers both new and experienced.
$PRGNAM:
$PRGNAM:
$PRGNAM: $ stack setup
$PRGNAM:
$PRGNAM:
$PRGNAM: Homepage:  https://www.stackage.org/
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
