#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $(pwd))
UPSTREAM_REPO=https://github.com/ebeem/guile-swayer
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/var/cache/SlackBuilds.gwh

PREFIX=/usr

[ ! -e $REPOSITORIES/$PRGNAM ] && git clone ${UPSTREAM_REPO}.git $REPOSITORIES/$PRGNAM
cd $REPOSITORIES/$PRGNAM
git pull --all

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
cp -R $REPOSITORIES/$PRGNAM $TMP/$PRGNAM

cd $TMP/$PRGNAM
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

autoreconf -i
./configure \
    --prefix=/usr

# installation
make install DESTDIR=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM
cp LICENSE README* $PKG/usr/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM ( Extensible Guile bindings for SwayWM )
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: see https://github.com/ebeem/dotfiles/tree/main/.config/sway
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
