#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
FONTDIR="/usr/share/fonts"

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log


[ ! -e $REPOSITORY ] && git clone https://github.com/impallari/Encode-Sans.git $REPOSITORY
cd $REPOSITORY
git pull
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/TTF $PKG/usr/doc/$PRGNAM

cd $REPOSITORY
cp *.txt *.md $PKG/usr/doc/$PRGNAM
cp fonts/*.ttf $PKG$FONTDIR/TTF

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Encode Sans Fonts)
$PRGNAM:
$PRGNAM: The Encode Sans family is a versatile workhorse. Featuring a huge range of
$PRGNAM: weights and widths, it's ready for all kind of typographic challenges. It
$PRGNAM: also includes Tabular and Old Style figres, as well as full set of Small
$PRGNAM: Caps and other Open Type features.
$PRGNAM:
$PRGNAM: Designed by Pablo Impallari and Andres Torresi.
$PRGNAM:
$PRGNAM: https://github.com/impallari/Encode-Sans
$PRGNAM:
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
