#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=$(uname -m)

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
if [ ! -e $REPOSITORIES/$PRGNAM ]; then
    mkdir -p $REPOSITORIES/$PRGNAM
    ( cd $REPOSITORIES/$PRGNAM
        httrack http://www-inst.eecs.berkeley.edu/~cs61a/sp12/
    )
else
    ( cd $REPOSITORIES/$PRGNAM
        httrack --update
    )
fi

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORIES/$PRGNAM $PKG$PREFIX/doc/$PRGNAM

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Teaching SICP using Python3 course)
$PRGNAM: 
$PRGNAM: Berkeley class
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www-inst.eecs.berkeley.edu/~cs61a/sp12/
$PRGNAM: 
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
