#!/bin/bash

# variables
UPSTREAM_REPO=https://github.com/pinnacle-comp/pinnacle
VERSION=${VERSION:-latest}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}"/"$PRGNAM"

mkdir -p "$PKG"

# mise en place
cd "$TMP" || exit 1
[ ! -e "$REPOSITORY" ] && git clone ${UPSTREAM_REPO}.git "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all

cp -R "$REPOSITORY" $TMP/
cd "$TMP"/"$PRGNAM" || exit 1
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" # || git checkout $VERSION

export RUSTUP_TOOLCHAIN=stable
cargo fetch --locked

export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target
cargo build --frozen --release

mkdir -p "$PKG$PREFIX"/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} "$PKG$PREFIX"/bin/ \;
chmod 755 "$PKG$PREFIX"/bin/*

install -vDm 644 resources/"$PRGNAM"{.service,-shutdown.target} -t "$PKG/usr/lib/systemd/user/"
install -vDm 644 resources/"$PRGNAM".desktop -t "$PKG/usr/share/wayland-sessions/"
install -vDm 644 resources/"$PRGNAM"-portals.conf -t "$PKG/usr/share/xdg-desktop-portal/"

# lua
install -vd "$PKG/usr/share/$PRGNAM"
install -vd "$PKG/usr/share/$PRGNAM/snowcap"
cp -vR api/protobuf "$PKG/usr/share/$PRGNAM"
cp -vR snowcap/api/protobuf "$PKG/usr/share/$PRGNAM/snowcap"

# move doc/ to the appropriate location
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R assets/ wiki/ LICENSE ./*.md "$PKG$PREFIX/doc/$PRGNAM/"

( cd ./api/lua || exit 1
  luarocks make --pack-binary-rock
  # find . -type f -depath 1 -name \*.rockspec -exec luarocks pack {} \;
  cp ./*.rock "$PKG$PREFIX/doc/$PRGNAM/"
)

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX"/man ] && find "$PKG$PREFIX"/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p "$PKG"/install

cat <<EOF > "$PKG"/install/doinst.sh
#!/bin/bash
find "$PREFIX/doc/$PRGNAM/" -type f -name \\*.rock -exec luarocks install --force {} \;
EOF

cat <<EOF > "$PKG"/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A WIP Smithay-based Wayland compositor, inspired by AwesomeWM)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM:
EOF

# empaquetage
rm -f "$PKG"/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
