#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
VERSION=${VERSION:-$(curl -s https://codeberg.org/readeck/readeck/releases.rss | grep title | head -n2 | tail -n1 | sed 's|<title>||g' | sed 's|</title>||g' | xargs)}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
PREFIX=/usr

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}

mkdir -p "$REPOSITORY"

WORK_DIR=/var/lib/readeck

echo "$ARCH" | grep -q 64 && SRC_ARCH=amd64

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

# Check if the readeck user and group exist. If not, then bail.
if [ "$(id -g readeck 2> /dev/null)" != "876" -o "$(id -u readeck 2> /dev/null)" != "876" ]; then
    echo "  You must have an 'readeck' user and group to run this script."
    echo "    # groupadd -g 876 readeck"
    echo "    # useradd -d /var/lib/readeck -g readeck -s /bin/bash -u 876 readeck --system "
    exit 1
fi

mkdir -p "$REPOSITORY"

[ ! -e "$REPOSITORY/readeck-${VERSION}-linux-${SRC_ARCH}" ] && wget -c "https://codeberg.org/readeck/readeck/releases/download/${VERSION}/readeck-${VERSION}-linux-${SRC_ARCH}" -O "$REPOSITORY/readeck-${VERSION}-linux-${SRC_ARCH}"

rm -fr "$PKG"

mkdir -p "$PKG$PREFIX/bin"
cp "$REPOSITORY/readeck-${VERSION}-linux-${SRC_ARCH}" "$PKG$PREFIX/bin/readeck"
chmod +x "$PKG$PREFIX"/bin/readeck

mkdir -p "$PKG$WORK_DIR"

mkdir -p "$PKG"/etc/readeck/
cat <<EOF > "$PKG"/etc/readeck/config.toml.new
[main]
log_level = "INFO"
secret_key = "$(openssl rand -base64 48)"
data_directory = "${WORK_DIR}"

[server]
host = "0.0.0.0"
port = 8000
allowed_hosts

[database]
source = "sqlite3:${WORK_DIR}/db.sqlite3"
EOF
chown -R readeck:readeck "$PKG"/etc/readeck
chmod 770 "$PKG"/etc/readeck

mkdir -p "$PKG"/var/log/readeck
chown -R readeck:readeck "$PKG"/var/log/readeck "$PKG$WORK_DIR"

mkdir -p "$PKG/etc/rc.d/"
cat <<EOF > "$PKG/etc/rc.d/rc.$PRGNAM"
#!/bin/bash
#Slackware startup deamon script

# Name of Service
NAME="Readeck Daemon"

# Command to run
CMD="/usr/bin/readeck"

# user used to run the daemon
USERNAME=readeck

# Option to run with deamon
OPTIONS=" serve -config /etc/readeck/config.toml"

func_status() {
    pgrep -u \$USERNAME readeck && echo Running || echo Stopped
}

func_stop() {
    pkill -u \$USERNAME readeck

    func_status
}

func_start() {
    echo -n "Starting \$NAME ... "
    [ ! -e /etc/readeck/config.toml ] && exit 1
    su - \$USERNAME -c "\$CMD \$OPTIONS" &

    sleep 2

    func_status
}


case \$1 in
    "start")
        func_start
        ;;

    "stop")
        func_stop
        ;;

    "restart")
        func_stop
        sleep 2
        func_start
        ;;

    "status")
        func_status
        ;;

    *)
        echo "Usage; start|stop|restart"
        ;;
esac
EOF
chmod +x "$PKG/etc/rc.d/rc.$PRGNAM"

mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
           # HOW TO EDIT THIS FILE:
           # The "handy ruler" below makes it easier to edit a package description.  Line
           # up the first '|' above the ':' following the base package name, and the '|'
           # on the right side marks the last column you can put a character in.  You must
           # make exactly 11 lines for the formatting to be correct.  It's also
           # customary to leave one space after the ':'.

       |-----handy-ruler--------------------------------------------------------|
$PRGNAM: $PRGNAM (Your Own Content Hub)
$PRGNAM:
$PRGNAM: That article you want to read later today? The photo you’d love to keep
$PRGNAM:  forever? Or the video you want to save for this weekend?
$PRGNAM:
$PRGNAM: Readeck helps you collect them as Bookmarks, ready for you whenever you
$PRGNAM:  are.
$PRGNAM:
$PRGNAM:
$PRGNAM: https://readeck.org/
$PRGNAM:
EOF

cd "$PKG" || exit 1

/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
