#!/bin/bash

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-1.036}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log
                          # remove old log files

FONTDIR="/usr/share/fonts"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/{OTF,TTF} $PKG/usr/doc/$PRGNAM
cd $PKG$FONTDIR/
[ ! -e $CWD/${PRGNAM}_FontsOnly-$VERSION.zip ] && \
	wget -c --no-check-certificate "https://github.com/downloads/adobe/Source-Sans-Pro/${PRGNAM}_FontsOnly-$VERSION.zip" \
	-O $CWD/${PRGNAM}_FontsOnly-$VERSION.zip
unzip $CWD/${PRGNAM}_FontsOnly-$VERSION.zip
cd ${PRGNAM}_FontsOnly-$VERSION
mv *.{html,txt} $PKG/usr/doc/$PRGNAM
mv *.ttf ../TTF
mv *.otf ../OTF
cd ..
rm -fr ${PRGNAM}_FontsOnly-$VERSION

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Adobe Open Source font)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: https://github.com/adobe/Source-Sans-Pro#readme
$PRGNAM: 
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz

