#!/bin/bash

# variables
VERSION=master_$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
REPOSITORY_IMPORTERS=/home/installs/SlackBuilds/repositories/$PRGNAM-importers
PREFIX=/usr

EMACS=$(basename $(ls /usr/bin/emacs-2*))
EMACS_VERSION=$(echo "$EMACS" | grep -o "\-[0-9\.]*\-" | tr -d - | head -n1)

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
    git clone "http://github.com/punchagan/org2blog.git" $REPOSITORY
else
	( cd $REPOSITORY
		git pull
	)
fi
if [ ! -e $REPOSITORY_IMPORTERS ] ; then
    git clone "http://github.com/punchagan/org2blog-importers.git" $REPOSITORY_IMPORTERS
else
	( cd $REPOSITORY_IMPORTERS
		git pull
	)
fi

mkdir -p $PKG$PREFIX/share/emacs/site-lisp $PKG$PREFIX/doc/$PRGNAM
cp -R $REPOSITORY $PKG$PREFIX/share/emacs/site-lisp
cd $PKG$PREFIX/share/emacs/site-lisp/$PRGNAM
$EMACS -batch -f batch-byte-compile *.el

mv README* $PKG$PREFIX/doc/$PRGNAM
cp -R $REPOSITORY_IMPORTERS $PKG$PREFIX/doc/$PRGNAM

rm -fr .git $PKG$PREFIX/doc/$PRGNAM/$PRGNAM-importers/.git

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Emacs: from org-mode to WordPress)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://github.com/punchagan/org2blog
$PRGNAM: 
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
