#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=noarch

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone "git://github.com/zsh-users/zsh-syntax-highlighting.git" $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/share/zsh/site-functions/
cp -R $REPOSITORY/highlighters/ $PKG$PREFIX/share/zsh/site-functions/
cp -R $REPOSITORY/zsh-syntax-highlighting.zsh $PKG$PREFIX/share/zsh/site-functions/_zsh-syntax-highlighting

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R $REPOSITORY/* $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (Fish shell like syntax highlighting for Zsh.)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://github.com/zsh-users/zsh-syntax-highlighting
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
