#!/bin/sh

# variables
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=cyco
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=noarch

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone git://github.com/zsh-users/antigen.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/share/antigen/
cp $REPOSITORY/antigen.zsh $PKG$PREFIX/share/antigen/

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R $REPOSITORY/*.{txt,mkd} $PKG$PREFIX/doc/$PRGNAM/
cp $CWD/*.SlackBuild $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A plugin manager for zsh, inspired by oh-my-zsh and vundle.)
$PRGNAM:
$PRGNAM: Antigen is a small set of functions that help you easily manage your
$PRGNAM: shell (zsh) plugins, called bundles.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://antigen.sharats.me
$PRGNAM: http://github.com/zsh-users/antigen
$PRGNAM:
EOF

# empaquetage
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
