#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/leozide/leocad"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all > /dev/null 2>&1

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

LIBRARY_URL=$(curl -s https://api.github.com/repos/leozide/leocad/releases | grep -o "http.*Library-.*zip" | sort | tail -n1)
LIBRARY_FILE=$(echo "$LIBRARY_URL" | grep -o "Library-[0-9.]*.zip")
LIBRARY_VERSION=$(echo "$LIBRARY_FILE" | grep -o "[0-9.]*")
[ ! -e "$REPOSITORY/$LIBRARY_FILE" ] && wget --quiet -c -O "$REPOSITORY/$LIBRARY_FILE" "$LIBRARY_URL"

PACKAGE_NAME="$PRGNAM-${VERSION//-/}_${LIBRARY_VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

qmake-qt5 DISABLE_UPDATE_CHECK=1 DOCS_DIR=/usr/doc/"$PRGNAM" MAN_DIR=/usr/man/man1 leocad.pro
CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      make
make INSTALL_ROOT="$PKG" install

mkdir -p "$PKG"/usr/man/man1
cp -a docs/leocad.1 "$PKG"/usr/man/man1
find "$PKG"/usr/man -type f -exec gzip -9 {} \;
for i in $( find "$PKG"/usr/man -type l ) ; do ln -s "$( readlink "$i" ).gz" "$i.gz" ; rm "$i" ; done

# Data from zip-file + set permissions
mkdir -p "$PKG"/usr/share/leocad
unzip "$REPOSITORY/$LIBRARY_FILE" -d "$PKG"/usr/share/leocad/

# correction
chown -R root:root "$PKG"/*

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/doinst.sh
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
  fi
fi
EOF

cat <<EOF > "$PKG"/install/slack-desc
      |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (CAD program for toy bricks)
$PRGNAM:
$PRGNAM: $PRGNAM is a CAD program that uses bricks similar to those
$PRGNAM: found in many toys (but they don't represent any particular brand).
$PRGNAM: Currently it uses a library of more than 7000 different pieces.
$PRGNAM:
$PRGNAM: https://www.$PRGNAM.org/
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
