#!/bin/bash

CWD=$(pwd)
TAG=${TAG:-gwh}
OUTPUT=${OUTPUT:-/tmp}
TMP=/tmp/$TAG

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(echo $PRGNAM-*.zip | grep -o "[0-9.]*" | head -n1)}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-1}

PKG=$TMP/pkg-$PRGNAM

rm -rf $PKG

mkdir -p $TMP
cd $TMP

mkdir -p $PKG/usr/games/ $PKG/opt/
cd $PKG/opt/
[ ! -e $CWD/$PRGNAM-$VERSION-pc.zip ] && exit 1
unzip $CWD/$PRGNAM-$VERSION-pc.zip
mv $PRGNAM-$VERSION-pc $PRGNAM

cd $PKG/usr/games/
ln -s ../../opt/$PRGNAM/$PRGNAM.sh

mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

            |-----handy-ruler------------------------------------------------------|
${PRGNAM}: ${PRGNAM} (NSFW game)
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}:
${PRGNAM}: (You need to download the game and put the file $PRGNAM-X.x.x-pc.zip
${PRGNAM}:  and put it next to this script)
${PRGNAM}:
${PRGNAM}: https://dark-coffee-ink.itch.io/back-to-the-booty-a-porn-parody-game
${PRGNAM}:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}$TAG.txz
