#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=noarch

REPOSITORIES=/home/installs/SlackBuilds/repositories/$PRGNAM

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORY ] && git clone https://github.com/adambard/learnxinyminutes-docs $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORY $PKG$PREFIX/doc/$PRGNAM
find $PKG$PREFIX/doc/$PRGNAM -name \.git\* -exec rm -fr {} \;

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (A book on functional programming in CoffeeScript)
$PRGNAM:
$PRGNAM: Whirlwind tours of (several, hopefully many someday) popular and
$PRGNAM: ought-to-be-more-popular programming languages, presented as valid,
$PRGNAM: commented code and explained as they go.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://learnxinyminutes.com
$PRGNAM: https://github.com/adambard/learnxinyminutes-docs
$PRGNAM:
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
