#!/bin/bash

# variables
VERSION=${VERSION:-"latest"}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=noarch

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/_repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

# mise en place
[ ! -e "$REPOSITORY" ] && git clone https://git.sr.ht/~rabbits/uxn "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all

cp -R "$REPOSITORY" "$TMP/"
cd "$TMP/$PRGNAM" || exit 1
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

./build.sh --no-run

mkdir -p "$PKG$PREFIX/bin"
cp bin/uxn{asm,cli,emu} "$PKG$PREFIX/bin/"

mkdir -p "$PKG$PREFIX/share/$PRGNAM/"
cp bin/*.rom "$PKG$PREFIX/share/$PRGNAM/"

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R LICENSE README.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (An assembler and emulator for the Uxn stack-machine)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://git.sr.ht/~rabbits/uxn
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz"
