#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://git.sr.ht/~rabbits/uxn"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all
git submodule update --quiet --init

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

./build.sh --no-run

mkdir -p "$PKG$PREFIX/bin"
cp bin/uxn{asm,cli,emu} "$PKG$PREFIX/bin/"

mkdir -p "$PKG$PREFIX/share/$PRGNAM/"
cp boot.rom "$PKG$PREFIX/share/$PRGNAM/"

mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp -R projects/ LICENSE README.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

# embaumement
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (An assembler and emulator for the Uxn stack-machine)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://git.sr.ht/~rabbits/uxn
$PRGNAM:
EOF

# empaquetage
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
