#!/bin/sh
set -x

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-0.3.0}

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o 64)

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# Cleaning
( cd $TMP
    rm -fr $PRGNAM-$VERSION
    rm -fr $PKG
)

# Fetching sources
( cd $TMP
    [ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && \
        wget -c http://downloads.sourceforge.net/project/$PRGNAM/$PRGNAM/$VERSION/$PRGNAM-$VERSION.tar.gz/download -O $CWD/$PRGNAM-$VERSION.tar.gz
    tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
)

# Preparation
( cd $TMP/$PRGNAM-$VERSION
    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Configuration
( cd $TMP/$PRGNAM-$VERSION
    ./configure \
        --prefix=$PREFIX \
        --mandir=$PREFIX/man \
        --infodir=$PREFIX/info \
        --libdir=$PREFIX/lib$LIBSUFFIX \
        --libexecdir=$PREFIX/libexec \
        --docdir=$PREFIX/doc/$PRGNAM
)

# Building
( cd $TMP/$PRGNAM-$VERSION
    make
)

# Installation
( cd $TMP/$PRGNAM-$VERSION
    make install install.TAGS DESTDIR=$PKG

    cp A* C* H* INSTALL NEWS README TODO $PKG$PREFIX/doc/$PRGNAM
)

# Cleaning
( cd $PKG
    find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
    find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

    find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Packaging
( cd $PKG
    mkdir install
    cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (WindowMaker dock-like)
$PRGNAM:
$PRGNAM: xdock is a software that emulates the Window Maker docks,
$PRGNAM: with the following differences:
$PRGNAM:    * runs in any window manager
$PRGNAM:    * client/server - it works in a client/server way, where a server sits in the
$PRGNAM: right side of the screen, and the docks are clients that connect to that server;
$PRGNAM:    * easy to program - programming the Window Maker docks was a hard job. But
$PRGNAM: xdock provides a API that makes programming much easier! 
$PRGNAM:
$PRGNAM: http://xdock.sourceforge.net/
EOF

    makepkg -l n -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
)

