#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH="noarch"   # hardcode ARCH
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

DOCROOT=${DOCROOT:-/var/www/vhosts/nextcloud-server/htdocs}

PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
REPOSITORIES=/home/installs/SlackBuilds/repositories

set -eu

APPNAM=${PRGNAM#nextcloud-}

rm -rf $PKG
mkdir -p $TMP $OUTPUT $PKG/$DOCROOT/apps/
cd $PKG/$DOCROOT/apps/

[ ! -e $REPOSITORIES/$PRGNAM ] && git clone https://github.com/brantje/nextnote.git $REPOSITORIES/$PRGNAM

( cd $REPOSITORIES/$PRGNAM
  git pull
)

VERSION="git_$( cd $REPOSITORIES/$PRGNAM && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORIES/$PRGNAM $APPNAM

cd $APPNAM
rm -fr .git .travis.yml
#VERSION=$(cat appinfo/info.xml | grep -i version\> | sed 's|</\?version>||g' | tr -d \   | sed 's|\t||g' )

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 -o -perm 755 \) \
     -exec chmod 750 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 -o -perm 644 \) \
     -exec chmod 640 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM
cp -a COPYING README.md AUTHORS.md $PKG/usr/doc/$PRGNAM

# Change ownership and perms
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/
chmod 0750 $PKG/$DOCROOT/apps/$APPNAM


mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A full Evernote / OneNote style WYSIWYG note editor for Nextcloud)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: 
$PRGNAM: https://github.com/brantje/nextnote
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
