#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=nightly
BUILD=1

ARCH=$(uname -m)

REPOSITORIES=/home/installs/SlackBuilds/repositories

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG
mkdir -p $TMP $PKG

# get sources
[ "$VERSION" == "nightly" ] && rm $CWD/rustc-${VERSION}-src.tar.gz
[ ! -e $CWD/rustc-${VERSION}-src.tar.gz ] && wget -c https://static.rust-lang.org/dist/rustc-${VERSION}-src.tar.gz

cd $TMP
tar xvf $CWD/rustc-${VERSION}-src.tar.gz

cd $PRGNAM-$VERSION
./configure \
	--prefix=$PREFIX
make
make DESTDIR=$PKG install
mv $PKG/usr/share/man $PKG/usr/
find $PKG/usr/man/ -type f -name \*.\? -exec gzip -9 {} \;

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (a safe, concurrent, practical language)
$PRGNAM: 
$PRGNAM:  Rust is a curly-brace, block-structured expression language.
$PRGNAM: It visually resembles the C language family, but differs significantly in
$PRGNAM: syntactic and semantic details. Its design is oriented toward concerns of
$PRGNAM: “programming in the large”, that is, of creating and maintaining boundaries
$PRGNAM: – both abstract and operational – that preserve large-system integrity,
$PRGNAM: availability and concurrency.
$PRGNAM: 
$PRGNAM: http://www.rust-lang.org/
$PRGNAM: 
EOF

chown -R root:root *

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
