#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +"%Y.%m.%d")}
BUILD=${BUILD:-1}

ARCH=noarch

TAG=cyco
TMP=${TMP:-/tmp/$TAG}
PKG=${PKG:-$TMP/pkg-$PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

PREFIX=${PREFIX:-/usr}

# cleaning
rm -fr $PKG

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cd $PKG$PREFIX/doc/$PRGNAM
lftp -e "mget *; bye" http://www.microlinux.fr/howtos/

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (Howtos en français de Kiki Novac)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www.microlinux.fr/
$PRGNAM: 
EOF

chown -R root:root *

makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
