#!/bin/bash

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=5.0-beta2
BUILD=1

ARCH=$(uname -m)

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

mkdir -p $PKG/srv/www/htdocs/

[ ! -e $CWD/${PRGNAM}-$VERSION.tar.bz2 ] && wget -c http://downloads.sourceforge.net/phppgadmin/${PRGNAM}-$VERSION.tar.bz2 -O $CWD/${PRGNAM}-$VERSION.tar.bz2
( cd $PKG/srv/www/htdocs/
    tar xf $CWD/${PRGNAM}-$VERSION.tar.bz2
    mv ${PRGNAM}-$VERSION $PRGNAM
)

( cd $PKG
    mkdir -p install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (web-based administration tool for PostgreSQL)
$PRGNAM: 
$PRGNAM: phpPgAdmin is a web-based administration tool for PostgreSQL.
$PRGNAM: It is perfect for PostgreSQL DBAs, newbies and hosting services.
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://phppgadmin.sourceforge.net
$PRGNAM: 
EOF

    chown -R root:root *

    makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr - _)-$ARCH-$BUILD$TAG.txz
)
