#!/bin/sh

PRGNAM=$(basename $(pwd))
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH=font
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

CWD=$(pwd)

# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
TMP=${TMP:=/tmp/$TAG}
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
FONTDIR="/usr/share/fonts"

# Create working directories:
mkdir -p $OUTPUT          # place for the package to be saved
mkdir -p $PKG             # place for the package to be built
rm -rf $PKG/*             # always erase old package's contents
rm -rf $OUTPUT/{configure,make,install,error,/sbin/makepkg}-$PRGNAM.log


[ ! -e $REPOSITORY ] && git clone https://github.com/mozilla/Fira.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

# Move the fonts into place:
mkdir -p $PKG$FONTDIR/ $PKG/usr/doc/
cp -R $REPOSITORY $PKG/usr/doc/$PRGNAM
rm -fr $PKG/usr/doc/$PRGNAM/.git{ignore,}
mv $PKG/usr/doc/$PRGNAM/ttf $PKG$FONTDIR/TTF
mv $PKG/usr/doc/$PRGNAM/otf $PKG$FONTDIR/OTF

# Post-install script:
mkdir -p $PKG/install
cat <<EOT > $PKG/install/doinst.sh
# Update X font indexes and the font cache:
if [ -x ./usr/bin/mkfontdir ]; then
  chroot . /usr/bin/mkfontscale $FONTDIR
  chroot . /usr/bin/mkfontdir $FONTDIR
fi
if [ -x ./usr/bin/fc-cache ]; then
  chroot . /usr/bin/fc-cache -f $FONTDIR
fi
EOT

# Add a package description:
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Mozilla's new typeface)
$PRGNAM:
$PRGNAM: Mozilla's new typeface, used in Firefox OS
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://github.com/mozilla/Fira
$PRGNAM: http://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/
$PRGNAM:
EOF

# Build the package:
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
