#!/bin/bash

# variables
GITHUB_REPO=srvrco/checkssl
VERSION=${VERSION:-latest}
BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/home/installs/SlackBuilds/_repositories/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --all
[ "x$VERSION" == "xlatest" ] && VERSION=$(git describe --tags --abbrev=0)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

mkdir -p $PKG$PREFIX/bin
cp $REPOSITORY/checkssl $PKG$PREFIX/bin/
chmod 755 $PKG$PREFIX/bin/*

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp $REPOSITORY/LICENSE $REPOSITORY/README $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (checks ssl certs for a set of domains.)
$PRGNAM:
$PRGNAM: With the good work by "Let’s Encrypt" in providing free SSL certs for
$PRGNAM: users, I wanted a quick way to check all the domains I look after to
$PRGNAM: determine which ones have correct SSL certs, and which ones are in
$PRGNAM: need of updating etc.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/${GITHUB_REPO}/
$PRGNAM:
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
