#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=noarch

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
[ ! -e $REPOSITORY ] && git clone http://github.com/autotelicum/Smooth-CoffeeScript.git $REPOSITORY
( cd $REPOSITORY && git pull )
VERSION="git_$( cd $REPOSITORY && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORY $PKG$PREFIX/doc/$PRGNAM
find $PKG$PREFIX/doc/$PRGNAM -name \.git\* -exec rm -fr {} \;

( cd $PKG
  mkdir -p install
  cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (A book on functional programming in CoffeeScript)
$PRGNAM:
$PRGNAM: Smooth CoffeeScript is a free book about CoffeeScript and programming.
$PRGNAM: No previous programming knowledge is required. Over 200 pages and
$PRGNAM: 35 exercises. Download includes book and full source code with
$PRGNAM: and without solutions.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://github.com/autotelicum/Smooth-CoffeeScript#readme
$PRGNAM:
EOF

  chown -R root:root *

  makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
)
