#!/bin/sh

# variables
VERSION=git_$(date +"%Y.%m.%d_%H.%M")
BUILD=1

TAG=cyco
OUTPUT=/tmp
TMP=${TMP:=/tmp/$TAG}
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=x86_64

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM-$VERSION

mkdir -p $PKG

# mise en place
cd $TMP
if [ ! -e $REPOSITORY ] ; then
        mkdir -p $(dirname $REPOSITORY)
        cd $(dirname $REPOSITORY)
        git clone git://git.webkit.org/WebKit.git $PRGNAM
fi

( cd $REPOSITORY
    git pull
)

cp -R $REPOSITORY $TMP/$PRGNAM-$VERSION
( cd $TMP/$PRGNAM-$VERSION

    find . -name ".git*" -exec rm -fr {} \;

    CFLAGS="$SLKCFLAGS" \
        CXXFLAGS="$SLKCFLAGS" \
        ./autogen.sh \
        --prefix=$PREFIX \
        --libdir=$PREFIX/lib${LIBDIRSUFFIX} \
        --mandir=$PREFIX/man \
        --sysconfdir=/etc \
        --localstatedir=/var/lib \
        --enable-fast-malloc \
        --with-font-backend=pango \
        --disable-static \
        --build=$ARCH-slackware-linux

    make

    make install DESTDIR=$PKG
)

# correction
( cd $PKG
    chown -R root:root *

    [ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9f {} \;
)

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (web browser engine)
$PRGNAM:
$PRGNAM: WebKit is an open source web browser engine. WebKit is also the name of the
$PRGNAM: Mac OS X system framework version of the engine that's used by Safari,
$PRGNAM: Dashboard, Mail, and many other OS X applications. WebKit's HTML and JavaScript
$PRGNAM: code began as a branch of the KHTML and KJS libraries from KDE.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://webkit.org/
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
