#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=$(date +"%Y.%m.%d_%H.%M")
BUILD=1

ARCH=noarch

TAG=cyco
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORIES=/home/installs/SlackBuilds/repositories/
PREFIX=/usr

# cleaning
rm -fr $PKG

# get sources
if [ ! -e $REPOSITORIES/$PRGNAM ]; then
    mkdir -p $REPOSITORIES/$PRGNAM
    ( cd $REPOSITORIES/$PRGNAM
        httrack http://www-cs-students.stanford.edu/~blynn/gitmagic/
    )
else
    ( cd $REPOSITORIES/$PRGNAM
        httrack --update
    )
fi

mkdir -p $PKG$PREFIX/doc/
cp -R $REPOSITORIES/$PRGNAM $PKG$PREFIX/doc/$PRGNAM

cd $PKG
mkdir -p install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM («Git Magic» book)
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: 
$PRGNAM: http://www-cs-students.stanford.edu/~blynn/gitmagic/
$PRGNAM: 
EOF

chown -R root:root *

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
