#!/bin/sh

# variables
TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)
OUTPUT=/tmp

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

DOCS="LICENSE README.md"

ARCH=$(uname -m)
BUILD=1

PREFIX=/usr

SLCKFLAGS="-fPIC -O2"

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/Matoking/protontricks.git $REPOSITORY
( cd $REPOSITORY && git pull )

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
VERSION="$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)"

# installation
python3 ./setup.py install --root=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM
cp -R $DOCS $PKG/usr/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A simple wrapper that does winetricks things for Proton enabled games)
$PRGNAM:
$PRGNAM: requires Winetricks.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/Matoking/protontricks
$PRGNAM:
EOF

# empaquetage
cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
