#!/bin/bash

# variables
UPSTREAM_REPO=https://github.com/tinted-theming/tinty
VERSION=${VERSION:-$(curl -s https://api.github.com/repos/tinted-theming/tinty/releases/latest | jq -r .tag_name)} # or VERSION=trunk

BUILD=${BUILD:-1}

TAG=gwh
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-/var/cache/SlackBuilds.gwh/$PRGNAM}
PREFIX=${PREFIX:-/usr}

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY
cd $REPOSITORY
git pull --all

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

cargo build --release

mkdir -p $PKG$PREFIX/bin
find target/release/ -type f -executable -maxdepth 1 -exec cp {} $PKG$PREFIX/bin/ \;
chmod 755 $PKG$PREFIX/bin/*

mkdir -p $PKG/usr/share/bash-completion/completions
$PKG/usr/bin/tinty generate-completion bash > $PKG/usr/share/bash-completion/completions/tinty
chmod 0644 $PKG/usr/share/bash-completion/completions/tinty

mkdir -p $PKG/usr/share/zsh/site-functions
$PKG/usr/bin/tinty generate-completion zsh > $PKG/usr/share/zsh/site-functions/_tinty
chmod 0644 $PKG/usr/share/zsh/site-functions/_tinty

# move doc/ to the appropriate location
mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp *.md LICENSE* $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

[ -d $PKG$PREFIX/man ] && find $PKG$PREFIX/man -type f -not -name \*.gz -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A base16 and base24 color scheme manager)
$PRGNAM:
$PRGNAM: Change the theme of your terminal, text editor and anything else with
$PRGNAM: one command. Immediately switch between over 250 themes!
$PRGNAM:
$PRGNAM: Tinty is a Base16 and Base24 theming manager for all Tinted Theming
$PRGNAM: projects including any third-party template repository that follows
$PRGNAM: the Base16 builder specification.
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/tinted-theming/tinty
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
