#!/bin/bash

cd "$(dirname "$0")" || exit 1
CWD=$(pwd)

# variables
UPSTREAM_REPO=${UPSTREAM_REPO:-"https://github.com/tinted-theming/tinty"}
VERSION=${VERSION:-"trunk"}
BUILD=${BUILD:-1}

TAG="gwh"
TMP="/tmp/$TAG"

PRGNAM=$(basename "$CWD")
PKG="$TMP/pkg-$PRGNAM"
OUTPUT=${OUTPUT:-"/tmp"}

ARCH=${ARCH:-$(uname -m)}

REPOSITORY=${REPOSITORY:-"/var/cache/SlackBuilds.gwh/$PRGNAM/"}
PREFIX=${PREFIX:-"/usr"}

[ ! -e "$REPOSITORY" ] && git clone "${UPSTREAM_REPO}.git" "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --quiet --all

mkdir -p "$TMP"

rm -fr "$PKG" "${TMP:?}/$PRGNAM"

mkdir -p "$PKG"

cp -R "$REPOSITORY" "$TMP/$PRGNAM"
cd "$TMP/$PRGNAM" || exit 1
case $VERSION in
    trunk)
        VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
        ;;
    latest)
        VERSION="$(git tag --sort=-version:refname | head -n1)"
        git checkout --quiet "$VERSION"
        ;;
    *)
        git checkout --quiet "$VERSION"
        ;;
esac

PACKAGE_NAME="$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ -n "${PRINT_PACKAGE_NAME}" ]; then
    echo "$PACKAGE_NAME"
    exit 0
fi

#configuration

#build
cargo build --release

#install
mkdir -p "$PKG$PREFIX/bin"
find target/release/ -type f -executable -maxdepth 1 -exec cp {} "$PKG$PREFIX/bin/" \;
chmod 755 "$PKG$PREFIX/bin"/*

mkdir -p "$PKG"/usr/share/bash-completion/completions
"$PKG"/usr/bin/tinty generate-completion bash > "$PKG"/usr/share/bash-completion/completions/tinty
chmod 0644 "$PKG"/usr/share/bash-completion/completions/tinty

mkdir -p "$PKG"/usr/share/zsh/site-functions
"$PKG"/usr/bin/tinty generate-completion zsh > "$PKG"/usr/share/zsh/site-functions/_tinty
chmod 0644 "$PKG"/usr/share/zsh/site-functions/_tinty

#install docs
mkdir -p "$PKG$PREFIX/doc/$PRGNAM"
cp LICENSE* ./*.md "$PKG$PREFIX/doc/$PRGNAM"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

[ -d "$PKG$PREFIX/man" ] && find "$PKG$PREFIX/man" -type f -not -name \*.gz -exec gzip -9 {} \;

# packaging
mkdir -p "$PKG/install"

cat <<EOF > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

       |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A base16 and base24 color scheme manager)
$PRGNAM:
$PRGNAM: Change the theme of your terminal, text editor and anything else with
$PRGNAM: one command. Immediately switch between over 250 themes!
$PRGNAM:
$PRGNAM: Tinty is a Base16 and Base24 theming manager for all Tinted Theming
$PRGNAM: projects including any third-party template repository that follows
$PRGNAM: the Base16 builder specification.
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/tinted-theming/tinty
EOF

# empaquetage
cd "$PKG" || exit 1
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PACKAGE_NAME"
