#!/bin/bash
set -x

PRGNAM=wmname
VERSION=0.1

BUILD=1

ARCH=$(uname -m)
LIBSUFFIX=$(echo $ARCH | grep -o "\(64\)")

CWD=$(pwd)
TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

PREFIX=/usr

# Cleaning
( cd $TMP
    rm -fr $PRGNAM-$VERSION
    rm -fr $PKG
)

# Fetching sources
( cd $TMP
    [ ! -e $CWD/$PRGNAM-$VERSION.tar.?z* ] && ( cd $CWD
        wget -c http://dl.suckless.org/tools/$PRGNAM-$VERSION.tar.gz
    )
    [ -e $CWD/$PRGNAM-$VERSION.tar.?z* ] \
        && tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
)

# Preparation
( cd $TMP/$PRGNAM-$VERSION
    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Configuration
( cd $TMP/$PRGNAM-$VERSION
    sed -i "s|/usr/local|$PREFIX|g" config.mk
)

# Building
( cd $TMP/$PRGNAM-$VERSION
    make
)

# Installation
( cd $TMP/$PRGNAM-$VERSION
	make install DESTDIR=$PKG
    mkdir -p $PKG$PREFIX/doc/$PRGNAM
    cp LICENSE $PKG$PREFIX/doc/$PRGNAM
)

# Cleaning
( cd $PKG
    find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
    find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

    find $PKG$PREFIX/man -type f -name "*.?" -exec gzip -9 {} \;

    chown -R root:root .
    find . \
        \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
        -exec chmod 755 {} \; -o \
        \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
        -exec chmod 644 {} \;
)

# Packaging
( cd $PKG
    mkdir install
    cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM ()
$PRGNAM: 
$PRGNAM: wmname prints/sets the window manager name property of the root window similar
$PRGNAM: to how hostname(1) behaves.
$PRGNAM: wmname is a nice utility to fix problems with JDK versions and other broken
$PRGNAM: programs assuming a reparenting window manager for instance.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: http://tools.suckless.org/wmname
$PRGNAM:
EOF

    makepkg -l y -c n $OUTPUT/$PRGNAM-$(echo $VERSION | tr -d '-')-$ARCH-$BUILD$TAG.txz
)

