#!/bin/bash
set -x -e

VERSION=${VERSION:-21.0.2}
RANDOMHEX=${RANDOMHEX:-f2283984656d49d69e91c558476027ac}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG

mkdir -p $TMP

[ -e $TMP/java/ ] && rm -fr $TMP/java/

cp -a /home/installs/mirrors/slackware64-current/extra/java/ $TMP/

cd $TMP/java/ || exit 1

wget -c "https://download.java.net/java/GA/jdk${VERSION}/${RANDOMHEX}/13/GPL/openjdk-${VERSION}_linux-x64_bin.tar.gz" -O "./jdk-${VERSION}_linux-x64_bin.tar.gz"

BUILD=$BUILD$TAG ./java.SlackBuild "./jdk-${VERSION}_linux-x64_bin.tar.gz"
