#!/bin/bash

# variables
VERSION=${VERSION:-"trunk"}
BUILD=1

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
CWD=$(pwd)

PRGNAM=$(basename $CWD)
PKG=$TMP/pkg-$PRGNAM

ARCH=$(uname -m)

REPOSITORY=/home/installs/SlackBuilds/repositories/$PRGNAM
PREFIX=/usr

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
[ ! -e $REPOSITORY ] && git clone https://github.com/ifreund/river --recursive $REPOSITORY
cd $REPOSITORY
git pull --all
git submodule update

cp -R $REPOSITORY $TMP/
cd $TMP/$PRGNAM/

[ "x$VERSION" == "xtrunk" ] && VERSION="git_$(git log -1 --format=%h_%ad --date=format:%Y.%m.%d)" || git checkout $VERSION

zig build -Drelease-safe --prefix $PKG$PREFIX install

mv $PKG$PREFIX/share/man $PKG$PREFIX/

cat <<EOF > $PKG$PREFIX/bin/start_river.sh
#!/bin/bash

export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SAL_USE_VCLPLUGIN=gtk3

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export GDK_BACKEND=wayland
export CLUTTER_BACKEND=gdk

export SDL_VIDEODRIVER=wayland

export XDG_CURRENT_DESKTOP=river

[ -e $HOME/.profile ] && . $HOME/.profile

exec /usr/bin/river
EOF
chmod +x $PKG$PREFIX/bin/start_river.sh

mkdir -p $PKG/usr/share/wayland-sessions/
cat <<EOF > $PKG/usr/share/wayland-sessions/river.desktop
[Desktop Entry]
Name=River
Comment=a modern wayland compositor
Exec=/usr/bin/start_river.sh
Type=Application
EOF

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -a docs/ example/ contrib/ AUTHORS LICENSE *.md $PKG$PREFIX/doc/$PRGNAM/

# correction
cd $PKG
chown -R root:root *
find $PKG$PREFIX/man -name "*.?" -type f -exec gzip -9 {} \;

# embaumement
mkdir -p $PKG/install

cat <<EOF > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler------------------------------------------------------|
$PRGNAM: $PRGNAM (A dynamic tiling wayland compositor)
$PRGNAM:
$PRGNAM: River is a dynamic tiling wayland compositor with flexible runtime
$PRGNAM: configuration.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/ifreund/river
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
