#!/bin/bash
set -x

CWD=$(pwd)

PRGNAM=$(basename "$CWD")

BUILD=1
VERSION=${VERSION:-latest}

ARCH=$(uname -m)

TAG=gwh
OUTPUT=/tmp
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM

REPOSITORY=/home/installs/SlackBuilds/_repositories/$PRGNAM

PREFIX=/usr

mkdir -p $TMP

# Cleaning
rm -fr "${TMP:?}"/"$PRGNAM" "$PKG"

# Fetching sources
[ ! -e "$REPOSITORY" ] && git clone https://src.le-moine.org/gwh/saturnng.git "$REPOSITORY"
cd "$REPOSITORY" || exit 1
git pull --all

cp -R "$REPOSITORY" $TMP/"$PRGNAM"

# Preparation
cd $TMP/"$PRGNAM" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git describe --tags --abbrev=0)
[ "$VERSION" == "" ] && VERSION=trunk
if [ "$VERSION" == "trunk" ]; then
    VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)"
else
    git checkout "$VERSION"
fi

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Building
make all PREFIX=/usr

# Installation
make install DESTDIR="$PKG" PREFIX=/usr

# Cleaning
cd "$PKG" || exit 1
find -0 . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find -0 . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

[ -d "$PKG$PREFIX"/man ] && find "$PKG$PREFIX"/man -type f -name "*.?" -exec gzip -9 {} \;
[ -d "$PKG$PREFIX"/info ] && find "$PKG$PREFIX"/info -type f -name "*.info" -exec gzip -9 {} \;

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
     -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
     -exec chmod 644 {} \;

# Packaging
mkdir install
cat <<EOF > install/slack-desc
$PRGNAM: $PRGNAM (HP48 emulator)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://www.hpcalc.org/details/4382
$PRGNAM: https://src.le-moine.org/gwh/saturn_bertolotti.git
EOF

rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT/$PRGNAM-$(echo "$VERSION" | tr -d '-')-$ARCH-$BUILD$TAG.txz"
