#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
UPSTREAM_REPO=https://github.com/fish-shell/fish-shell
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

SLCKFLAGS=" -O "

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone ${UPSTREAM_REPO}.git $REPOSITORY

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

# configuration
cmake \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_MANDIR=$PREFIX/man \
    -DCMAKE_INSTALL_DOCDIR=$PREFIX/doc/$PRGNAM \
    .

# compilation
make -j$(nproc)

# installation
make install DESTDIR=$PKG
mkdir -p $PKG$PREFIX/man/man1
mv $PKG$PREFIX/man/lsyncd.1 $PKG$PREFIX/man/man1/

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R COPYING ChangeLog INSTALL *.md examples $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

find $PKG -name \.git\* -exec rm -fr {} \;

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# Strip binaries
cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (The user-friendly command line shell)
$PRGNAM:
$PRGNAM: fish is a smart and user-friendly command line shell for macOS, Linux,
$PRGNAM: and the rest of the family. fish includes features like syntax highlighting,
$PRGNAM: autosuggest-as-you-type, and fancy tab completions that just work,
$PRGNAM: with no configuration required.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://fishshell.com/
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
