#!/bin/sh

CWD=$(pwd)

PRGNAM=$(basename $CWD)
VERSION=${VERSION:-$(date +%F | tr - .)}
ARCH="noarch"   # hardcode ARCH
BUILD=${BUILD:-1}
TAG=${TAG:-gwh}

DOCROOT=${DOCROOT:-/var/www/vhosts/nextcloud-server/htdocs}

PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

TMP=${TMP:-/tmp/$TAG}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
REPOSITORIES=/home/installs/SlackBuilds/repositories

set -eu

APPNAM=${PRGNAM#nextcloud-}

rm -rf $PKG
mkdir -p $TMP $OUTPUT $PKG/$DOCROOT/themes/
cd $PKG/$DOCROOT/themes/

[ ! -e $REPOSITORIES/$PRGNAM ] && git clone https://github.com/mwalbeck/nextcloud-breeze-dark.git $REPOSITORIES/$PRGNAM

( cd $REPOSITORIES/$PRGNAM
  git pull
)

VERSION="git_$( cd $REPOSITORIES/$PRGNAM && git log -1 --format=%h_%ad --date=format:%Y.%m.%d )"

cp -R $REPOSITORIES/$PRGNAM $APPNAM

cd $APPNAM
rm -fr .git .travis.yml

chown -R root:root .
find . \
     \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 -o -perm 755 \) \
     -exec chmod 750 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 -o -perm 644 \) \
     -exec chmod 640 {} \;

# Change ownership and perms
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/
chmod 0750 $PKG/$DOCROOT/themes/$APPNAM

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (A Breeze Dark theme for Nextcloud)
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://github.com/mwalbeck/nextcloud-breeze-dark
$PRGNAM:
EOF

cd $PKG
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
