#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename $CWD)
GITHUB_REPO=axkibe/lsyncd
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=1

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

SLCKFLAGS=" -O "

# nettoyage préalable
rm -fr $PKG $TMP/$PRGNAM

mkdir -p $PKG

# mise en place
cd $TMP
[ ! -e $REPOSITORY ] && git clone https://github.com/${GITHUB_REPO}.git $REPOSITORY

cp -R $REPOSITORY $TMP/$PRGNAM
cd $TMP/$PRGNAM
[ "x$VERSION" == "xlatest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "x$VERSION" == "x" ] && VERSION=trunk
[ "x$VERSION" == "xtrunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" || git checkout $VERSION

# configuration
cmake \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    .

# compilation
make -j$(nproc)

# installation
make install DESTDIR=$PKG
mkdir -p $PKG$PREFIX/man/man1
mv $PKG$PREFIX/man/lsyncd.1 $PKG$PREFIX/man/man1/

mkdir -p $PKG$PREFIX/doc/$PRGNAM
cp -R COPYING ChangeLog INSTALL *.md examples $PKG$PREFIX/doc/$PRGNAM

# correction
cd $PKG
chown -R root:root *

find $PKG -name \.git\* -exec rm -fr {} \;

[ -d $PKG/usr/man ] && find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# # Strip binaries
# cd $PKG
# find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
# find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# embaumement
mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM (Live Syncing Daemon)
$PRGNAM:
$PRGNAM: Lsyncd watches a local directory trees event monitor interface (inotify or
$PRGNAM: fsevents). It aggregates and combines events for a few seconds and then
$PRGNAM: spawns one (or more) process(es) to synchronize the changes. By default this
$PRGNAM: is rsync. Lsyncd is thus a light-weight live mirror solution that is
$PRGNAM: comparatively easy to install not requiring new filesystems or block devices
$PRGNAM: and does not hamper local filesystem performance.
$PRGNAM:
$PRGNAM: https://axkibe.github.io/lsyncd/
EOF

# empaquetage
rm -f $PKG/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend $OUTPUT/$PRGNAM-$(echo $VERSION | sed 's/-//g')-$ARCH-$BUILD$TAG.txz
