#!/bin/bash

# variables
CWD=$(pwd)

PRGNAM=$(basename "$CWD")
UPSTREAM_REPO="https://github.com/hyprwm/$PRGNAM"
VERSION=${VERSION:-latest}
ARCH=${ARCH:-$(uname -m)}
BUILD=3

TAG=gwh
TMP=/tmp/$TAG
PKG=$TMP/pkg-$PRGNAM
OUTPUT=/tmp

REPOSITORY=/var/cache/SlackBuilds.gwh/$PRGNAM

PREFIX=/usr

# nettoyage préalable
rm -fr "$PKG" "$TMP"/"$PRGNAM"

mkdir -p "$PKG"

# mise en place
cd "$TMP" || exit 1
[ ! -e "$REPOSITORY" ] && git clone --quiet "${UPSTREAM_REPO}.git" "$REPOSITORY"

cd "$REPOSITORY" || exit1
git pull --quiet --all

cp -R "$REPOSITORY" "$TMP"/"$PRGNAM"
cd "$TMP"/"$PRGNAM" || exit 1

[ "$VERSION" == "latest" ] && VERSION=$(git tag --sort=-version:refname | head -n1)
[ "$VERSION" == "" ] && VERSION=trunk
[ "$VERSION" == "trunk" ] && VERSION="git_r$(git rev-list --count HEAD)_$(git log -1 --format=%h)" # || git checkout --quiet $VERSION
git submodule update --quiet --init --recursive

# configuration
cmake --no-warn-unused-cli \
      -DSYSCONFDIR=/etc \
      -DCMAKE_BUILD_TYPE:STRING=Release \
      -DCMAKE_INSTALL_PREFIX:STRING=${PREFIX} \
      -DNO_SYSTEMD:STRING=true \
      -DNO_UWSM:STRING=true \
      -S . \
      -B ./build

# compilation
cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`

# installation
cmake --install build --prefix "$PKG"$PREFIX --strip

mkdir -p "$PKG$PREFIX/doc/$PRGNAM/"
cp -R LICENSE VERSION ./*.md docs/ example/ assets/ "$PKG$PREFIX/doc/$PRGNAM/"

cat <<EOF > "$PKG$PREFIX/bin/start_hyprland.sh"
#!/bin/bash

#set -e

# LOGFILE=~/.wsession-errors
# true > \$LOGFILE
# exec &> \$LOGFILE

set -x
echo "hyprland Starting: \$( date )"

# Uncomment if mouse pointer is invisible
#export WLR_NO_HARDWARE_CURSORS=1

# unset QT_QPA_PLATFORM


# # vulklan seems buggy with Intel IGP
# if \$(lsmod | grep -q "^i915.*$"); then
#    export WLR_RENDERER=gles2
# else
#    export WLR_RENDERER=vulkan
# fi

# export CLUTTER_BACKEND=wayland
# export SDL_VIDEODRIVER=wayland
# export XDG_SESSION_DESKTOP=hyprland
# export XDG_SESSION_TYPE=wayland
# export QT_PLATFORMTHEME=qt5ct
# export QT_PLATFORM_PLUGIN=qt5ct

# export QT_QPA_PLATFORMTHEME=qt5ct
# export MOZ_ENABLE_WAYLAND=1
# export XDG_CURRENT_DESKTOP=hyprland
# export XDG_PICTURES_DIR=~/.wallpapers

# export HYPRLANDSOCK=/run/user/\$(id -u)/hyprland-ipc.\$(id -u).\$(pgrep -x hyprland).sock
# export XDG_RUNTIME_DIR=/tmp/xdg-runtime-\$(id -u)

# mkdir -p \$XDG_RUNTIME_DIR
# chmod 0700 \$XDG_RUNTIME_DIR

# # avoid wlr error
# unset DISPLAY

killall daemon

exec dbus-run-session /usr/bin/Hyprland
EOF
chmod +x "$PKG$PREFIX/bin/start_hyprland.sh"
sed -i 's|Exec=Hyprland|Exec=/usr/bin/start_hyprland.sh|' "$PKG$PREFIX/share/wayland-sessions/hyprland.desktop"

# correction
cd "$PKG" || exit 1
chown -R root:root ./*

mv "$PKG"/usr/share/man "$PKG"/usr/

[ -d "$PKG"/usr/man ] && find "$PKG"/usr/man -type f -name "*.?" -exec gzip -9f {} \;

# embaumement
mkdir -p "$PKG"/install
cat <<EOF > "$PKG"/install/slack-desc
$PRGNAM: $PRGNAM ( Wayland compositor )
$PRGNAM:
$PRGNAM: Hyprland is an independent, highly customizable, dynamic tiling Wayland
$PRGNAM:  compositor that doesn't sacrifice on its looks.
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: https://hyprland.org
$PRGNAM: ${UPSTREAM_REPO}
$PRGNAM: REQUIRES: re2
EOF

# empaquetage
rm -f "$PKG"/{,usr/}lib$(uname -m | grep -o 64)/*.la
/sbin/makepkg --linkadd y --chown n --prepend "$OUTPUT"/"$PRGNAM-${VERSION//-/}-$ARCH-$BUILD$TAG.txz"
